XINU: device/lfs/lfibget.c File Reference
lfibget.c File Reference
#include <xinu.h>
Functions
void lfibget (did32 diskdev, ibid32 inum, struct lfiblk *ibuff)
Function Documentation
lfibget()
void lfibget (did32 diskdev, ibid32 inum, struct lfiblk * ibuff)
Definition at line 10 of file lfibget.c.
References ib2disp, ib2sect, LF_BLKSIZ, and read().
Referenced by lfiballoc(), lfsckfmt(), lfsetup(), and lftruncate().
 {
     char    *from, *to;     /* Pointers used in copying */
     int32   i;          /* Loop index used during copy  */
     char    dbuff[LF_BLKSIZ];   /* Buffer to hold disk block    */
     /* Read disk block that contains the specified index block */
     read(diskdev, dbuff, ib2sect(inum));
     /* Copy specified index block to caller's ibuff */
     from = dbuff + ib2disp(inum);
     to = (char *)ibuff;
     for (i=0 ; i<sizeof(struct lfiblk) ; i++)
         *to++ = *from++;
     return;
 }