XINU: system/getitem.c File Reference
getitem.c File Reference
キュー内のプロセスを操作するAPI（プロセス取得API）を提供する。
#include <xinu.h>
Functions
pid32 getfirst (qid16 q)
キューの先頭からプロセスを取り出す。
pid32 getitem (pid32 pid)
キューの任意の位置からプロセスを取り出す。
pid32 getlast (qid16 q)
キューの末尾からプロセスを取り出す。
Detailed Description
キュー内のプロセスを操作するAPI（プロセス取得API）を提供する。
Definition in file getitem.c.
Function Documentation
getfirst()
pid32 getfirst (qid16 q)
キューの先頭からプロセスを取り出す。
Parameters
[in] q プロセスを取り出すためのキューID（チェックなしで有効）
Returns
キューにプロセスがある場合はキューの先頭にあるプロセスID、
キューが空の場合はEMPTYを返す。
Definition at line 13 of file getitem.c.
References EMPTY, getitem(), isempty, queuehead, and queuetab.
Referenced by dequeue(), semdelete(), and semreset().
 {
     pid32 head;
     if (isempty(q))
     {
         return EMPTY;
     }
     head = queuehead(q);
     return getitem(queuetab[head].qnext);
 }
getitem()
pid32 getitem (pid32 pid)
キューの任意の位置からプロセスを取り出す。
Parameters
[in] pid 取り出すプロセスID
Returns
キューにプロセスがある場合はキューの末尾にあるプロセスID、
キューが空の場合はEMPTYを返す。
Definition at line 51 of file getitem.c.
References qentry::qnext, qentry::qprev, and queuetab.
Referenced by getfirst(), getlast(), kill(), suspend(), and unsleep().
 {
     pid32 prev, next;
     next = queuetab[pid].qnext; /* Following node in list   */
     prev = queuetab[pid].qprev; /* Previous node in list    */
     queuetab[prev].qnext = next;
     queuetab[next].qprev = prev;
     return pid;
 }
getlast()
pid32 getlast (qid16 q)
キューの末尾からプロセスを取り出す。
Parameters
[in] q プロセスを取り出すためのキューID（チェックなしで有効）
Returns
キューにプロセスがある場合はキューの末尾にあるプロセスID、
キューが空の場合はEMPTYを返す。
Definition at line 32 of file getitem.c.
References EMPTY, getitem(), isempty, queuetab, and queuetail.
 {
     pid32 tail;
     if (isempty(q))
     {
         return EMPTY;
     }
     tail = queuetail(q);
     return getitem(queuetab[tail].qprev);
 }