XINU: lib/memcpy.c File Reference
memcpy.c File Reference
Functions
void * memcpy (void *s, const void *ct, int n)
Function Documentation
memcpy()
void* memcpy (void * s, const void * ct, int n)
Definition at line 8 of file memcpy.c.
Referenced by addargs(), arp_in(), arp_resolve(), dhcp_bld_bootp_msg(), dhcp_bld_req(), dns_bldq(), dns_geta(), dns_getrname(), ethcontrol(), ethread(), ethwrite(), getlocalip(), icmp_mkpkt(), ip_send(), ipout(), raminit(), ramread(), ramwrite(), rdsread(), rdswrite(), udp_send(), and udp_sendto().
 {
     register int i;
     char *dst = (char *)s;
     char *src = (char *)ct;
     for (i = 0; i < n; i++)
     {
         *dst++ = *src++;
     }
     return s;
 }