XINU: system/wait.c File Reference
wait.c File Reference
#include <xinu.h>
Functions
syscall wait (sid32 sem)
Function Documentation
wait()
syscall wait (sid32 sem)
Definition at line 9 of file wait.c.
References currpid, disable(), enqueue(), isbadsem, OK, PR_WAIT, proctab, procent::prsem, procent::prstate, resched(), restore(), S_FREE, sentry::scount, semtab, sentry::squeue, sentry::sstate, and SYSERR.
Referenced by ethread(), ethwrite(), getbuf(), ipout(), lflclose(), lflcontrol(), lflgetc(), lflputc(), lflseek(), lfsetup(), lfsopen(), mark(), ptrecv(), ptsend(), rdsbufalloc(), rdsprocess(), rflclose(), rflread(), rflseek(), rflwrite(), rfscontrol(), rfsopen(), ttycontrol(), ttygetc(), ttyputc(), and xsh_ls().
 {
     intmask mask;           /* Saved interrupt mask     */
     struct  procent *prptr;     /* Ptr to process's table entry */
     struct  sentry *semptr;     /* Ptr to sempahore table entry */
     mask = disable();
     if (isbadsem(sem)) {
         restore(mask);
         return SYSERR;
     }
     semptr = &semtab[sem];
     if (semptr->sstate == S_FREE) {
         restore(mask);
         return SYSERR;
     }
     if (--(semptr->scount) < 0) {       /* If caller must block */
         prptr = &proctab[currpid];
         prptr->prstate = PR_WAIT;   /* Set state to waiting */
         prptr->prsem = sem;     /* Record semaphore ID  */
         enqueue(currpid,semptr->squeue);/* Enqueue on semaphore */
         resched();          /*   and reschedule */
     }
     restore(mask);
     return OK;
 }