XINU: system/clkhandler.c File Reference
clkhandler.c File Reference
#include <xinu.h>
Functions
void clkhandler ()
Function Documentation
clkhandler()
void clkhandler (void)
Definition at line 9 of file clkhandler.c.
References AM335X_TIMER1MS_TISR_OVF_IT_FLAG, clktime, count1000, firstid, isempty, preempt, QUANTUM, queuetab, resched(), sleepq, am335x_timer1ms::tisr, and wakeup().
Referenced by clkinit().
 {
     volatile struct am335x_timer1ms *csrptr =
             (struct am335x_timer1ms *)0x44E31000;
             /* Set csrptr to address of timer CSR       */
     /* If there is no interrupt, return */
     if((csrptr->tisr & AM335X_TIMER1MS_TISR_OVF_IT_FLAG) == 0) {
         return;
     }
     /* Acknowledge the interrupt */
     csrptr->tisr = AM335X_TIMER1MS_TISR_OVF_IT_FLAG;
     /* Increment 1000ms counter */
     count1000++;
     /* After 1 sec, increment clktime */
     if(count1000 >= 1000) {
         clktime++;
         count1000 = 0;
     }
     /* check if sleep queue is empty */
     if(!isempty(sleepq)) {
         /* sleepq nonempty, decrement the key of */
         /* topmost process on sleepq         */
         if((--queuetab[firstid(sleepq)].qkey) == 0) {
             wakeup();
         }
     }
     /* Decrement the preemption counter */
     /* Reschedule if necessary      */
     if((--preempt) == 0) {
         preempt = QUANTUM;
         resched();
     }
 }