XINU: system/ptdelete.c File Reference
ptdelete.c File Reference
ポートを削除し、待機中のプロセスとメッセージを解放する。
#include <xinu.h>
Functions
syscall ptdelete (int32 portid, int32(*disp)(int32))
ポートを削除し、待機中のプロセスとメッセージを解放する。
Detailed Description
ポートを削除し、待機中のプロセスとメッセージを解放する。
Definition in file ptdelete.c.
Function Documentation
ptdelete()
syscall ptdelete (int32 portid, int32(*)(int32) disp)
ポートを削除し、待機中のプロセスとメッセージを解放する。
Step1. 割り込みを禁止する。
Step2. ポートIDが不正、もしくはポートがALLOC状態でなければ割り込み状態を復元し、処理を終了する。
Step3. ポートを用いたメッセージと待機中プロセスを解放し、セマフォを削除する。
Step4. 次回のポート作成時には、今回削除したポートIDを使用するように設定する。
Step5. 割り込み状態を復元する。
Parameters
[in] portid 削除対象のポート
[in] disp 待機メッセージ処分用の関数ポインタ
Returns
成功時はOK、ポートIDが不正もしくはポートがALLOC状態以外の場合はSYSERRを返す。
Definition at line 19 of file ptdelete.c.
References _ptclear(), disable(), isbadport, OK, porttab, PT_ALLOC, PT_FREE, ptnextid, ptentry::ptstate, restore(), and SYSERR.
 {
     intmask mask;          /* Saved interrupt mask      */
     struct ptentry *ptptr; /* Pointer to port table entry   */
     mask = disable();
     if (isbadport(portid) ||
         (ptptr = &porttab[portid])->ptstate != PT_ALLOC)
     {
         restore(mask);
         return SYSERR;
     }
     _ptclear(ptptr, PT_FREE, disp);
     ptnextid = portid;
     restore(mask);
     return OK;
 }