XINU: device/tty/ttyinit.c File Reference
ttyinit.c File Reference
TTYラインのバッファおよびモードを初期化します
#include <xinu.h>
Functions
devcall ttyinit (struct dentry *devptr)
Variables
struct ttycblk ttytab [Ntty]
Detailed Description
TTYラインのバッファおよびモードを初期化します
Definition in file ttyinit.c.
Function Documentation
ttyinit()
devcall ttyinit (struct dentry * devptr)
Definition at line 17 of file ttyinit.c.
References dentry::dvcsr, dentry::dvintr, dentry::dvirq, dentry::dvminor, FALSE, uart_csreg::lcr, uart_csreg::mdr1, OK, semcreate(), set_evec(), TRUE, ttykickout(), ttytab, TY_BACKSP, TY_BACKSP2, TY_EOFCH, TY_FULLCH, TY_IMCOOKED, TY_KILLCH, TY_OBUFLEN, TY_STOPCH, TY_STRTCH, ttycblk::tyebuff, ttycblk::tyecrlf, ttycblk::tyehead, ttycblk::tyeof, ttycblk::tyeofch, ttycblk::tyetail, ttycblk::tyevis, ttycblk::tyibuff, ttycblk::tyicrlf, ttycblk::tyicursor, ttycblk::tyieback, ttycblk::tyiecho, ttycblk::tyierase, ttycblk::tyierasec, ttycblk::tyierasec2, ttycblk::tyifullc, ttycblk::tyihead, ttycblk::tyikill, ttycblk::tyikillc, ttycblk::tyimode, ttycblk::tyisem, ttycblk::tyitail, ttycblk::tyobuff, ttycblk::tyocrlf, ttycblk::tyoflow, ttycblk::tyohead, ttycblk::tyoheld, ttycblk::tyosem, ttycblk::tyostart, ttycblk::tyostop, ttycblk::tyotail, UART_DLL, UART_DLM, UART_FCR_EFIFO, UART_FCR_RRESET, UART_FCR_TRESET, UART_FCR_TRIG2, UART_LCR_8N1, UART_LCR_DLAB, and UART_MDR1_16X.
 {
     struct ttycblk *typtr;   /* Pointer to ttytab entry */
     struct uart_csreg *uptr; /* Address of UART's CSRs  */
     typtr = &ttytab[devptr->dvminor];
     /* Initialize values in the tty control block */
     typtr->tyihead = typtr->tyitail =      /* Set up input queue    */
         &typtr->tyibuff[0];                /*    as empty       */
     typtr->tyisem = semcreate(0);          /* Input semaphore   */
     typtr->tyohead = typtr->tyotail =      /* Set up output queue   */
         &typtr->tyobuff[0];                /*    as empty       */
     typtr->tyosem = semcreate(TY_OBUFLEN); /* Output semaphore  */
     typtr->tyehead = typtr->tyetail =      /* Set up echo queue */
         &typtr->tyebuff[0];                /*    as empty       */
     typtr->tyimode = TY_IMCOOKED;          /* Start in cooked mode  */
     typtr->tyiecho = TRUE;                 /* Echo console input    */
     typtr->tyieback = TRUE;                /* Honor erasing bksp    */
     typtr->tyevis = TRUE;                  /* Visual control chars  */
     typtr->tyecrlf = TRUE;                 /* Echo CRLF for NEWLINE*/
     typtr->tyicrlf = TRUE;                 /* Map CR to NEWLINE */
     typtr->tyierase = TRUE;                /* Do erasing backspace  */
     typtr->tyierasec = TY_BACKSP;          /* Primary erase char    */
     typtr->tyierasec2 = TY_BACKSP2;        /* Alternate erase char  */
     typtr->tyeof = TRUE;                   /* Honor eof on input    */
     typtr->tyeofch = TY_EOFCH;             /* End-of-file character*/
     typtr->tyikill = TRUE;                 /* Allow line kill   */
     typtr->tyikillc = TY_KILLCH;           /* Set line kill to ^U   */
     typtr->tyicursor = 0;                  /* Start of input line   */
     typtr->tyoflow = TRUE;                 /* Handle flow control   */
     typtr->tyoheld = FALSE;                /* Output not held   */
     typtr->tyostop = TY_STOPCH;            /* Stop char is ^S   */
     typtr->tyostart = TY_STRTCH;           /* Start char is ^Q  */
     typtr->tyocrlf = TRUE;                 /* Send CRLF for NEWLINE*/
     typtr->tyifullc = TY_FULLCH;           /* Send ^G when buffer   */
                                            /*   is full     */
     /* Initialize the UART */
     uptr = (struct uart_csreg *)devptr->dvcsr;
     /* Set baud rate */
     uptr->lcr = UART_LCR_DLAB;
     uptr->dlm = UART_DLM;
     uptr->dll = UART_DLL;
     uptr->lcr = UART_LCR_8N1; /* 8 bit char, No Parity, 1 Stop*/
     uptr->fcr = 0x00;         /* Disable FIFO for now       */
     /* Register the interrupt dispatcher for the tty device */
     set_evec(devptr->dvirq, (uint32)devptr->dvintr);
     /* Enable interrupts on the device: reset the transmit and  */
     /*   receive FIFOS, and set the interrupt trigger level     */
     uptr->fcr = UART_FCR_EFIFO | UART_FCR_RRESET |
                 UART_FCR_TRESET | UART_FCR_TRIG2;
     /* UART must be in 16x mode (TI AM335X specific) */
     uptr->mdr1 = UART_MDR1_16X;
     /* Start the device */
     ttykickout(uptr);
     return OK;
 }
Variable Documentation
ttytab
struct ttycblk ttytab[Ntty]
Definition at line 11 of file ttyinit.c.
Referenced by ttycontrol(), ttygetc(), ttyhandler(), ttyinit(), ttyputc(), and ttyread().