XINU: lib/fprintf.c File Reference
fprintf.c File Reference
#include <xinu.h>
#include <stdarg.h>
Functions
void _fdoprnt (char *, va_list, int(*)(did32, char), int)
int fprintf (int dev, char *fmt,...)
Function Documentation
_fdoprnt()
void _fdoprnt (char * , va_list , int(*)(did32, char) , int)
Referenced by fprintf().
fprintf()
int fprintf (int dev, char * fmt, ...)
Definition at line 14 of file fprintf.c.
References _fdoprnt(), putc(), va_end, and va_start.
Referenced by addattr(), addton(), devisid(), devonid(), getattrid(), getutime(), hexdump(), hexdump_print(), if(), main(), newdev(), newtype(), shell(), xsh_cat(), xsh_clear(), xsh_date(), xsh_devdump(), xsh_help(), xsh_kill(), xsh_ls(), xsh_memdump(), xsh_memstat(), xsh_netinfo(), xsh_ping(), xsh_ps(), xsh_sleep(), xsh_udpdump(), xsh_udpecho(), xsh_udpeserver(), xsh_uptime(), and yyerror().
 {
     va_list ap;
     int putc(did32, char);
     va_start(ap, fmt);
     _fdoprnt(fmt, ap, putc, dev);
     va_end(ap);
     return 0;
 }