XINU: system/create.c File Reference
create.c File Reference
新しいプロセスを作成する。
#include <xinu.h>
Macros
#define roundew(x) ((x + 3) & ~0x3)
4の倍数でスタックサイズを丸める。
Functions
pid32 create (void *procaddr, uint32 ssize, pri16 priority, char *name, uint32 nargs,...)
関数の実行を開始するプロセスを作成する。
local int newpid ()
新しいプロセスIDを取得するnewpid()の宣言
Detailed Description
新しいプロセスを作成する。
Definition in file create.c.
Macro Definition Documentation
roundew
#define roundew (x) ((x + 3) & ~0x3)
4の倍数でスタックサイズを丸める。
Parameters
[in] x スタックサイズ
Returns
下位2Bitを切り落とし、4の倍数で丸めたスタックサイズを返す。
Definition at line 16 of file create.c.
Referenced by create().
Function Documentation
create()
pid32 create (void * procaddr, uint32 ssize, pri16 priority, char * name, uint32 nargs, ...)
関数の実行を開始するプロセスを作成する。
Step1. 割り込みを禁止する。
Step2. スタックサイズがMINSTKを下回っていた場合、サイズをMINSTKまで引き上げ、丸めを行う。
Step3. 以下のいずれかを満たした場合は、割り込み許可状態に復元し、SYSERRを返す。
・スタックが確保できなかった場合
・全てのプロセスがFREE状態ではなかった場合（使用中だった場合）
・引数のプロセス優先度が1より小さかった場合
Step4. アクティブプロセス数を１増やす。 Step5. プロセステーブルエントリを以下の状態で初期化する。
・プロセス状態 = サスペンド
・プロセス優先度 = 引数で指定した優先度
・スタックアドレス = getstk()で取得したスタックアドレス（ プロセススタックの最上位にオーバフロー検知マーカを付与）
・スタックサイズ = 引数で指定されたスタックサイズ（MINSTK以上のサイズ）
・プロセス名 = 引数で指定した名前（15文字 + NULL終端）
・セマフォとメッセージ = 未使用状態
・デバイスディスクリプタ = XINU Shell用に0:STDIN(標準入力)、1:STDOUT(標準出力)、2:STDERR(標準エラー)を設定
Step6. 可変長引数と関数ポインタをスタックに積む。前提として、ARMはr0〜r3レジスタが引数渡しに使用される。
可変長引数の5個目〜N個目をスタックに積んだ後、関数ポインタをスタックに積む。
引数をレジスタ渡しするためにスタックにr4〜r11用の情報（=0）を積み、r3〜r0用の情報（引数次第で変化）を積む。
Step7. 関数のリターンアドレス（INITRET = userret()であり、kill()を呼び出す）をスタックに積む。
Step8. CPSR F bitを有効化し、スーパバイザモードに移行するためのビットマスクをスタックに積む。
このビットマスクは、コンテキストスイッチ中のリストア時に使用される。
Step9. 新しいスタックアドレスをプロセステーブルにセットする。
Step10. 割り込み許可状態に復元する。
Parameters
[in] procaddr 関数ポインタ（プロセスのエントリポイント）
[in] ssize スタックサイズ（Byte）
[in] priority プロセスの優先度（> 0）
[in] name プロセス名（デバッグ用）
[in] nargs 本引数より後にある引数の総数
[in] ... 可変長引数
Returns
成功時は作成したプロセスのID、以下の場合はSYSERRを返す。
・スタックが確保できなかった場合
・全てのプロセスがFREE状態ではなかった場合（使用中だった場合）
・引数のプロセス優先度が1より小さかった場合
Definition at line 55 of file create.c.
References CONSOLE, disable(), FALSE, getpid(), getstk(), INITRET, MINSTK, newpid(), NULLCH, PNMLEN, PR_SUSP, prcount, procent::prdesc, procent::prhasmsg, procent::prname, proctab, procent::prparent, procent::prprio, procent::prsem, procent::prstate, procent::prstkbase, procent::prstklen, procent::prstkptr, restore(), roundew, STACKMAGIC, and SYSERR.
Referenced by main(), net_init(), nulluser(), rdsinit(), shell(), and startup().
 {
     intmask mask;          /* interrupt mask        */
     pid32 pid;             /* stores new process id */
     struct procent *prptr; /* pointer to proc. table entry */
     int32 i;
     uint32 *a;     /* points to list of args    */
     uint32 *saddr; /* stack address     */
     mask = disable();
     if (ssize < MINSTK)
         ssize = MINSTK;
     ssize = (uint32)roundew(ssize);
     if (((saddr = (uint32 *)getstk(ssize)) ==
          (uint32 *)SYSERR) ||
         (pid = newpid()) == SYSERR || priority < 1)
     {
         restore(mask);
         return SYSERR;
     }
     prcount++;
     prptr = &proctab[pid];
     /* initialize process table entry for new process */
     prptr->prstate = PR_SUSP; /* initial state is suspended */
     prptr->prprio = priority;
     prptr->prstkbase = (char *)saddr;
     prptr->prstklen = ssize;
     prptr->prname[PNMLEN - 1] = NULLCH;
     for (i = 0; i < PNMLEN - 1 && (prptr->prname[i] = name[i]) != NULLCH; i++)
         ;
     prptr->prsem = -1;
     prptr->prparent = (pid32)getpid();
     prptr->prhasmsg = FALSE;
     /* set up initial device descriptors for the shell      */
     prptr->prdesc[0] = CONSOLE; /* stdin  is CONSOLE device */
     prptr->prdesc[1] = CONSOLE; /* stdout is CONSOLE device */
     prptr->prdesc[2] = CONSOLE; /* stderr is CONSOLE device */
     /* Initialize stack as if the process was called        */
     *saddr = STACKMAGIC;
     /* push arguments */
     a = (uint32 *)(&nargs + 1); /* start of args        */
     a += nargs - 1;             /* last argument        */
     for (; nargs > 4; nargs--)  /* machine dependent; copy args */
         *--saddr = *a--;        /* onto created process's stack */
     *--saddr = (long)procaddr;
     for (i = 11; i >= 4; i--)
         *--saddr = 0;
     for (i = 4; i > 0; i--)
     {
         if (i <= nargs)
             *--saddr = *a--;
         else
             *--saddr = 0;
     }
     *--saddr = (long)INITRET;    /* push on return address  */
     *--saddr = (long)0x00000053; /* CPSR F bit set,     */
     /* Supervisor mode      */
     prptr->prstkptr = (char *)saddr;
     restore(mask);
     return pid;
 }
newpid()
local pid32 newpid (void)
新しいプロセスIDを取得するnewpid()の宣言
新しいPID（FREEなPID）を取o得する。
newpid()内で、前回のnewpid()実行結果に１を加算したPIDを保持している。
このPIDから順番に、状態がFREEなプロセスをプロセステーブルから探す。
検索は全てのプロセスに対して行われ、探索対象のPIDがNPROC（プロセス総数）と一致した場合、
検索対象のPIDが0番に戻る（nextpid %= NPROC;部分）
Returns
成功時は新しいPID、全てのプロセスがFREE状態ではなかった場合SYSERRを返す。
Definition at line 131 of file create.c.
References NPROC, PR_FREE, proctab, procent::prstate, and SYSERR.
Referenced by create().
 {
     uint32 i;                 /* iterate through all processes*/
     static pid32 nextpid = 1; /* position in table to try or    */
     /*  one beyond end of table */
     /* check all NPROC slots */
     for (i = 0; i < NPROC; i++)
     {
         nextpid %= NPROC; /* wrap around to beginning */
         if (proctab[nextpid].prstate == PR_FREE)
         {
             return nextpid++;
         }
         else
         {
             nextpid++;
         }
     }
     return (pid32)SYSERR;
 }