XINU: system/ready.c File Reference
ready.c File Reference
プロセスをCPUサービスの対象にする。
#include <xinu.h>
Functions
status ready (pid32 pid)
プロセスをCPUサービスの対象にする。
Variables
qid16 readylist
READYリストのインデックス
Detailed Description
プロセスをCPUサービスの対象にする。
Definition in file ready.c.
Function Documentation
ready()
status ready (pid32 pid)
プロセスをCPUサービスの対象にする。
Step1. PIDが正常値かどうかを確認する。
Step2. プロセス情報を取得し、ステータスをREADY状態に移行する。
Step3. プロセスをREADYリストに挿入する。
Step4. 再スケジューリングを行う。
Parameters
[in] pid READY状態に遷移させるプロセスのID
Returns
プロセスがREADY状態となった場合はOK、引数が不正なPIDの場合はSYSERRを返す。
Definition at line 21 of file ready.c.
References insert(), isbadpid, OK, PR_READY, proctab, procent::prprio, procent::prstate, readylist, resched(), and SYSERR.
Referenced by resume(), semdelete(), semreset(), send(), signal(), signaln(), and wakeup().
 {
     register struct procent *prptr;
     if (isbadpid(pid))
     {
         return SYSERR;
     }
     /* Set process state to indicate ready and add to ready list */
     prptr = &proctab[pid];
     prptr->prstate = PR_READY;
     insert(pid, readylist, prptr->prprio);
     resched();
     return OK;
 }
Variable Documentation
readylist
qid16 readylist
READYリストのインデックス
READY状態のプロセスリストに対するグローバルID.
Definition at line 9 of file ready.c.
Referenced by ready(), resched(), and sysinit().