XINU: system/suspend.c File Reference
suspend.c File Reference
プロセスを一時停止し、休止状態（サスペンド）に遷移する。
#include <xinu.h>
Functions
syscall suspend (pid32 pid)
プロセスを一時停止し、休止状態（サスペンド）に遷移する。
Detailed Description
プロセスを一時停止し、休止状態（サスペンド）に遷移する。
Definition in file suspend.c.
Function Documentation
suspend()
syscall suspend (pid32 pid)
プロセスを一時停止し、休止状態（サスペンド）に遷移する。
Step1.割り込み禁止状態とし、割り込みマスクを保持する。
Step2. PIDが正常値か、NULLプロセスではないかを確認する。
NULLプロセスが休止状態になった場合、動かすプロセスがREADYリストから無くなる可能性がある。
Step3. サスペンド対象プロセス情報を取得する。
Step4. サスペンド可能なプロセスは、現在実行中かREADY状態のプロセスだけである。
READY状態の場合：READYリストからサスペンド対象プロセスを除外し、サスペンド状態とする。
実行中の場合：サスペンド状態とし、再スケジューリングを行う。
それ以外：割り込み状態（割り込みマスク）を元に戻し、エラー終了
Step5. 現在の優先度を取得する。 Step6. 割り込み状態（割り込みマスク）を元に戻す。
Parameters
[in] pid 休止状態に移行させるプロセスのID
Returns
一時休止（サスペンド）されたプロセスの優先度
Definition at line 23 of file suspend.c.
References disable(), getitem(), isbadpid, NULLPROC, PR_CURR, PR_READY, PR_SUSP, proctab, procent::prprio, procent::prstate, resched(), restore(), and SYSERR.
 {
     intmask mask;          /* Saved interrupt mask      */
     struct procent *prptr; /* Ptr to process's table entry  */
     pri16 prio;            /* Priority to return        */
     mask = disable();
     if (isbadpid(pid) || (pid == NULLPROC))
     {
         restore(mask);
         return SYSERR;
     }
     /* Only suspend a process that is current or ready */
     prptr = &proctab[pid];
     if ((prptr->prstate != PR_CURR) && (prptr->prstate != PR_READY))
     {
         restore(mask);
         return SYSERR;
     }
     if (prptr->prstate == PR_READY)
     {
         getitem(pid); /* Remove a ready process */
                       /*   from the ready list  */
         prptr->prstate = PR_SUSP;
     }
     else
     {
         prptr->prstate = PR_SUSP; /* Mark the current process   */
         resched();                /*   suspended and resched.   */
     }
     prio = prptr->prprio;
     restore(mask);
     return prio;
 }