XINU: device/lfs/lfflush.c File Reference
lfflush.c File Reference
#include <xinu.h>
Functions
status lfflush (struct lflcblk *lfptr)
Function Documentation
lfflush()
status lfflush (struct lflcblk * lfptr)
Definition at line 10 of file lfflush.c.
References FALSE, LF_AREA_DIR, Lf_data, lfdata::lf_dir, lfdata::lf_dirdirty, lfdata::lf_dskdev, LF_FREE, lflcblk::lfdbdirty, lflcblk::lfdblock, lflcblk::lfdnum, lflcblk::lfibdirty, lflcblk::lfiblock, lfibput(), lflcblk::lfinum, lflcblk::lfstate, OK, SYSERR, and write().
Referenced by lflclose(), lfsetup(), and lftruncate().
 {
     if (lfptr->lfstate == LF_FREE) {
         return SYSERR;
     }
     /* Write the directory if it has changed */
     if (Lf_data.lf_dirdirty) {
         write(Lf_data.lf_dskdev, (char *)&Lf_data.lf_dir,
                             LF_AREA_DIR);
         Lf_data.lf_dirdirty = FALSE;
     }
     /* Write data block if it has changed */
     if (lfptr->lfdbdirty) {
         write(Lf_data.lf_dskdev, lfptr->lfdblock, lfptr->lfdnum);
         lfptr->lfdbdirty = FALSE;
     }
     /* Write i-block if it has changed */
     if (lfptr->lfibdirty) {
         lfibput(Lf_data.lf_dskdev, lfptr->lfinum, &lfptr->lfiblock);
         lfptr->lfibdirty = FALSE;
     }
     return OK;
 }