XINU: system/xdone.c File Reference
xdone.c File Reference
最終プロセスの終了時、システム終了メッセージを表示する。
#include <xinu.h>
Functions
void xdone (void)
最終プロセスの終了時、システム終了メッセージを表示する。
Detailed Description
最終プロセスの終了時、システム終了メッセージを表示する。
Definition in file xdone.c.
Function Documentation
xdone()
void xdone (void)
最終プロセスの終了時、システム終了メッセージを表示する。
Definition at line 10 of file xdone.c.
References halt(), and kprintf().
Referenced by kill().
 {
     kprintf("\n\nAll user processes have completed.\n\n");
     halt(); /* Halt the processor       */
 }