XINU: include/tftp.h File Reference
tftp.h File Reference
Data Structures
struct tftp_msg
Macros
#define TFTP_ACK 4 /* Acknowledgement */
#define TFTP_DATA 3 /* Data Packet */
#define TFTP_ERROR 5 /* Error */
#define TFTP_ERROR_ACCESS_VIOLATION 2 /* Access violation. */
#define TFTP_ERROR_DISK_FULL 3 /* Disk full or allocation exceeded. */
#define TFTP_ERROR_FILE_EXISTS 6 /* File already exists. */
#define TFTP_ERROR_FILE_NOT_FOUND 1 /* File not found. */
#define TFTP_ERROR_ILLEGAL_OP 4 /* Illegal TFTP operation. */
#define TFTP_ERROR_NO_SUCH_USER 7 /* No such user. */
#define TFTP_ERROR_NOT_DEFINED 0 /* Not defined, see error message (if any). */
#define TFTP_ERROR_UNKNOWN_TRANSFER_ID 5 /* Unknown transfer ID. */
#define TFTP_MAXDATA 512 /* Max size of a data packet */
#define TFTP_MAXNAM 64 /* Max length of a file name */
#define TFTP_MAXRETRIES 3 /* Number of retranmissions */
#define TFTP_NON_VERBOSE 0 /* Do not use verbose output */
#define TFTP_PORT 69 /* UDP Port for TFTP */
#define TFTP_RRQ 1 /* Read Request */
#define TFTP_VERBOSE 1 /* Use verbose output */
#define TFTP_WAIT 5000 /* Time to wait for reply (ms) */
#define TFTP_WRQ 2 /* Write Request */
Functions
status tftpget (uint32 serverip, const char *filename, char *rcv_buf, uint32 rcv_buf_size, byte verbose)
status tftpget_mb (uint32 serverip, const char *filename, char **rcv_bufs, uint32 *rcv_buf_sizes, uint32 rcv_buf_count, byte verbose)
Macro Definition Documentation
TFTP_ACK
#define TFTP_ACK 4 /* Acknowledgement */
Definition at line 7 of file tftp.h.
Referenced by tftpget_mb().
TFTP_DATA
#define TFTP_DATA 3 /* Data Packet */
Definition at line 6 of file tftp.h.
Referenced by tftp_send1().
TFTP_ERROR
#define TFTP_ERROR 5 /* Error */
Definition at line 8 of file tftp.h.
Referenced by tftp_send1().
TFTP_ERROR_ACCESS_VIOLATION
#define TFTP_ERROR_ACCESS_VIOLATION 2 /* Access violation. */
Definition at line 13 of file tftp.h.
TFTP_ERROR_DISK_FULL
#define TFTP_ERROR_DISK_FULL 3 /* Disk full or allocation exceeded. */
Definition at line 14 of file tftp.h.
TFTP_ERROR_FILE_EXISTS
#define TFTP_ERROR_FILE_EXISTS 6 /* File already exists. */
Definition at line 17 of file tftp.h.
TFTP_ERROR_FILE_NOT_FOUND
#define TFTP_ERROR_FILE_NOT_FOUND 1 /* File not found. */
Definition at line 12 of file tftp.h.
TFTP_ERROR_ILLEGAL_OP
#define TFTP_ERROR_ILLEGAL_OP 4 /* Illegal TFTP operation. */
Definition at line 15 of file tftp.h.
TFTP_ERROR_NO_SUCH_USER
#define TFTP_ERROR_NO_SUCH_USER 7 /* No such user. */
Definition at line 18 of file tftp.h.
TFTP_ERROR_NOT_DEFINED
#define TFTP_ERROR_NOT_DEFINED 0 /* Not defined, see error message (if any). */
Definition at line 11 of file tftp.h.
TFTP_ERROR_UNKNOWN_TRANSFER_ID
#define TFTP_ERROR_UNKNOWN_TRANSFER_ID 5 /* Unknown transfer ID. */
Definition at line 16 of file tftp.h.
TFTP_MAXDATA
#define TFTP_MAXDATA 512 /* Max size of a data packet */
Definition at line 22 of file tftp.h.
TFTP_MAXNAM
#define TFTP_MAXNAM 64 /* Max length of a file name */
Definition at line 21 of file tftp.h.
Referenced by tftpget_mb().
TFTP_MAXRETRIES
#define TFTP_MAXRETRIES 3 /* Number of retranmissions */
Definition at line 23 of file tftp.h.
Referenced by tftpget_mb().
TFTP_NON_VERBOSE
#define TFTP_NON_VERBOSE 0 /* Do not use verbose output */
Definition at line 27 of file tftp.h.
TFTP_PORT
#define TFTP_PORT 69 /* UDP Port for TFTP */
Definition at line 20 of file tftp.h.
Referenced by tftpget_mb().
TFTP_RRQ
#define TFTP_RRQ 1 /* Read Request */
Definition at line 4 of file tftp.h.
Referenced by tftpget_mb().
TFTP_VERBOSE
#define TFTP_VERBOSE 1 /* Use verbose output */
Definition at line 28 of file tftp.h.
Referenced by tftpget_mb().
TFTP_WAIT
#define TFTP_WAIT 5000 /* Time to wait for reply (ms) */
Definition at line 24 of file tftp.h.
Referenced by tftp_send1().
TFTP_WRQ
#define TFTP_WRQ 2 /* Write Request */
Definition at line 5 of file tftp.h.
Function Documentation
tftpget()
status tftpget (uint32 serverip, const char * filename, char * rcv_buf, uint32 rcv_buf_size, byte verbose)
Definition at line 100 of file tftp.c.
References tftpget_mb().
 {
     return tftpget_mb(serverip, filename, &rcv_buf, &rcv_buf_size, 1,
                                  verbose);
 }
tftpget_mb()
status tftpget_mb (uint32 serverip, const char * filename, char ** rcv_bufs, uint32 * rcv_buf_sizes, uint32 rcv_buf_count, byte verbose)
Definition at line 118 of file tftp.c.
References getport(), htons, kprintf(), memset(), NULL, NULLCH, strncpy(), strnlen(), SYSERR, tftp_msg::tf_data, tftp_msg::tf_dblk, tftp_msg::tf_opcode, TFTP_ACK, TFTP_MAXNAM, TFTP_MAXRETRIES, TFTP_PORT, TFTP_RRQ, tftp_send1(), TFTP_VERBOSE, TIMEOUT, udp_register(), udp_release(), and udp_sendto().
Referenced by tftpget().
 {
     int32   nlen;           /* Length of file name      */
     uint16  localport;      /* Local UDP port to use    */
     uint16  remport=TFTP_PORT;  /* Remote UDP port to use   */
     int32   sock;           /* Socket descriptor to use */
     uint16  expected = 1;       /* Next data block we expect    */
     int32   i;          /* Loop index           */
     int32   n;          /* Num,h. octets in incoming msg*/
     int32   ret;            /* Return value         */
     int32   filesiz;        /* Total size of downloaded file*/
     struct  tftp_msg outmsg;    /* Outgoing message     */
     int32   mlen;           /* Length of outgoing mesage    */
     struct  tftp_msg inmsg;     /* Buffer for response message  */
     int32   dlen;           /* Size of data in a response   */
     char*   curr_buf;       /* Current buffer being used    */
     uint32  curr_buf_ind;       /* Index of current buffer  */
     uint32  curr_used;      /* Amount used in buffer    */
     /* Check args */
     if(filename == NULL || serverip == 0 || rcv_bufs == NULL ||
         rcv_buf_sizes == NULL || rcv_buf_count == 0) {
         kprintf("[TFTP GET] ERROR: Invalid argument\n");
         return SYSERR;
     }
     for(i = 0; i < rcv_buf_count; i++) {
         if(rcv_bufs[i] == NULL || rcv_buf_sizes[i] == 0) {
             kprintf("[TFTP GET] ERROR: Invalid argument\n");
             return SYSERR;
         }
     }
     nlen = strnlen(filename, TFTP_MAXNAM+1);
     if ( (nlen <= 0) || (nlen > TFTP_MAXNAM) ) {
         return SYSERR;
     }
     if(verbose & TFTP_VERBOSE) {
         kprintf("[TFTP Get] Server: %08X File: %s\n",
                          serverip, filename);
     }
     /* Generate a local port */
     localport = getport();
     if (verbose & TFTP_VERBOSE) {
         kprintf("[TFTP Get] Using local port %u\n",
                         0xffff & localport);
     }
     /* Register a UDP socket */
     sock = udp_register(serverip, 0, localport);
     if (sock == SYSERR) {
         kprintf("[TFTP Get] ERROR: udp_register failed\n");
         return SYSERR;
     }
     /* Clear the message buffer */
     memset((char*)&outmsg, NULLCH, sizeof(outmsg));
     /* Initialize the total file size to zero */
     filesiz = 0;
     curr_buf_ind = 0;
     curr_buf = (char*)rcv_bufs[curr_buf_ind];
     curr_used = 0;
     /* Form the first message and compute length (a Read Request)   */
     outmsg.tf_opcode = htons(TFTP_RRQ);
     strncpy(outmsg.tf_filemode, filename, nlen+1);
     /* Set mode to 'octet' */
     strncpy(outmsg.tf_filemode+nlen+1, "octet", sizeof("octet")+1);
     /* Length is 2 opcode octets, name length, "octet" length,  */
     /*      and two NULLs                   */
     mlen = nlen + strnlen("octet", 6) + 4;
     /* Repeatedly send the next request and get a response,     */
     /*  retransmitting a request up to TFTP_MAXRETRIES times    */
     while(1) {
         for (i=0; i < TFTP_MAXRETRIES; i++) {
         n = tftp_send1(sock, serverip, &remport, &outmsg, mlen,
                             &inmsg, expected);
         if (n > 0) {
             break;
         } else if (n == SYSERR) {
             kprintf("\n[TFTP Get] ERROR: TFTP Send fails\n");
             udp_release(sock);
             return SYSERR;
         } else if (n == TIMEOUT) {
             continue;
         }
         }
         if (i >= TFTP_MAXRETRIES) {
         kprintf("\n[TFTP Get] ERROR: Max retries %d exceeded\n",
                             TFTP_MAXRETRIES);
         udp_release(sock);
         return SYSERR;
         }
         if(verbose & TFTP_VERBOSE) {
         kprintf(".");
         }
         /* Compute size of data in the message */
         dlen = n - sizeof(inmsg.tf_opcode) - sizeof(inmsg.tf_dblk);
         /* Move the contents of this block into the file buffer */
         for (i=0; i<dlen; i++) {
         if (curr_used >= rcv_buf_sizes[curr_buf_ind]) {
             curr_buf_ind++;
             if(curr_buf_ind >= rcv_buf_count) {
                 udp_release(sock);
                 if(verbose & TFTP_VERBOSE) {
                     kprintf("\n");
                 }
                 return filesiz;
             }
             curr_buf = (char*)rcv_bufs[curr_buf_ind];
             curr_used = 0;
         }
         *curr_buf++ = inmsg.tf_data[i];
         curr_used++;
         filesiz++;
         }
         /* Form an ACK */
         outmsg.tf_opcode = htons(TFTP_ACK);
         outmsg.tf_ablk = htons(expected);
         mlen = sizeof(outmsg.tf_opcode) + sizeof(outmsg.tf_ablk);
         /* If this was the last packet, send final ACK */
         if (dlen < 512) {
         ret = udp_sendto(sock, serverip, remport,
                     (char *) &outmsg, mlen);
         udp_release(sock);
         if(verbose & TFTP_VERBOSE) {
             kprintf("\n");
         }
         if (ret == SYSERR) {
             kprintf("\n[TFTP GET] Error on final ack\n");
             return SYSERR;
         }
         return filesiz;
         }
         /* Move to next block and continue */
         expected++;
     }
 }