XINU: config/y.tab.c File Reference
y.tab.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stddef.h>
#include "lex.yy.c"
Data Structures
struct dev_ent
union yyalloc
Macros
#define CLOSE 269
#define COLON 260
#define CONFC "conf.c" /* Name of .c output */
#define CONFH "conf.h" /* Name of .h output */
#define CONFHREF "<conf.h>" /* How conf.h referenced */
#define CONTROL 273
#define CSR 264
#define DEFBRK 258
#define GETC 276
#define IDENT 263
#define IFBRK 259
#define INFILE "Configuration" /* Name of input file */
#define INIT 267
#define INTEGER 262
#define INTR 266
#define IRQ 265
#define IS 274
#define MAXNAME 16 /* Max length of names */
#define NDEVS 250 /* Max devices */
#define NIL (struct dev_ent *)0x00
#define NTYPES 250 /* Max device types */
#define OCTAL 261
#define ON 275
#define OPEN 268
#define PUTC 277
#define READ 270
#define SEEK 272
#define WRITE 271
#define YY_(Msgid) Msgid
#define YY_ATTRIBUTE(Spec) /* empty */
#define YY_ATTRIBUTE_PURE YY_ATTRIBUTE ((__pure__))
#define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YY_INITIAL_VALUE(Value) Value
#define YY_NULLPTR ((void*)0)
#define YY_REDUCE_PRINT(Rule)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YYABORT goto yyabortlab
#define YYACCEPT goto yyacceptlab
#define YYBACKUP(Token, Value)
#define YYBISON 1
#define YYBISON_VERSION "3.3.2"
#define yyclearin (yychar = YYEMPTY)
#define YYCOPY(Dst, Src, Count)
#define YYCOPY_NEEDED 1
#define YYDEBUG 0
#define YYDPRINTF(Args)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYERRCODE 256
#define yyerrok (yyerrstatus = 0)
#define YYERROR goto yyerrorlab
#define YYERROR_VERBOSE 0
#define YYFINAL 3
#define YYFREE free
#define YYINITDEPTH 200
#define YYLAST 39
#define YYMALLOC malloc
#define YYMAXDEPTH 10000
#define YYMAXUTOK 277
#define YYNNTS 20
#define YYNRULES 35
#define YYNSTATES 58
#define YYNTOKENS 23
#define YYPACT_NINF -14
#define yypact_value_is_default(Yystate) (!!((Yystate) == (-14)))
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
#define YYPULL 1
#define YYPURE 0
#define YYPUSH 0
#define YYRECOVERING() (!!yyerrstatus)
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YYSIZE_T size_t
#define YYSKELETON_NAME "yacc.c"
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYSTACK_BYTES(N)
#define YYSTACK_FREE YYFREE
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYSTYPE_IS_DECLARED 1
#define YYSTYPE_IS_TRIVIAL 1
#define YYTABLE_NINF -1
#define yytable_value_is_error(Yytable_value) 0
#define YYTERROR 1
#define YYTOKENTYPE
#define YYTRANSLATE(YYX) ((unsigned) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYUNDEFTOK 2
#define YYUSE(E) ((void) (E))
Typedefs
typedef int YYSTYPE
typedef short yytype_int16
typedef signed char yytype_int8
typedef unsigned short yytype_uint16
typedef unsigned char yytype_uint8
Enumerations
enum yytokentype {
DEFBRK = 258, IFBRK = 259, COLON = 260, OCTAL = 261,
INTEGER = 262, IDENT = 263, CSR = 264, IRQ = 265,
INTR = 266, INIT = 267, OPEN = 268, CLOSE = 269,
READ = 270, WRITE = 271, SEEK = 272, CONTROL = 273,
IS = 274, ON = 275, GETC = 276, PUTC = 277
}
Functions
void addattr (int, int)
int addton (char *)
int config_atoi (char *, int)
void devisid (char *)
void devonid (char *)
void free (void *)
void getattrid (char *)
int main (int argc, char **argv)
void * malloc (YYSIZE_T)
void newdev (char *)
int newtype (char *)
static void yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep)
void yyerror (char *)
int yylex (void)
int yyparse (void)
Variables
int brkcount = 0
FILE * confc
FILE * confh
struct dev_ent devs [NDEVS]
char * devstab []
char * doing = "device type declarations"
struct dev_ent dtypes [NTYPES]
int linectr = 1
int ndevs = 0
int ntypes = 0
char saveattrid [MAXNAME]
int yychar
static const yytype_int8 yycheck []
static const yytype_uint8 yydefact []
static const yytype_int8 yydefgoto []
int yyleng
YYSTYPE yylval
int yynerrs
static const yytype_int8 yypact []
static const yytype_int8 yypgoto []
static const yytype_uint8 yyr1 []
static const yytype_uint8 yyr2 []
static const yytype_uint8 yystos []
static const yytype_uint8 yytable []
char * yytext
static const yytype_uint8 yytranslate []
Macro Definition Documentation
CLOSE
#define CLOSE 269
Definition at line 249 of file y.tab.c.
Referenced by addattr(), and yyparse().
COLON
#define COLON 260
Definition at line 240 of file y.tab.c.
CONFC
#define CONFC "conf.c" /* Name of .c output */
Definition at line 91 of file y.tab.c.
Referenced by main().
CONFH
#define CONFH "conf.h" /* Name of .h output */
Definition at line 92 of file y.tab.c.
Referenced by main().
CONFHREF
#define CONFHREF "<conf.h>" /* How conf.h referenced */
Definition at line 93 of file y.tab.c.
CONTROL
#define CONTROL 273
Definition at line 253 of file y.tab.c.
Referenced by addattr(), and yyparse().
CSR
#define CSR 264
Definition at line 244 of file y.tab.c.
Referenced by addattr(), and yyparse().
DEFBRK
#define DEFBRK 258
Definition at line 238 of file y.tab.c.
GETC
#define GETC 276
Definition at line 256 of file y.tab.c.
Referenced by addattr(), and yyparse().
IDENT
#define IDENT 263
Definition at line 243 of file y.tab.c.
IFBRK
#define IFBRK 259
Definition at line 239 of file y.tab.c.
INFILE
#define INFILE "Configuration" /* Name of input file */
Definition at line 94 of file y.tab.c.
Referenced by main().
INIT
#define INIT 267
Definition at line 247 of file y.tab.c.
Referenced by addattr(), and yyparse().
INTEGER
#define INTEGER 262
Definition at line 242 of file y.tab.c.
INTR
#define INTR 266
Definition at line 246 of file y.tab.c.
Referenced by addattr(), and yyparse().
IRQ
#define IRQ 265
Definition at line 245 of file y.tab.c.
Referenced by addattr(), and yyparse().
IS
#define IS 274
Definition at line 254 of file y.tab.c.
MAXNAME
#define MAXNAME 16 /* Max length of names */
Definition at line 95 of file y.tab.c.
Referenced by addton(), devisid(), devonid(), getattrid(), newdev(), and newtype().
NDEVS
#define NDEVS 250 /* Max devices */
Definition at line 97 of file y.tab.c.
Referenced by newdev().
NIL
#define NIL (struct dev_ent *)0x00
Definition at line 89 of file y.tab.c.
NTYPES
#define NTYPES 250 /* Max device types */
Definition at line 98 of file y.tab.c.
Referenced by newtype().
OCTAL
#define OCTAL 261
Definition at line 241 of file y.tab.c.
ON
#define ON 275
Definition at line 255 of file y.tab.c.
OPEN
#define OPEN 268
Definition at line 248 of file y.tab.c.
Referenced by addattr(), and yyparse().
PUTC
#define PUTC 277
Definition at line 257 of file y.tab.c.
Referenced by addattr(), and yyparse().
READ
#define READ 270
Definition at line 250 of file y.tab.c.
Referenced by addattr(), and yyparse().
SEEK
#define SEEK 272
Definition at line 252 of file y.tab.c.
Referenced by addattr(), and yyparse().
WRITE
#define WRITE 271
Definition at line 251 of file y.tab.c.
Referenced by addattr(), and yyparse().
YY_
#define YY_ (Msgid) Msgid
Definition at line 326 of file y.tab.c.
Referenced by yyparse().
YY_ATTRIBUTE
#define YY_ATTRIBUTE (Spec) /* empty */
Definition at line 336 of file y.tab.c.
YY_ATTRIBUTE_PURE
#define YY_ATTRIBUTE_PURE YY_ATTRIBUTE ((__pure__))
Definition at line 341 of file y.tab.c.
YY_ATTRIBUTE_UNUSED
#define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
Definition at line 345 of file y.tab.c.
YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
Definition at line 367 of file y.tab.c.
Referenced by yydestruct(), and yyparse().
YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
Definition at line 368 of file y.tab.c.
Referenced by yydestruct(), and yyparse().
YY_INITIAL_VALUE
#define YY_INITIAL_VALUE (Value) Value
Definition at line 364 of file y.tab.c.
YY_NULLPTR
#define YY_NULLPTR ((void*)0)
Definition at line 189 of file y.tab.c.
YY_REDUCE_PRINT
#define YY_REDUCE_PRINT (Rule)
Definition at line 855 of file y.tab.c.
Referenced by yyparse().
YY_STACK_PRINT
#define YY_STACK_PRINT (Bottom, Top)
Definition at line 854 of file y.tab.c.
Referenced by yyparse().
YY_SYMBOL_PRINT
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Definition at line 853 of file y.tab.c.
Referenced by yydestruct(), and yyparse().
YYABORT
#define YYABORT goto yyabortlab
Definition at line 700 of file y.tab.c.
Referenced by yyparse().
YYACCEPT
#define YYACCEPT goto yyacceptlab
Definition at line 699 of file y.tab.c.
Referenced by yyparse().
YYBACKUP
#define YYBACKUP (Token, Value)
Value:
do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)
Definition at line 706 of file y.tab.c.
YYBISON
#define YYBISON 1
Definition at line 48 of file y.tab.c.
YYBISON_VERSION
#define YYBISON_VERSION "3.3.2"
Definition at line 51 of file y.tab.c.
yyclearin
#define yyclearin (yychar = YYEMPTY)
Definition at line 695 of file y.tab.c.
YYCOPY
#define YYCOPY (Dst, Src, Count)
Value:
do                                        \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
Definition at line 491 of file y.tab.c.
YYCOPY_NEEDED
#define YYCOPY_NEEDED 1
Definition at line 463 of file y.tab.c.
YYDEBUG
#define YYDEBUG 0
Definition at line 204 of file y.tab.c.
YYDPRINTF
#define YYDPRINTF (Args)
Definition at line 852 of file y.tab.c.
Referenced by yyparse().
YYEMPTY
#define YYEMPTY (-2)
Definition at line 696 of file y.tab.c.
Referenced by yyparse().
YYEOF
#define YYEOF 0
Definition at line 697 of file y.tab.c.
Referenced by yyparse().
YYERRCODE
#define YYERRCODE 256
Definition at line 725 of file y.tab.c.
yyerrok
#define yyerrok (yyerrstatus = 0)
Definition at line 694 of file y.tab.c.
YYERROR
#define YYERROR goto yyerrorlab
Definition at line 701 of file y.tab.c.
Referenced by yyparse().
YYERROR_VERBOSE
#define YYERROR_VERBOSE 0
Definition at line 198 of file y.tab.c.
YYFINAL
#define YYFINAL 3
Definition at line 504 of file y.tab.c.
Referenced by yyparse().
YYFREE
#define YYFREE free
Definition at line 434 of file y.tab.c.
YYINITDEPTH
#define YYINITDEPTH 200
Definition at line 861 of file y.tab.c.
Referenced by yyparse().
YYLAST
#define YYLAST 39
Definition at line 506 of file y.tab.c.
Referenced by yyparse().
YYMALLOC
#define YYMALLOC malloc
Definition at line 428 of file y.tab.c.
YYMAXDEPTH
#define YYMAXDEPTH 10000
Definition at line 872 of file y.tab.c.
Referenced by yyparse().
YYMAXUTOK
#define YYMAXUTOK 277
Definition at line 518 of file y.tab.c.
YYNNTS
#define YYNNTS 20
Definition at line 511 of file y.tab.c.
YYNRULES
#define YYNRULES 35
Definition at line 513 of file y.tab.c.
YYNSTATES
#define YYNSTATES 58
Definition at line 515 of file y.tab.c.
YYNTOKENS
#define YYNTOKENS 23
Definition at line 509 of file y.tab.c.
Referenced by yyparse().
YYPACT_NINF
#define YYPACT_NINF -14
Definition at line 595 of file y.tab.c.
yypact_value_is_default
#define yypact_value_is_default (Yystate) (!!((Yystate) == (-14)))
Definition at line 597 of file y.tab.c.
Referenced by yyparse().
YYPOPSTACK
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
Referenced by yyparse().
YYPULL
#define YYPULL 1
Definition at line 63 of file y.tab.c.
YYPURE
#define YYPURE 0
Definition at line 57 of file y.tab.c.
YYPUSH
#define YYPUSH 0
Definition at line 60 of file y.tab.c.
YYRECOVERING
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 704 of file y.tab.c.
YYSIZE_MAXIMUM
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
Definition at line 316 of file y.tab.c.
YYSIZE_T
#define YYSIZE_T size_t
Definition at line 310 of file y.tab.c.
Referenced by yyparse().
YYSKELETON_NAME
#define YYSKELETON_NAME "yacc.c"
Definition at line 54 of file y.tab.c.
YYSTACK_ALLOC
#define YYSTACK_ALLOC YYMALLOC
Definition at line 414 of file y.tab.c.
Referenced by yyparse().
YYSTACK_ALLOC_MAXIMUM
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
Definition at line 417 of file y.tab.c.
YYSTACK_BYTES
#define YYSTACK_BYTES (N)
Value:
((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
Definition at line 459 of file y.tab.c.
Referenced by yyparse().
YYSTACK_FREE
#define YYSTACK_FREE YYFREE
Definition at line 415 of file y.tab.c.
Referenced by yyparse().
YYSTACK_GAP_MAXIMUM
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
Definition at line 455 of file y.tab.c.
YYSTACK_RELOCATE
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
do                                                                  \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (0)
Definition at line 470 of file y.tab.c.
Referenced by yyparse().
YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
Definition at line 263 of file y.tab.c.
YYSTYPE_IS_TRIVIAL
#define YYSTYPE_IS_TRIVIAL 1
Definition at line 262 of file y.tab.c.
YYTABLE_NINF
#define YYTABLE_NINF -1
Definition at line 600 of file y.tab.c.
yytable_value_is_error
#define yytable_value_is_error (Yytable_value) 0
Definition at line 602 of file y.tab.c.
Referenced by yyparse().
YYTERROR
#define YYTERROR 1
Definition at line 724 of file y.tab.c.
Referenced by yyparse().
YYTOKENTYPE
#define YYTOKENTYPE
Definition at line 212 of file y.tab.c.
YYTRANSLATE
#define YYTRANSLATE (YYX) ((unsigned) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Definition at line 522 of file y.tab.c.
Referenced by yyparse().
YYUNDEFTOK
#define YYUNDEFTOK 2
Definition at line 517 of file y.tab.c.
YYUSE
#define YYUSE (E) ((void) (E))
Definition at line 350 of file y.tab.c.
Referenced by yydestruct().
Typedef Documentation
YYSTYPE
typedef int YYSTYPE
Definition at line 261 of file y.tab.c.
yytype_int16
typedef short yytype_int16
Definition at line 300 of file y.tab.c.
yytype_int8
typedef signed char yytype_int8
Definition at line 288 of file y.tab.c.
yytype_uint16
typedef unsigned short yytype_uint16
Definition at line 294 of file y.tab.c.
yytype_uint8
typedef unsigned char yytype_uint8
Definition at line 282 of file y.tab.c.
Enumeration Type Documentation
yytokentype
enum yytokentype
Enumerator
DEFBRK
IFBRK
COLON
OCTAL
INTEGER
IDENT
CSR
IRQ
INTR
INIT
OPEN
CLOSE
READ
WRITE
SEEK
CONTROL
IS
ON
GETC
PUTC
Definition at line 213 of file y.tab.c.
   {
     DEFBRK = 258,
     IFBRK = 259,
     COLON = 260,
     OCTAL = 261,
     INTEGER = 262,
     IDENT = 263,
     CSR = 264,
     IRQ = 265,
     INTR = 266,
     INIT = 267,
     OPEN = 268,
     CLOSE = 269,
     READ = 270,
     WRITE = 271,
     SEEK = 272,
     CONTROL = 273,
     IS = 274,
     ON = 275,
     GETC = 276,
     PUTC = 277
   };
Function Documentation
addattr()
void addattr (int tok, int val)
Definition at line 1958 of file y.tab.c.
References brkcount, dev_ent::close, CLOSE, dev_ent::control, CONTROL, dev_ent::csr, CSR, devs, dtypes, fprintf(), dev_ent::getc, GETC, dev_ent::init, INIT, dev_ent::intr, INTR, dev_ent::irq, IRQ, ndevs, ntypes, dev_ent::open, OPEN, dev_ent::putc, PUTC, dev_ent::read, READ, saveattrid, dev_ent::seek, SEEK, stderr, strcpy(), dev_ent::write, and WRITE.
Referenced by yyparse().
{
     struct dev_ent *s;
     char *c;
     if (brkcount == 0) {
         /* Doing types */
         s = &dtypes[ntypes-1];
     } else {
         /* Doing devices */
         s = &devs[ndevs-1];
     }
     switch (tok) {
     case CSR:   s->csr = val;           break;
     case IRQ:   s->irq = val;           break;
     case INTR:  strcpy(s->intr, saveattrid);    break;
     case READ:  strcpy(s->read, saveattrid);    break;
     case WRITE: strcpy(s->write,saveattrid);    break;
     case GETC:  strcpy(s->getc, saveattrid);    break;
     case PUTC:  strcpy(s->putc, saveattrid);    break;
     case OPEN:  strcpy(s->open, saveattrid);    break;
     case CLOSE: strcpy(s->close,saveattrid);    break;
     case INIT:  strcpy(s->init, saveattrid);    break;
     case SEEK:  strcpy(s->seek, saveattrid);    break;
     case CONTROL:   strcpy(s->control,saveattrid);  break;
     default:    fprintf(stderr, "Internal error 1\n");
     }
 }
addton()
int addton (char * tonid)
Definition at line 1994 of file y.tab.c.
References dtypes, exit(), fprintf(), dev_ent::ison, linectr, MAXNAME, ntypes, stderr, strcpy(), and strlen().
Referenced by yyparse().
{
     int currtype;       /* The current type     */
     if (strlen(tonid) >= MAXNAME) {
         fprintf(stderr,"string %s is too long on line %d\n",
                 tonid, linectr);
         exit(1);
     }
     currtype = ntypes - 1;
     strcpy(dtypes[currtype].ison, tonid);
     return currtype;
 }
config_atoi()
int config_atoi (char * p, int len)
Definition at line 2016 of file y.tab.c.
References isdigit, and isupper.
Referenced by yyparse().
{
     int base, rv;
     if (*p == '0')
     {
         ++p;
         --len;
         if (*p == 'x' || *p == 'X')
         {
             ++p; --len; /* skip 'x' */
             base = 16;
         }
         else
         {
             base = 8;
         }
     }
     else
     {
         base = 10;
     }
     rv = 0;
     for (; len > 0; ++p, --len)
     {
         rv *= base;
         if      (isdigit(*p)) { rv += *p - '0'; }
         else if (isupper(*p)) { rv += *p - 'A' + 10; }
         else                  { rv += *p - 'a' + 10; }
     }
     return rv;
 }
devisid()
void devisid (char * tname)
Definition at line 2056 of file y.tab.c.
References devs, dtypes, exit(), fprintf(), linectr, MAXNAME, ndevs, ntypes, stderr, strcmp(), strcpy(), and strlen().
Referenced by yyparse().
{
     int currdev;        /* The current device       */
     int i;
     if (strlen(tname) >= MAXNAME) {
         fprintf(stderr,"string %s is too long on line %d\n",
                 tname, linectr);
         exit(1);
     }
     /* Verify the type exists */
     for (i=0; i<ntypes; i++) {
         if (strcmp(tname, dtypes[i].tname) == 0) {
             break;
         }
     }
     if (i >= ntypes) {
         fprintf(stderr, "Illegal type name %s on line %d\n",
                 tname, linectr);
         exit(1);
     }
     currdev = ndevs - 1;
     strcpy(devs[currdev].tname, tname);
     return;
 }
devonid()
void devonid (char * onname)
Definition at line 2091 of file y.tab.c.
References devs, dtypes, exit(), fprintf(), dev_ent::ison, linectr, MAXNAME, dev_ent::minor, dev_ent::name, ndevs, ntypes, stderr, strcmp(), strcpy(), strlen(), and dev_ent::tname.
Referenced by yyparse().
{
     int currdev;        /* The current device       */
     int i;
     struct  dev_ent *dptr;      /* Pointer to current device    */
     struct  dev_ent *tptr;      /* Pointer to a type        */
     char    tmp[MAXNAME];       /* Holds the device name during */
                     /*   copy           */
     if (strlen(onname) >= MAXNAME) {
         fprintf(stderr,"string %s is too long on line %d\n",
                 onname, linectr);
         exit(1);
     }
     if (ndevs <=0) {
         fprintf(stderr,"Internal error 3\n");
         exit(1);
     }
     currdev = ndevs - 1;
     dptr = &devs[currdev];
     strcpy(dptr->ison, onname);
     /* Lookup the device type */
     for (i=0; i<ntypes; i++) {
         tptr = &dtypes[i];
         if ( (strcmp(dptr->tname,tptr->tname) == 0 ) &&
              (strcmp(dptr->ison, tptr->ison)  == 0 )  ){
             /* The specified type matches the ith entry, so */
             /*  set all attributes equal to the ones in the */
             /*  type definition.                */
             strcpy(tmp, dptr->name);
             bcopy (tptr, dptr, sizeof(struct dev_ent));
             /* Increment the minor device number for the    */
             /*  next time the type is used          */
             tptr->minor++;
             strcpy(dptr->name, tmp);
             return;
         }
     }
     fprintf(stderr, "Ileagal device specification on line %d\n", linectr);
     exit(1);
 }
free()
void free (void *)
getattrid()
void getattrid (char * str)
Definition at line 2145 of file y.tab.c.
References exit(), fprintf(), linectr, MAXNAME, saveattrid, stderr, strcpy(), and strlen().
Referenced by yyparse().
{
     if (strlen(str) >= MAXNAME) {
         fprintf(stderr,"atribute string %s is too long on line %d\n",
                 str, linectr);
         exit(1);
     }
     strcpy(saveattrid, str);
     return;
 }
main()
int main (int argc, char ** argv)
Definition at line 1753 of file y.tab.c.
References brkcount, dev_ent::close, CONFC, confc, CONFH, confh, dev_ent::control, dev_ent::csr, devs, devstab, dtypes, exit(), fprintf(), dev_ent::getc, INFILE, dev_ent::init, input(), dev_ent::intr, dev_ent::irq, dev_ent::ison, dev_ent::minor, dev_ent::name, ndevs, ntypes, NULL, dev_ent::open, printf(), dev_ent::putc, dev_ent::read, dev_ent::seek, stderr, stdin, strncmp(), dev_ent::tname, dev_ent::write, and yyparse().
{
     int n, i, j, l, fcount;
     struct dev_ent *s;
     int   verbose = 0;
     char *p;
     int  c;
     if ( argc > 1 && (strncmp("-v", argv[1], 2) == 0) ) {
         argc--;
         argv++;
         verbose++;
     }
     if ( argc > 4 ) {
         fprintf(stderr, "use: config [-v] [input_file] [conf.c] [conf.h]\n");
         exit(1);
     }
     if (verbose) { printf("Opening input file...\n"); }
     if (argc >= 2) {
         if (freopen(argv[1], "r", stdin) == NULL) {
             fprintf(stderr, "Can't open %s\n", argv[1]);
             exit(1);
         }
     }
     else {  /* try to open Configuration file */
         if (freopen(INFILE, "r", stdin) == NULL) {
             fprintf(stderr, "Can't open %s\n", INFILE);
             exit(1);
         }
     }
     /****************************************************************/
     /*                              */
     /*      Parse the Configuration file            */
     /*                              */
     /****************************************************************/
     if (verbose) { printf("Parsing configuration specs...\n"); }
     if ( (n = yyparse()) != 0 ) { exit(n); }
     /* Open conf.h and conf.c for writing */
     if (verbose) { printf("Opening output files...\n"); }
     if (argc >= 3) {
         if ( (confc = fopen(argv[2],"w") ) == NULL) {
             fprintf(stderr, "Can't write on %s\n", argv[2]);
             exit(1);
         }
     }
     else {  /* try to open conf.c file */
         if ( (confc = fopen(CONFC,"w") ) == NULL) {
             fprintf(stderr, "Can't write on %s\n", CONFC);
             exit(1);
         }
     }
     if (argc >= 4) {
         if ( (confh = fopen(argv[3],"w") ) == NULL) {
             fprintf(stderr, "Can't write on %s\n", argv[3]);
             exit(1);
         }
     }
     else {  /* try to open conf.h file */
         if ( (confh = fopen(CONFH,"w") ) == NULL) {
             fprintf(stderr, "Can't write on %s\n", CONFH);
             exit(1);
         }
     }
     /****************************************************************/
     /*                              */
     /*          produce conf.h              */
     /*                              */
     /****************************************************************/
     fprintf(confh, "/* conf.h (GENERATED FILE; DO NOT EDIT) */\n\n");
     if (verbose) { printf("Writing output...\n"); }
     fprintf(confh, "/* Device switch table declarations */\n\n");
     for (i = 0; (p = devstab[i]) != NULL; i++) {
         fprintf(confh, "%s\n", p);
     }
     fprintf(confh, "\n");
     /* write device declarations and definitions */
     fprintf(confh, "/* Device name definitions */\n\n");
     for (i = 0; i<ndevs; i++) {
         s = &devs[i];
         fprintf(confh, "#define %-20s%2d\t/* type %-8s */\n",
             s->name, i, s->tname);
     }
     fprintf(confh, "\n");
     /* write count of device types */
     fprintf(confh, "/* Control block sizes */\n\n");
     for (i = 0; i < ntypes;  i++) {
         s = &dtypes[i];
         if (s->minor > 0) {
             fprintf(confh, "#define\tN%s\t%d\n",
                 s->tname, s->minor);
         }
     }
     fprintf(confh, "\n");
     if (ndevs > 0) { fprintf(confh, "#define NDEVS %d\n", ndevs); }
     /* Copy definitions to output */
     if (brkcount >= 4 && verbose) {
         printf("Copying definitions to %s...\n", CONFH);
     }
     if (brkcount >= 2) {
         while ( (c = input()) > 0) {    /* lex input function   */
             putc(c, confh);
         }
     }
     fclose(confh);
     /****************************************************************/
     /*                              */
     /*          produce conf.c              */
     /*                              */
     /****************************************************************/
     fprintf(confc, "/* conf.c (GENERATED FILE; DO NOT EDIT) */\n\n");
     fprintf(confc, "#include <xinu.h>\n\n");
     fprintf(confc, "\n");
     fprintf(confc, "extern\tdevcall\tioerr(void);\n");
     fprintf(confc, "extern\tdevcall\tionull(void);\n\n");
     /* produce devtab (giant I/O switch table) */
     fprintf(confc, "/* Device independent I/O switch */\n\n");
     if (ndevs > 0)
     {
         fprintf(confc, "struct  dentry  devtab[NDEVS] =\n{\n");
         fprintf(confc, "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n\n",
             "/**",
             " * Format of entries is:",
             " * dev-number, minor-number, dev-name,",
             " * init, open, close,",
             " * read, write, seek,",
             " * getc, putc, control,",
             " * dev-csr-address, intr-handler, irq",
             " */");
     }
     for (i=0; i<ndevs; i++) {
         s = &devs[i];
         fprintf(confc, "/* %s is %s */\n", s->name, s->tname);
         fprintf(confc, "\t{ %d, %d, \"%s\",\n", i, s->minor, s->name);
         fprintf(confc, "\t  (void *)%s, (void *)%s, (void *)%s,\n",
             s->init, s->open, s->close);
         fprintf(confc, "\t  (void *)%s, (void *)%s, (void *)%s,\n",
             s->read, s->write, s->seek);
         fprintf(confc, "\t  (void *)%s, (void *)%s, (void *)%s,\n",
             s->getc, s->putc, s->control);
         fprintf(confc, "\t  (void *)0x%x, (void *)%s, %d }",
             s->csr, s->intr, s->irq);
         if (i< ndevs-1) {
             fprintf(confc, ",\n\n");
         } else {
             fprintf(confc, "\n};");
         }
     }
     /* we must guarantee conf.c written later than conf.h for make */
     fprintf(confc, "\n");
     fclose(confc);
     /* finish up and write report for user if requested */
     if (verbose) {
         printf("Configuration complete. Number of devs=%d:\n", ndevs);
         for (i=0; i<ndevs; i++) {
             s = &devs[i];
             printf("Device %s (on %s)\n", s->name, s->ison);
             printf("    csr=0x%04x, irq=0x%04x, minor=%d\n",
                 s->csr, s->irq, s->minor);
         }
     }
 }
malloc()
void* malloc (YYSIZE_T)
newdev()
void newdev (char * name)
Definition at line 2163 of file y.tab.c.
References bzero(), devs, exit(), fprintf(), linectr, MAXNAME, NDEVS, ndevs, stderr, strcmp(), strcpy(), and strlen().
Referenced by nammap(), namopen(), and yyparse().
{
     struct  dev_ent *dptr;      /* Ptr. to an entry in devs */
     int i;
     if (ndevs >= NDEVS) {
         fprintf(stderr,"Too many devices on line %d", linectr);
         exit(1);
     }
     if (strlen(name) >= MAXNAME) {
         fprintf(stderr,"Device name %s is too long on line %d\n",
                 name, linectr);
         exit(1);
     }
     /* Verify that the device name is unique */
     for (i=0; i<ndevs; i++) {
         if (strcmp(name, devs[i].name) == 0) {
             fprintf(stderr, "Duplicate device name %s on line %d\n",
                 name, linectr);
             exit(1);
         }
     }
     dptr = &devs[ndevs];
     /* Initialize fields in the entry */
     bzero((void *)dptr, sizeof(struct dev_ent));
     strcpy(dptr->name,   name);
     ndevs++;
     return;
 }
newtype()
int newtype (char * name)
Definition at line 2205 of file y.tab.c.
References bzero(), dtypes, exit(), fprintf(), linectr, MAXNAME, NTYPES, ntypes, stderr, strcmp(), strcpy(), strlen(), strncpy(), and dev_ent::tname.
Referenced by yyparse().
{
     struct  dev_ent *dptr;      /* Ptr. to an entry in dtypes   */
     int i;          /* Index into the type table    */
     if (ntypes >= NTYPES) {
         fprintf(stderr,"Too many types on line %d", linectr);
         exit(1);
     }
     if (strlen(name) >= MAXNAME) {
         fprintf(stderr,"Type name %s is too long on line %d\n",
                 name, linectr);
         exit(1);
     }
     /* Verify that the type name is unique */
     for (i=0; i<ntypes; i++) {
         if (strcmp(name, dtypes[i].tname) == 0) {
             fprintf(stderr, "Duplicate type name %s on line %d\n",
                 name, linectr);
             exit(1);
         }
     }
     dptr = &dtypes[ntypes];
     /* Initialize fields in the entry */
     bzero((void *)dptr, sizeof(struct dev_ent));
     strcpy(dptr->tname,  name);
     strncpy(dptr->intr, "ioerr", 5);
     strncpy(dptr->init, "ioerr", 5);
     strncpy(dptr->open, "ioerr", 5);
     strncpy(dptr->close,    "ioerr", 5);
     strncpy(dptr->read, "ioerr", 5);
     strncpy(dptr->write,    "ioerr", 5);
     strncpy(dptr->control,  "ioerr", 5);
     strncpy(dptr->seek, "ioerr", 5);
     strncpy(dptr->getc, "ioerr", 5);
     strncpy(dptr->putc, "ioerr", 5);
     return ntypes++;
 }
yydestruct()
static void yydestruct (const char * yymsg, int yytype, YYSTYPE * yyvaluep) static
Definition at line 1108 of file y.tab.c.
References YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_SYMBOL_PRINT, and YYUSE.
Referenced by yyparse().
 {
   YYUSE (yyvaluep);
   if (!yymsg)
     yymsg = "Deleting";
   YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   YYUSE (yytype);
   YY_IGNORE_MAYBE_UNINITIALIZED_END
 }
yyerror()
void yyerror (char * s)
Definition at line 2257 of file y.tab.c.
References doing, fprintf(), linectr, and stderr.
Referenced by yyparse().
                       {
     fprintf(stderr, "Syntax error in %s on line %d\n", doing, linectr);
 }
yylex()
int yylex (void)
Referenced by yyparse().
yyparse()
int yyparse (void)
Definition at line 1137 of file y.tab.c.
References addattr(), addton(), CLOSE, config_atoi(), CONTROL, CSR, devisid(), devonid(), doing, getattrid(), GETC, INIT, INTR, IRQ, newdev(), newtype(), OPEN, PUTC, READ, SEEK, stderr, WRITE, YY_, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yychar, yycheck, yydefact, yydefgoto, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror(), YYERROR, YYFINAL, YYINITDEPTH, YYLAST, yyleng, yylex(), yylval, YYMAXDEPTH, yynerrs, YYNTOKENS, yypact, yypact_value_is_default, yypgoto, YYPOPSTACK, yyr1, yyr2, YYSIZE_T, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yystos, yytable, yytable_value_is_error, YYTERROR, yytext, YYTRANSLATE, and yyalloc::yyvs_alloc.
Referenced by main().
 {
     int yystate;
     /* Number of tokens to shift before error messages enabled.  */
     int yyerrstatus;
     /* The stacks and their tools:
        'yyss': related to states.
        'yyvs': related to semantic values.
        Refer to the stacks through separate pointers, to allow yyoverflow
        to reallocate them elsewhere.  */
     /* The state stack.  */
     yytype_int16 yyssa[YYINITDEPTH];
     yytype_int16 *yyss;
     yytype_int16 *yyssp;
     /* The semantic value stack.  */
     YYSTYPE yyvsa[YYINITDEPTH];
     YYSTYPE *yyvs;
     YYSTYPE *yyvsp;
     YYSIZE_T yystacksize;
   int yyn;
   int yyresult;
   /* Lookahead token as an internal (translated) token number.  */
   int yytoken = 0;
   /* The variables used to return semantic value and location from the
      action routines.  */
   YYSTYPE yyval;
 #if YYERROR_VERBOSE
   /* Buffer for error messages, and its allocated size.  */
   char yymsgbuf[128];
   char *yymsg = yymsgbuf;
   YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
 #endif
 #define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))
   /* The number of symbols on the RHS of the reduced rule.
      Keep to zero when no symbol should be popped.  */
   int yylen = 0;
   yyssp = yyss = yyssa;
   yyvsp = yyvs = yyvsa;
   yystacksize = YYINITDEPTH;
   YYDPRINTF ((stderr, "Starting parse\n"));
   yystate = 0;
   yyerrstatus = 0;
   yynerrs = 0;
   yychar = YYEMPTY; /* Cause a token to be read.  */
   goto yysetstate;
 /*------------------------------------------------------------.
 | yynewstate -- push a new state, which is found in yystate.  |
 `------------------------------------------------------------*/
 yynewstate:
   /* In all cases, when you get here, the value and location stacks
      have just been pushed.  So pushing a state here evens the stacks.  */
   yyssp++;
 /*--------------------------------------------------------------------.
 | yynewstate -- set current state (the top of the stack) to yystate.  |
 `--------------------------------------------------------------------*/
 yysetstate:
   *yyssp = (yytype_int16) yystate;
   if (yyss + yystacksize - 1 <= yyssp)
 #if !defined yyoverflow && !defined YYSTACK_RELOCATE
     goto yyexhaustedlab;
 #else
     {
       /* Get the current used size of the three stacks, in elements.  */
       YYSIZE_T yysize = (YYSIZE_T) (yyssp - yyss + 1);
 # if defined yyoverflow
       {
         /* Give user a chance to reallocate the stack.  Use copies of
            these so that the &'s don't force the real ones into
            memory.  */
         YYSTYPE *yyvs1 = yyvs;
         yytype_int16 *yyss1 = yyss;
         /* Each stack pointer address is followed by the size of the
            data in use in that stack, in bytes.  This used to be a
            conditional around just the two extra args, but that might
            be undefined if yyoverflow is a macro.  */
         yyoverflow (YY_("memory exhausted"),
                     &yyss1, yysize * sizeof (*yyssp),
                     &yyvs1, yysize * sizeof (*yyvsp),
                     &yystacksize);
         yyss = yyss1;
         yyvs = yyvs1;
       }
 # else /* defined YYSTACK_RELOCATE */
       /* Extend the stack our own way.  */
       if (YYMAXDEPTH <= yystacksize)
         goto yyexhaustedlab;
       yystacksize *= 2;
       if (YYMAXDEPTH < yystacksize)
         yystacksize = YYMAXDEPTH;
       {
         yytype_int16 *yyss1 = yyss;
         union yyalloc *yyptr =
           (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
         if (! yyptr)
           goto yyexhaustedlab;
         YYSTACK_RELOCATE (yyss_alloc, yyss);
         YYSTACK_RELOCATE (yyvs_alloc, yyvs);
 # undef YYSTACK_RELOCATE
         if (yyss1 != yyssa)
           YYSTACK_FREE (yyss1);
       }
 # endif
       yyssp = yyss + yysize - 1;
       yyvsp = yyvs + yysize - 1;
       YYDPRINTF ((stderr, "Stack size increased to %lu\n",
                   (unsigned long) yystacksize));
       if (yyss + yystacksize - 1 <= yyssp)
         YYABORT;
     }
 #endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */
   YYDPRINTF ((stderr, "Entering state %d\n", yystate));
   if (yystate == YYFINAL)
     YYACCEPT;
   goto yybackup;
 /*-----------.
 | yybackup.  |
 `-----------*/
 yybackup:
   /* Do appropriate processing given the current state.  Read a
      lookahead token if we need one and don't already have one.  */
   /* First try to decide what to do without reference to lookahead token.  */
   yyn = yypact[yystate];
   if (yypact_value_is_default (yyn))
     goto yydefault;
   /* Not known => get a lookahead token if don't already have one.  */
   /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
   if (yychar == YYEMPTY)
     {
       YYDPRINTF ((stderr, "Reading a token: "));
       yychar = yylex ();
     }
   if (yychar <= YYEOF)
     {
       yychar = yytoken = YYEOF;
       YYDPRINTF ((stderr, "Now at end of input.\n"));
     }
   else
     {
       yytoken = YYTRANSLATE (yychar);
       YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
     }
   /* If the proper action on seeing token YYTOKEN is to reduce or to
      detect an error, take that action.  */
   yyn += yytoken;
   if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
     goto yydefault;
   yyn = yytable[yyn];
   if (yyn <= 0)
     {
       if (yytable_value_is_error (yyn))
         goto yyerrlab;
       yyn = -yyn;
       goto yyreduce;
     }
   /* Count tokens shifted since error; after three, turn off error
      status.  */
   if (yyerrstatus)
     yyerrstatus--;
   /* Shift the lookahead token.  */
   YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
   /* Discard the shifted token.  */
   yychar = YYEMPTY;
   yystate = yyn;
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   goto yynewstate;
 /*-----------------------------------------------------------.
 | yydefault -- do the default action for the current state.  |
 `-----------------------------------------------------------*/
 yydefault:
   yyn = yydefact[yystate];
   if (yyn == 0)
     goto yyerrlab;
   goto yyreduce;
 /*-----------------------------.
 | yyreduce -- do a reduction.  |
 `-----------------------------*/
 yyreduce:
   /* yyn is the number of a rule to reduce with.  */
   yylen = yyr2[yyn];
   /* If YYLEN is nonzero, implement the default value of the action:
      '$$ = $1'.
      Otherwise, the following line sets YYVAL to garbage.
      This behavior is undocumented and Bison
      users should not rely upon it.  Assigning to YYVAL
      unconditionally makes the parser a bit smaller, and it avoids a
      GCC warning that YYVAL may be used uninitialized.  */
   yyval = yyvsp[1-yylen];
   YY_REDUCE_PRINT (yyn);
   switch (yyn)
     {
         case 3:
 #line 142 "config.y" /* yacc.c:1652  */
     { doing = "device definitions"; }
 #line 1379 "y.tab.c" /* yacc.c:1652  */
     break;
   case 6:
 #line 149 "config.y" /* yacc.c:1652  */
     { yyval = newtype(yytext); }
 #line 1385 "y.tab.c" /* yacc.c:1652  */
     break;
   case 9:
 #line 156 "config.y" /* yacc.c:1652  */
     { yyval = yyvsp[0]; }
 #line 1391 "y.tab.c" /* yacc.c:1652  */
     break;
   case 10:
 #line 159 "config.y" /* yacc.c:1652  */
     { yyval = addton(yytext); }
 #line 1397 "y.tab.c" /* yacc.c:1652  */
     break;
   case 13:
 #line 166 "config.y" /* yacc.c:1652  */
     { addattr(CSR,    yyvsp[0]);    }
 #line 1403 "y.tab.c" /* yacc.c:1652  */
     break;
   case 14:
 #line 167 "config.y" /* yacc.c:1652  */
     { addattr(IRQ,    yyvsp[0]);    }
 #line 1409 "y.tab.c" /* yacc.c:1652  */
     break;
   case 15:
 #line 168 "config.y" /* yacc.c:1652  */
     { addattr(INTR,    0);  }
 #line 1415 "y.tab.c" /* yacc.c:1652  */
     break;
   case 16:
 #line 169 "config.y" /* yacc.c:1652  */
     { addattr(OPEN,    0);  }
 #line 1421 "y.tab.c" /* yacc.c:1652  */
     break;
   case 17:
 #line 170 "config.y" /* yacc.c:1652  */
     { addattr(CLOSE,   0);  }
 #line 1427 "y.tab.c" /* yacc.c:1652  */
     break;
   case 18:
 #line 171 "config.y" /* yacc.c:1652  */
     { addattr(INIT,    0);  }
 #line 1433 "y.tab.c" /* yacc.c:1652  */
     break;
   case 19:
 #line 172 "config.y" /* yacc.c:1652  */
     { addattr(GETC,    0);  }
 #line 1439 "y.tab.c" /* yacc.c:1652  */
     break;
   case 20:
 #line 173 "config.y" /* yacc.c:1652  */
     { addattr(PUTC,    0);  }
 #line 1445 "y.tab.c" /* yacc.c:1652  */
     break;
   case 21:
 #line 174 "config.y" /* yacc.c:1652  */
     { addattr(READ,    0);  }
 #line 1451 "y.tab.c" /* yacc.c:1652  */
     break;
   case 22:
 #line 175 "config.y" /* yacc.c:1652  */
     { addattr(WRITE,   0);  }
 #line 1457 "y.tab.c" /* yacc.c:1652  */
     break;
   case 23:
 #line 176 "config.y" /* yacc.c:1652  */
     { addattr(SEEK,    0);  }
 #line 1463 "y.tab.c" /* yacc.c:1652  */
     break;
   case 24:
 #line 177 "config.y" /* yacc.c:1652  */
     { addattr(CONTROL, 0);  }
 #line 1469 "y.tab.c" /* yacc.c:1652  */
     break;
   case 25:
 #line 180 "config.y" /* yacc.c:1652  */
     { yyval = 0; getattrid(yytext); }
 #line 1475 "y.tab.c" /* yacc.c:1652  */
     break;
   case 26:
 #line 183 "config.y" /* yacc.c:1652  */
     { yyval = config_atoi(yytext, yyleng); }
 #line 1481 "y.tab.c" /* yacc.c:1652  */
     break;
   case 27:
 #line 193 "config.y" /* yacc.c:1652  */
     { doing = "interface types"; }
 #line 1487 "y.tab.c" /* yacc.c:1652  */
     break;
   case 31:
 #line 203 "config.y" /* yacc.c:1652  */
     { newdev(yytext); }
 #line 1493 "y.tab.c" /* yacc.c:1652  */
     break;
   case 33:
 #line 209 "config.y" /* yacc.c:1652  */
     { devisid(yytext); }
 #line 1499 "y.tab.c" /* yacc.c:1652  */
     break;
   case 35:
 #line 215 "config.y" /* yacc.c:1652  */
     { devonid(yytext); }
 #line 1505 "y.tab.c" /* yacc.c:1652  */
     break;
 #line 1509 "y.tab.c" /* yacc.c:1652  */
       default: break;
     }
   /* User semantic actions sometimes alter yychar, and that requires
      that yytoken be updated with the new translation.  We take the
      approach of translating immediately before every use of yytoken.
      One alternative is translating here after every semantic action,
      but that translation would be missed if the semantic action invokes
      YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
      if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
      incorrect destructor might then be invoked immediately.  In the
      case of YYERROR or YYBACKUP, subsequent parser actions might lead
      to an incorrect destructor call or verbose syntax error message
      before the lookahead is translated.  */
   YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   *++yyvsp = yyval;
   /* Now 'shift' the result of the reduction.  Determine what state
      that goes to, based on the state we popped back to and the rule
      number reduced by.  */
   {
     const int yylhs = yyr1[yyn] - YYNTOKENS;
     const int yyi = yypgoto[yylhs] + *yyssp;
     yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
                ? yytable[yyi]
                : yydefgoto[yylhs]);
   }
   goto yynewstate;
 /*--------------------------------------.
 | yyerrlab -- here on detecting error.  |
 `--------------------------------------*/
 yyerrlab:
   /* Make sure we have latest lookahead translation.  See comments at
      user semantic actions for why this is necessary.  */
   yytoken = yychar == YYEMPTY ? YYEMPTY : YYTRANSLATE (yychar);
   /* If not already recovering from an error, report this error.  */
   if (!yyerrstatus)
     {
       ++yynerrs;
 #if ! YYERROR_VERBOSE
       yyerror (YY_("syntax error"));
 #else
 # define YYSYNTAX_ERROR yysyntax_error (&yymsg_alloc, &yymsg, \
                                         yyssp, yytoken)
       {
         char const *yymsgp = YY_("syntax error");
         int yysyntax_error_status;
         yysyntax_error_status = YYSYNTAX_ERROR;
         if (yysyntax_error_status == 0)
           yymsgp = yymsg;
         else if (yysyntax_error_status == 1)
           {
             if (yymsg != yymsgbuf)
               YYSTACK_FREE (yymsg);
             yymsg = (char *) YYSTACK_ALLOC (yymsg_alloc);
             if (!yymsg)
               {
                 yymsg = yymsgbuf;
                 yymsg_alloc = sizeof yymsgbuf;
                 yysyntax_error_status = 2;
               }
             else
               {
                 yysyntax_error_status = YYSYNTAX_ERROR;
                 yymsgp = yymsg;
               }
           }
         yyerror (yymsgp);
         if (yysyntax_error_status == 2)
           goto yyexhaustedlab;
       }
 # undef YYSYNTAX_ERROR
 #endif
     }
   if (yyerrstatus == 3)
     {
       /* If just tried and failed to reuse lookahead token after an
          error, discard it.  */
       if (yychar <= YYEOF)
         {
           /* Return failure if at end of input.  */
           if (yychar == YYEOF)
             YYABORT;
         }
       else
         {
           yydestruct ("Error: discarding",
                       yytoken, &yylval);
           yychar = YYEMPTY;
         }
     }
   /* Else will try to reuse lookahead token after shifting the error
      token.  */
   goto yyerrlab1;
 /*---------------------------------------------------.
 | yyerrorlab -- error raised explicitly by YYERROR.  |
 `---------------------------------------------------*/
 yyerrorlab:
   /* Pacify compilers when the user code never invokes YYERROR and the
      label yyerrorlab therefore never appears in user code.  */
   if (0)
     YYERROR;
   /* Do not reclaim the symbols of the rule whose action triggered
      this YYERROR.  */
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   yystate = *yyssp;
   goto yyerrlab1;
 /*-------------------------------------------------------------.
 | yyerrlab1 -- common code for both syntax error and YYERROR.  |
 `-------------------------------------------------------------*/
 yyerrlab1:
   yyerrstatus = 3;      /* Each real token shifted decrements this.  */
   for (;;)
     {
       yyn = yypact[yystate];
       if (!yypact_value_is_default (yyn))
         {
           yyn += YYTERROR;
           if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
             {
               yyn = yytable[yyn];
               if (0 < yyn)
                 break;
             }
         }
       /* Pop the current state because it cannot handle the error token.  */
       if (yyssp == yyss)
         YYABORT;
       yydestruct ("Error: popping",
                   yystos[yystate], yyvsp);
       YYPOPSTACK (1);
       yystate = *yyssp;
       YY_STACK_PRINT (yyss, yyssp);
     }
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   /* Shift the error token.  */
   YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);
   yystate = yyn;
   goto yynewstate;
 /*-------------------------------------.
 | yyacceptlab -- YYACCEPT comes here.  |
 `-------------------------------------*/
 yyacceptlab:
   yyresult = 0;
   goto yyreturn;
 /*-----------------------------------.
 | yyabortlab -- YYABORT comes here.  |
 `-----------------------------------*/
 yyabortlab:
   yyresult = 1;
   goto yyreturn;
 #if !defined yyoverflow || YYERROR_VERBOSE
 /*-------------------------------------------------.
 | yyexhaustedlab -- memory exhaustion comes here.  |
 `-------------------------------------------------*/
 yyexhaustedlab:
   yyerror (YY_("memory exhausted"));
   yyresult = 2;
   /* Fall through.  */
 #endif
 /*-----------------------------------------------------.
 | yyreturn -- parsing is finished, return the result.  |
 `-----------------------------------------------------*/
 yyreturn:
   if (yychar != YYEMPTY)
     {
       /* Make sure we have latest lookahead translation.  See comments at
          user semantic actions for why this is necessary.  */
       yytoken = YYTRANSLATE (yychar);
       yydestruct ("Cleanup: discarding lookahead",
                   yytoken, &yylval);
     }
   /* Do not reclaim the symbols of the rule whose action triggered
      this YYABORT or YYACCEPT.  */
   YYPOPSTACK (yylen);
   YY_STACK_PRINT (yyss, yyssp);
   while (yyssp != yyss)
     {
       yydestruct ("Cleanup: popping",
                   yystos[*yyssp], yyvsp);
       YYPOPSTACK (1);
     }
 #ifndef yyoverflow
   if (yyss != yyssa)
     YYSTACK_FREE (yyss);
 #endif
 #if YYERROR_VERBOSE
   if (yymsg != yymsgbuf)
     YYSTACK_FREE (yymsg);
 #endif
   return yyresult;
 }
Variable Documentation
brkcount
int brkcount = 0
Definition at line 105 of file y.tab.c.
Referenced by addattr(), if(), and main().
confc
FILE* confc
Definition at line 102 of file y.tab.c.
Referenced by main().
confh
FILE* confh
Definition at line 103 of file y.tab.c.
Referenced by main().
devs
struct dev_ent devs[NDEVS]
Definition at line 134 of file y.tab.c.
Referenced by addattr(), devisid(), devonid(), main(), and newdev().
devstab
char* devstab[]
Initial value:
= {
    "/* Device table entry */",
    "struct\tdentry\t{",
    "\tint32   dvnum;",
    "\tint32   dvminor;",
    "\tchar    *dvname;",
    "\tdevcall (*dvinit) (struct dentry *);",
    "\tdevcall (*dvopen) (struct dentry *, char *, char *);",
    "\tdevcall (*dvclose)(struct dentry *);",
    "\tdevcall (*dvread) (struct dentry *, void *, uint32);",
    "\tdevcall (*dvwrite)(struct dentry *, void *, uint32);",
    "\tdevcall (*dvseek) (struct dentry *, int32);",
    "\tdevcall (*dvgetc) (struct dentry *);",
    "\tdevcall (*dvputc) (struct dentry *, char);",
    "\tdevcall (*dvcntl) (struct dentry *, int32, int32, int32);",
    "\tvoid    *dvcsr;",
    "\tvoid    (*dvintr)(void);",
    "\tbyte    dvirq;",
    "};\n",
    "extern struct  dentry  devtab[]; /* one entry per device */",
    NULL
}
Definition at line 137 of file y.tab.c.
Referenced by main().
doing
char* doing = "device type declarations"
Definition at line 107 of file y.tab.c.
Referenced by yyerror(), and yyparse().
dtypes
struct dev_ent dtypes[NTYPES]
Definition at line 131 of file y.tab.c.
Referenced by addattr(), addton(), devisid(), devonid(), main(), and newtype().
linectr
int linectr = 1
Definition at line 100 of file y.tab.c.
Referenced by addton(), devisid(), devonid(), getattrid(), if(), newdev(), newtype(), and yyerror().
ndevs
int ndevs = 0
Definition at line 135 of file y.tab.c.
Referenced by addattr(), devisid(), devonid(), main(), and newdev().
ntypes
int ntypes = 0
Definition at line 132 of file y.tab.c.
Referenced by addattr(), addton(), devisid(), devonid(), main(), and newtype().
saveattrid
char saveattrid[MAXNAME]
Definition at line 160 of file y.tab.c.
Referenced by addattr(), and getattrid().
yychar
int yychar
Definition at line 1124 of file y.tab.c.
Referenced by yyparse().
yycheck
const yytype_int8 yycheck[] static
Initial value:
=
{
       9,    10,    11,    12,    13,    14,    15,    16,    17,    18,
       0,     5,    21,    22,    27,    28,    29,    30,    31,    32,
      33,    34,    35,    16,     8,     3,     8,     8,    20,    22,
       8,    19,     7,    20,     8,     8,    15,    -1,    -1,    25
}
Definition at line 655 of file y.tab.c.
Referenced by yyparse().
yydefact
const yytype_uint8 yydefact[] static
Initial value:
=
{
       3,     0,     0,     1,    27,     6,     4,     0,     2,     0,
      31,    28,    11,     0,     0,     5,    11,    29,     0,     0,
      10,     9,    11,     7,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,    12,    33,    32,     0,
      30,     8,    26,    13,    14,    25,    15,    18,    16,    17,
      21,    22,    23,    24,    19,    20,    35,    34
}
Definition at line 620 of file y.tab.c.
Referenced by yyparse().
yydefgoto
const yytype_int8 yydefgoto[] static
Initial value:
=
{
      -1,     1,     2,     6,     7,    15,    16,    21,    17,    36,
      46,    43,     8,    11,    12,    13,    19,    38,    40,    57
}
Definition at line 638 of file y.tab.c.
Referenced by yyparse().
yyleng
int yyleng
Referenced by yyparse().
yylval
YYSTYPE yylval
Definition at line 1127 of file y.tab.c.
Referenced by yyparse().
yynerrs
int yynerrs
Definition at line 1129 of file y.tab.c.
Referenced by yyparse().
yypact
const yytype_int8 yypact[] static
Initial value:
=
{
     -14,    10,    22,   -14,   -14,   -14,   -14,     6,    16,     8,
     -14,   -14,   -14,    12,    18,     8,   -14,    -9,    19,    13,
     -14,   -14,   -14,    -9,    25,    25,    26,    26,    26,    26,
      26,    26,    26,    26,    26,    26,   -14,   -14,   -14,    27,
     -14,    -9,   -14,   -14,   -14,   -14,   -14,   -14,   -14,   -14,
     -14,   -14,   -14,   -14,   -14,   -14,   -14,   -14
}
Definition at line 607 of file y.tab.c.
Referenced by yyparse().
yypgoto
const yytype_int8 yypgoto[] static
Initial value:
=
{
     -14,   -14,   -14,   -14,   -14,   -14,    21,   -14,     7,   -14,
     -13,    14,   -14,   -14,   -14,   -14,   -14,   -14,   -14,   -14
}
Definition at line 631 of file y.tab.c.
Referenced by yyparse().
yyr1
const yytype_uint8 yyr1[] static
Initial value:
=
{
       0,    23,    24,    25,    25,    26,    27,    28,    28,    29,
      30,    31,    31,    32,    32,    32,    32,    32,    32,    32,
      32,    32,    32,    32,    32,    33,    34,    35,    35,    36,
      37,    38,    39,    40,    41,    42
}
Definition at line 676 of file y.tab.c.
Referenced by yyparse().
yyr2
const yytype_uint8 yyr2[] static
Initial value:
=
{
       0,     2,     3,     0,     2,     3,     1,     2,     3,     2,
       1,     0,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     1,     1,     0,     2,     2,
       3,     1,     2,     1,     2,     1
}
Definition at line 685 of file y.tab.c.
Referenced by yyparse().
yystos
const yytype_uint8 yystos[] static
Initial value:
=
{
       0,    24,    25,     0,     3,     8,    26,    27,    35,     5,
       8,    36,    37,    38,    20,    28,    29,    31,    19,    39,
       8,    30,    29,    31,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    21,    22,    32,     8,    40,    20,
      41,    31,     7,    34,    34,     8,    33,    33,    33,    33,
      33,    33,    33,    33,    33,    33,     8,    42
}
Definition at line 665 of file y.tab.c.
Referenced by yyparse().
yytable
const yytype_uint8 yytable[] static
Initial value:
=
{
      24,    25,    26,    27,    28,    29,    30,    31,    32,    33,
       3,     9,    34,    35,    47,    48,    49,    50,    51,    52,
      53,    54,    55,    23,    10,     4,    20,    37,    14,    41,
       5,    18,    42,    39,    45,    56,    22,     0,     0,    44
}
Definition at line 647 of file y.tab.c.
Referenced by yyparse().
yytext
char* yytext
Referenced by yyparse().
yytranslate
const yytype_uint8 yytranslate[] static
Definition at line 527 of file y.tab.c.