XINU: system/ptcount.c File Reference
ptcount.c File Reference
#include <xinu.h>
Functions
int32 ptcount (int32 portid)
Function Documentation
ptcount()
int32 ptcount (int32 portid)
Definition at line 14 of file ptcount.c.
References disable(), isbadport, porttab, PT_ALLOC, ptentry::ptrsem, ptentry::ptssem, ptentry::ptstate, restore(), semcount(), and SYSERR.
 {
     intmask mask;           /* Saved interrupt mask     */
     int32   count;          /* Count of messages available  */
     int32   sndcnt;         /* Count of sender semaphore    */
     struct  ptentry *ptptr;     /* Pointer to port table entry  */
     mask = disable();
     if ( isbadport(portid) ||
         (ptptr= &porttab[portid])->ptstate != PT_ALLOC ) {
             restore(mask);
             return SYSERR;
     }
     /* Get count of messages available */
     count = semcount(ptptr->ptrsem);
     /* If messages are waiting, check for blocked senders */
     if (count >= 0) {
         sndcnt = semcount(ptptr->ptssem);
         if (sndcnt < 0) {   /* -sndcnt senders blocked */
             count += -sndcnt;
         }
     }
     restore(mask);
     return count;
 }