XINU: system/evec.c File Reference
evec.c File Reference
#include <xinu.h>
#include <stdio.h>
Functions
int32 initintc ()
void irq_dispatch ()
int32 set_evec (uint32 xnum, uint32 handler)
void userret (void)
プロセスが最上位の関数に戻る時に呼ばれる。現在のプロセスを終了させる。
Variables
char expmsg1 [] = "Unhandled exception. Link Register: 0x%x"
char expmsg2 [] = "**** EXCEPTION ****"
uint32 intc_vector [128]
Function Documentation
initintc()
int32 initintc (void)
Definition at line 18 of file evec.c.
References INTC_SYSCONFIG_SOFTRESET, INTC_SYSSTATUS_RESETDONE, OK, intc_csreg::sysconfig, and intc_csreg::sysstatus.
Referenced by platinit().
 {
     struct  intc_csreg *csrptr = (struct intc_csreg *)0x48200000;
     /* Reset the interrupt controller */
     csrptr->sysconfig |= (INTC_SYSCONFIG_SOFTRESET);
     /* Wait until reset is complete */
     while((csrptr->sysstatus & INTC_SYSSTATUS_RESETDONE) == 0);
     return OK;
 }
irq_dispatch()
void irq_dispatch ()
Definition at line 72 of file evec.c.
References intc_csreg::control, currpid, DEFER_START, DEFER_STOP, disable(), INTC_CONTROL_NEWIRQAGR, intc_vector, kprintf(), panic(), proctab, resched_cntl(), intc_csreg::sir_irq, and trap().
 {
     struct  intc_csreg *csrptr = (struct intc_csreg *)0x48200000;
     uint32  xnum;       /* Interrupt number of device   */
     interrupt (*handler)(); /* Pointer to handler function  */
     /* Get the interrupt number from the Interrupt controller */
     xnum = csrptr->sir_irq & 0x7F;
     /* Defer scheduling until interrupt is acknowledged */
     resched_cntl(DEFER_START);
     /* If a handler is set for the interrupt, call it */
     if(intc_vector[xnum]) {
         handler = ( interrupt(*)() )intc_vector[xnum];
         handler(xnum);
     }
     /* Acknowledge the interrupt */
     csrptr->control |= (INTC_CONTROL_NEWIRQAGR);
     /* Resume scheduling */
     resched_cntl(DEFER_STOP);
 }
set_evec()
int32 set_evec (uint32 xnum, uint32 handler)
Definition at line 37 of file evec.c.
References intc_csreg::banks, intc_vector, intc_bank::mir, OK, and SYSERR.
Referenced by clkinit(), ethinit(), gpioinit(), and ttyinit().
 {
     struct  intc_csreg *csrptr = (struct intc_csreg *)0x48200000;
     uint32  bank;   /* bank number in int controller    */
     uint32  mask;   /* used to set bits in bank     */
     /* There are only 127 interrupts allowed 0-126 */
     if(xnum > 127) {
         return SYSERR;
     }
     /* Install the handler */
     intc_vector[xnum] = handler;
     /* Get the bank number based on interrupt number */
     bank = (xnum/32);
     /* Get the bit inside the bank */
     mask = (0x00000001 << (xnum%32));
     /* Reset the bit to enable that interrupt number */
     csrptr->banks[bank].mir &= (~mask);
     return OK;
 }
userret()
void userret (void)
プロセスが最上位の関数に戻る時に呼ばれる。現在のプロセスを終了させる。
Note
プロセス作成時に、戻りアドレスとしてuserret()がスタックに積まれる。
Definition at line 11 of file userret.c.
References getpid(), and kill().
 {
     kill(getpid()); /* Force process to exit */
 }
Variable Documentation
expmsg1
char expmsg1[] = "Unhandled exception. Link Register: 0x%x"
Definition at line 12 of file evec.c.
expmsg2
char expmsg2[] = "**** EXCEPTION ****"
Definition at line 13 of file evec.c.
intc_vector
uint32 intc_vector[128]
Definition at line 11 of file evec.c.
Referenced by irq_dispatch(), and set_evec().