XINU: system/write.c File Reference
write.c File Reference
#include <xinu.h>
Functions
syscall write (did32 descrp, char *buffer, uint32 count)
Function Documentation
write()
syscall write (did32 descrp, char * buffer, uint32 count)
Definition at line 9 of file write.c.
References devtab, disable(), dentry::dvwrite, isbaddev, restore(), and SYSERR.
Referenced by arp_in(), arp_resolve(), ip_out(), lfdballoc(), lfdbfree(), lfflush(), lfiballoc(), lfibput(), lfscreate(), and xsh_rdstest().
 {
     intmask     mask;       /* Saved interrupt mask     */
     struct dentry   *devptr;    /* Entry in device switch table */
     int32       retval;     /* Value to return to caller    */
     mask = disable();
     if (isbaddev(descrp)) {
         restore(mask);
         return SYSERR;
     }
     devptr = (struct dentry *) &devtab[descrp];
     retval = (*devptr->dvwrite) (devptr, buffer, count);
     restore(mask);
     return retval;
 }