XINU: system/sleep.c File Reference
sleep.c File Reference
#include <xinu.h>
Macros
#define MAXSECONDS 2147483 /* Max seconds per 32-bit msec */
Functions
syscall sleep (int32 delay)
syscall sleepms (int32 delay)
Macro Definition Documentation
MAXSECONDS
#define MAXSECONDS 2147483 /* Max seconds per 32-bit msec */
Definition at line 5 of file sleep.c.
Referenced by sleep().
Function Documentation
sleep()
syscall sleep (int32 delay)
Definition at line 11 of file sleep.c.
References MAXSECONDS, OK, sleepms(), and SYSERR.
Referenced by xsh_sleep().
 {
     if ( (delay < 0) || (delay > MAXSECONDS) ) {
         return SYSERR;
     }
     sleepms(1000*delay);
     return OK;
 }
sleepms()
syscall sleepms (int32 delay)
Definition at line 26 of file sleep.c.
References currpid, disable(), insertd(), OK, PR_SLEEP, proctab, procent::prstate, resched(), restore(), sleepq, SYSERR, and yield().
Referenced by main(), and sleep().
 {
     intmask mask;           /* Saved interrupt mask     */
     if (delay < 0) {
         return SYSERR;
     }
     if (delay == 0) {
         yield();
         return OK;
     }
     /* Delay calling process */
     mask = disable();
     if (insertd(currpid, sleepq, delay) == SYSERR) {
         restore(mask);
         return SYSERR;
     }
     proctab[currpid].prstate = PR_SLEEP;
     resched();
     restore(mask);
     return OK;
 }