XINU: system/exit.c File Reference
exit.c File Reference
#include <xinu.h>
Functions
void exit (void)
Function Documentation
exit()
void exit (void)
Definition at line 9 of file exit.c.
References getpid(), and kill().
Referenced by addton(), devisid(), devonid(), getattrid(), if(), main(), newdev(), and newtype().
 {
     kill(getpid());     /* Kill the current process */
 }