XINU: net/net.c File Reference
net.c File Reference
#include <xinu.h>
#include <stdio.h>
Functions
void eth_hton (struct netpacket *pktptr)
void eth_ntoh (struct netpacket *pktptr)
uint16 getport ()
void net_init (void)
process netin ()
Variables
bpid32 netbufpool
struct network NetData
uint32 netportseed
Function Documentation
eth_hton()
void eth_hton (struct netpacket * pktptr)
Definition at line 127 of file net.c.
References htons, and netpacket::net_ethtype.
Referenced by arp_in(), arp_resolve(), and ip_out().
 {
     pktptr->net_ethtype = htons(pktptr->net_ethtype);
 }
eth_ntoh()
void eth_ntoh (struct netpacket * pktptr)
Definition at line 139 of file net.c.
References netpacket::net_ethtype, and ntohs.
Referenced by netin().
 {
     pktptr->net_ethtype = ntohs(pktptr->net_ethtype);
 }
getport()
uint16 getport (void)
Definition at line 150 of file net.c.
References netportseed.
Referenced by tftpget_mb().
 {
     netportseed = 1103515245 * netportseed + 12345;
     return 50000 + ((uint16)((netportseed >> 16)) % 15535);
 }
net_init()
void net_init (void)
Definition at line 15 of file net.c.
References arp_init(), control(), create(), ETH_ADDR_LEN, ETH_CTRL_GET_MAC, ETHER0, getticks(), icmp_init(), ICMP_QSIZ, ICMP_SLOTS, ipoqueue, ipout(), iqentry::iqhead, iqentry::iqsem, iqentry::iqtail, memset(), mkbufpool(), netbufpool, NetData, netin(), netportseed, NETPRIO, NETSTK, NULL, NULLCH, PACKLEN, panic(), resume(), semcreate(), SYSERR, udp_init(), UDP_QSIZ, and UDP_SLOTS.
Referenced by nulluser().
 {
     int32   nbufs;          /* Total no of buffers      */
     /* Initialize the network data structure */
     memset((char *)&NetData, NULLCH, sizeof(struct network));
     /* Obtain the Ethernet MAC address */
     control(ETHER0, ETH_CTRL_GET_MAC, (int32)NetData.ethucast, 0);
     memset((char *)NetData.ethbcast, 0xFF, ETH_ADDR_LEN);
     /* Initialize the random port seed */
     netportseed = getticks();
     /* Create the network buffer pool */
     nbufs = UDP_SLOTS * UDP_QSIZ + ICMP_SLOTS * ICMP_QSIZ + 1;
     netbufpool = mkbufpool(PACKLEN, nbufs);
     /* Initialize the ARP cache */
     arp_init();
     /* Initialize UDP */
     udp_init();
     /* Initialize ICMP */
     icmp_init();
     /* Initialize the IP output queue */
     ipoqueue.iqhead = 0;
     ipoqueue.iqtail = 0;
     ipoqueue.iqsem = semcreate(0);
     if((int32)ipoqueue.iqsem == SYSERR) {
         panic("Cannot create ip output queue semaphore");
         return;
     }
     /* Create the IP output process */
     resume(create(ipout, NETSTK, NETPRIO, "ipout", 0, NULL));
     /* Create a network input process */
     resume(create(netin, NETSTK, NETPRIO, "netin", 0, NULL));
 }
netin()
process netin (void)
Definition at line 76 of file net.c.
References arp_in(), ETH_ARP, ETH_IP, ETH_IPv6, eth_ntoh(), ETHER0, freebuf(), getbuf(), ip_in(), netbufpool, PACKLEN, panic(), read(), and SYSERR.
Referenced by net_init().
 {
     struct  netpacket *pkt;     /* Ptr to current packet    */
     int32   retval;         /* Return value from read   */
     /* Do forever: read a packet from the network and process */
     while(1) {
         /* Allocate a buffer */
         pkt = (struct netpacket *)getbuf(netbufpool);
         /* Obtain next packet that arrives */
         retval = read(ETHER0, (char *)pkt, PACKLEN);
         if(retval == SYSERR) {
             panic("Cannot read from Ethernet\n");
         }
         /* Convert Ethernet Type to host order */
         eth_ntoh(pkt);
         /* Demultiplex on Ethernet type */
         switch (pkt->net_ethtype) {
             case ETH_ARP:           /* Handle ARP   */
             arp_in((struct arppacket *)pkt);
             continue;
             case ETH_IP:            /* Handle IP    */
             ip_in(pkt);
             continue;
             case ETH_IPv6:          /* Handle IPv6  */
             freebuf((char *)pkt);
             continue;
             default:    /* Ignore all other incoming packets    */
             freebuf((char *)pkt);
             continue;
         }
     }
 }
Variable Documentation
netbufpool
bpid32 netbufpool
Definition at line 7 of file net.c.
Referenced by icmp_mkpkt(), net_init(), netin(), udp_send(), and udp_sendto().
NetData
struct network NetData
Definition at line 6 of file net.c.
Referenced by arp_in(), arp_resolve(), dhcp_bld_bootp_msg(), dns_geta(), dnslookup(), getlocalip(), getutime(), icmp_mkpkt(), ip_in(), ip_send(), ipout(), net_init(), rdscomm(), startup(), udp_send(), udp_sendto(), and xsh_netinfo().
netportseed
uint32 netportseed
Definition at line 8 of file net.c.
Referenced by getport(), and net_init().