XINU: lib/strlen.c File Reference
strlen.c File Reference
NULL終端された文字列の長さを返す。NULL終端は長さに含まない。
Functions
int strlen (char *str)
NULL終端された文字列の長さを返す。NULL終端は長さに含まない。
Detailed Description
NULL終端された文字列の長さを返す。NULL終端は長さに含まない。
Definition in file strlen.c.
Function Documentation
strlen()
int strlen (char * str)
NULL終端された文字列の長さを返す。NULL終端は長さに含まない。
Parameters
[in] str 長さを調べる対象の文字列
Returns
文字列の長さを返す。NULL終端は長さに含まない。
Definition at line 11 of file strlen.c.
Referenced by addton(), devisid(), devonid(), dns_bldq(), dns_geta(), getattrid(), if(), newdev(), newtype(), and xsh_ping().
 {
     int len;
     len = 0;
     while (*str++ != '\0')
     {
         len++;
     }
     return len;
 }