XINU: device/rfs/rfscomm.c File Reference
rfscomm.c File Reference
#include <xinu.h>
Functions
int32 rfscomm (struct rf_msg_hdr *msg, int32 mlen, struct rf_msg_hdr *reply, int32 rlen)
Function Documentation
rfscomm()
int32 rfscomm (struct rf_msg_hdr * msg, int32 mlen, struct rf_msg_hdr * reply, int32 rlen)
Definition at line 10 of file rfscomm.c.
References htonl, kprintf(), ntohl, ntohs, Rf_data, rfdata::rf_loc_port, RF_MSG_RESPONSE, rfdata::rf_registered, RF_RETRIES, rfdata::rf_seq, rfdata::rf_ser_ip, rfdata::rf_ser_port, RF_TIMEOUT, rfdata::rf_udp_slot, SYSERR, TIMEOUT, TRUE, udp_recv(), udp_register(), and udp_send().
Referenced by rflread(), rflwrite(), rfscontrol(), rfsndmsg(), and rfsopen().
 {
     int32   i;          /* Counts retries       */
     int32   retval;         /* Return value         */
     int32   seq;            /* Sequence for this exchange   */
     int16   rtype;          /* Reply type in host byte order*/
     int32   slot;           /* UDP slot         */
     /* For the first time after reboot, register the server port */
     if ( ! Rf_data.rf_registered ) {
         if ( (slot = udp_register(Rf_data.rf_ser_ip,
                 Rf_data.rf_ser_port,
                 Rf_data.rf_loc_port)) == SYSERR) {
             return SYSERR;
         }
         Rf_data.rf_udp_slot = slot;
         Rf_data.rf_registered = TRUE;
     }
     /* Assign message next sequence number */
     seq = Rf_data.rf_seq++;
     msg->rf_seq = htonl(seq);
     /* Repeat RF_RETRIES times: send message and receive reply */
     for (i=0; i<RF_RETRIES; i++) {
         /* Send a copy of the message */
         retval = udp_send(Rf_data.rf_udp_slot, (char *)msg,
             mlen);
         if (retval == SYSERR) {
             kprintf("Cannot send to remote file server\n");
             return SYSERR;
         }
         /* Receive a reply */
         retval = udp_recv(Rf_data.rf_udp_slot, (char *)reply,
             rlen, RF_TIMEOUT);
         if (retval == TIMEOUT) {
             continue;
         } else if (retval == SYSERR) {
             kprintf("Error reading remote file reply\n");
             return SYSERR;
         }
         /* Verify that sequence in reply matches request */
         if (ntohl(reply->rf_seq) != seq) {
             continue;
         }
         /* Verify the type in the reply matches the request */
         rtype = ntohs(reply->rf_type);
         if (rtype != ( ntohs(msg->rf_type) | RF_MSG_RESPONSE) ) {
             continue;
         }
         return retval;      /* Return length to caller */
     }
     /* Retries exhausted without success */
     kprintf("Timeout on exchange with remote file server\n");
     return TIMEOUT;
 }