XINU: device/nam/mount.c File Reference
mount.c File Reference
#include <xinu.h>
Functions
syscall mount (char *prefix, char *replace, did32 device)
int32 namlen (char *name, int32 maxlen)
Function Documentation
mount()
syscall mount (char * prefix, char * replace, did32 device)
Definition at line 9 of file mount.c.
References disable(), isbaddev, nametab, namlen(), nmentry::ndevice, NM_PRELEN, NM_REPLLEN, NNAMES, nnames, nmentry::nprefix, nmentry::nreplace, OK, restore(), and SYSERR.
Referenced by naminit().
 {
     intmask mask;           /* Saved interrupt mask     */
     struct  nmentry *namptr;    /* Pointer to unused table entry*/
     int32   psiz, rsiz;     /* Sizes of prefix & replacement*/
     int32   i;          /* Counter for copy loop    */
         mask = disable();
     psiz = namlen(prefix, NM_PRELEN);
     rsiz = namlen(replace, NM_REPLLEN);
     /* If arguments are invalid or table is full, return error */
     if ( (psiz == SYSERR)   || (rsiz == SYSERR) ||
          (isbaddev(device)) || (nnames >= NNAMES) ) {
         restore(mask);
         return SYSERR;
     }
     /* Allocate a slot in the table */
     namptr = &nametab[nnames];  /* Next unused entry in table   */
     /* copy prefix and replacement strings and record device ID */
     for (i=0; i<psiz; i++) {    /* Copy prefix into table entry */
         namptr->nprefix[i] = *prefix++;
     }
     for (i=0; i<rsiz; i++) {    /* Copy replacement into entry  */
         namptr->nreplace[i] = *replace++;
     }
     namptr->ndevice = device;   /* Record the device ID     */
         nnames++;           /* Increment number of names    */
     restore(mask);
     return OK;
 }
namlen()
int32 namlen (char * name, int32 maxlen)
Definition at line 60 of file mount.c.
References NULLCH, and SYSERR.
Referenced by dns_geta(), mount(), and namrepl().
 {
     int32   i;          /* Count of characters found    */
     /* Search until a null terminator or length reaches max */
     for (i=0; i < maxlen; i++) {
         if (*name++ == NULLCH) {
             return i+1; /* Include NULLCH in length */
         }
     }
     return SYSERR;
 }