XINU: include/stdio.h File Reference
stdio.h File Reference
Macros
#define scanf(fmt, args) fscanf(CONSOLE, fmt, args)
#define stderr ((proctab[currpid]).prdesc[2])
#define stdin ((proctab[currpid]).prdesc[0])
#define stdout ((proctab[currpid]).prdesc[1])
Functions
int32 _doscan (char *, int32 *, int32(*)(void), int32(*)(char), int32, int32)
int32 fgetc (int)
デバイス（ファイル）から文字を読み込む。
char * fgets (char *, int32, int32)
デバイス（ファイル）から文字列を読み込む。
int32 fprintf (int, char *,...)
int32 fputc (int32, int32)
文字をデバイス（ファイル）に書き込む。
int32 fputs (char *, int32)
文字列をデバイス（ファイル）に書き込む。
int32 fscanf (int32, char *, int32)
int32 getchar (void)
STDIN（標準入力）から文字を読み込む。
int32 printf (const char *,...)
int32 putchar (int32 c)
int32 sprintf (char *, char *,...)
int32 sscanf (char *, char *, int32)
Macro Definition Documentation
scanf
#define scanf (fmt, args) fscanf(CONSOLE, fmt, args)
Definition at line 10 of file stdio.h.
stderr
#define stderr ((proctab[currpid]).prdesc[2])
Definition at line 17 of file stdio.h.
Referenced by addattr(), addton(), devisid(), devonid(), getattrid(), getutime(), if(), main(), newdev(), newtype(), xsh_cat(), xsh_clear(), xsh_date(), xsh_devdump(), xsh_help(), xsh_kill(), xsh_ls(), xsh_memdump(), xsh_memstat(), xsh_netinfo(), xsh_ping(), xsh_ps(), xsh_sleep(), xsh_udpdump(), xsh_udpecho(), xsh_udpeserver(), xsh_uptime(), yyerror(), and yyparse().
stdin
#define stdin ((proctab[currpid]).prdesc[0])
Definition at line 15 of file stdio.h.
Referenced by getchar(), if(), main(), and xsh_cat().
stdout
#define stdout ((proctab[currpid]).prdesc[1])
Definition at line 16 of file stdio.h.
Referenced by hexdump(), hexdump_print(), if(), printf(), putchar(), and xsh_cat().
Function Documentation
_doscan()
int32 _doscan (char * , int32 * , int32(*)(void) , int32(*)(char) , int32 , int32)
fgetc()
int32 fgetc (int dev)
デバイス（ファイル）から文字を読み込む。
Parameters
[in] dev デバイスディスクリプタ
Returns
成功時は読み込んだ文字、異常時はEOFを返す。
Definition at line 19 of file fgetc.c.
References EOF, and getc().
Referenced by getchar().
 {
     int result = (int)getc(dev);
     if (0 > result)
     {
         return EOF;
     }
     else
     {
         return result;
     }
 }
fgets()
char* fgets (char * s, int n, int dev)
デバイス（ファイル）から文字列を読み込む。
以下のいずれかの場合に、文字列の読み込みを停止する
・最大読み込みByteに達した
・行の最後（改行コード）まで達した（Linux形式=LFか、Mac形式=CRのどちらか）
・EOFまで達した
文字列（改行コード含む）の最後にはNULL終端を付与する。
Parameters
[in,out] s 読み込んだ文字列
[in] n 最大読み込みByte
[in] dev デバイスディスクリプタ
Returns
成功時は読み込んだ文字列（改行コードとNULL終端含む）、EOFや空文字の場合はNULLを返す。
Definition at line 25 of file fgets.c.
References getc(), and NULL.
 {
     int c = 0;
     char *cs;
     cs = s;
     /* Read characters until maximum read length, */
     /*  end of line, or end of file               */
     while ((--n > 0) && ((c = getc(dev)) >= 0))
     {
         *cs++ = c;
         if (('\n' == c) || ('\r' == c))
         {
             break;
         }
     }
     /* Check for EOF or empty string */
     if ((c < 0) && (cs == s))
     {
         return NULL;
     }
     /* Terminate string and return */
     *cs++ = '\0';
     return s;
 }
fprintf()
int32 fprintf (int , char * , ...)
Definition at line 14 of file fprintf.c.
References _fdoprnt(), putc(), va_end, and va_start.
Referenced by addattr(), addton(), devisid(), devonid(), getattrid(), getutime(), hexdump(), hexdump_print(), if(), main(), newdev(), newtype(), shell(), xsh_cat(), xsh_clear(), xsh_date(), xsh_devdump(), xsh_help(), xsh_kill(), xsh_ls(), xsh_memdump(), xsh_memstat(), xsh_netinfo(), xsh_ping(), xsh_ps(), xsh_sleep(), xsh_udpdump(), xsh_udpecho(), xsh_udpeserver(), xsh_uptime(), and yyerror().
 {
     va_list ap;
     int putc(did32, char);
     va_start(ap, fmt);
     _fdoprnt(fmt, ap, putc, dev);
     va_end(ap);
     return 0;
 }
fputc()
int32 fputc (int c, int dev)
文字をデバイス（ファイル）に書き込む。
Parameters
[in] c 書き込む文字
[in] dev デバイスディスクリプタ
Returns
成功時は書き込んだ文字、異常時はEOFを返す。
Definition at line 24 of file fputc.c.
References EOF, putc(), and SYSERR.
Referenced by putchar().
 {
     if (SYSERR == (int)putc(dev, c))
     {
         return EOF;
     }
     else
     {
         return c;
     }
 }
fputs()
int32 fputs (char * s, int dev)
文字列をデバイス（ファイル）に書き込む。
Parameters
[in] s 書き込む文字列（NULL終端されている事）
[in] dev デバイスディスクリプタ
Returns
最後にputc()で書き込んだ結果を返す（詳細は、 putc()を参照する事）
Definition at line 15 of file fputs.c.
References putc().
 {
     int r = 0, c;
     while ((c = (*s++)))
     {
         r = putc(dev, c);
     }
     return r;
 }
fscanf()
int32 fscanf (int32 , char * , int32)
Definition at line 23 of file fscanf.c.
References _doscan(), EMPTY, getch(), and ungetch().
 {
     int buf;
     buf = EMPTY;
     return (_doscan
             (fmt, (int **)&args, getch, ungetch, dev, (int)(int)&buf));
 }
getchar()
int32 getchar (void)
STDIN（標準入力）から文字を読み込む。
Returns
成功時は読み込んだ文字、異常時はEOFを返す。
Definition at line 12 of file getchar.c.
References fgetc(), and stdin.
 {
     return fgetc(stdin);
 }
printf()
int32 printf (const char * , ...)
Definition at line 13 of file printf.c.
References _fdoprnt(), putc(), stdout, va_end, and va_start.
Referenced by arp_dmp(), arp_dump(), main(), printFreeList(), printMemUse(), xsh_argecho(), xsh_arp(), xsh_cat(), xsh_clear(), xsh_date(), xsh_devdump(), xsh_echo(), xsh_help(), xsh_kill(), xsh_ls(), xsh_memdump(), xsh_memstat(), xsh_netinfo(), xsh_ping(), xsh_ps(), xsh_sleep(), xsh_udpdump(), xsh_udpecho(), xsh_udpeserver(), and xsh_uptime().
 {
     va_list ap;
     syscall putc(did32, char);
     va_start(ap, fmt);
     _fdoprnt((char *)fmt, ap, putc, stdout);
     va_end(ap);
     return 0;
 }
putchar()
int32 putchar (int32 c)
Definition at line 10 of file putchar.c.
References fputc(), and stdout.
 {
     return fputc(c, stdout);
 }
sprintf()
int32 sprintf (char * , char * , ...)
Definition at line 12 of file sprintf.c.
References _fdoprnt(), sprntf(), va_end, and va_start.
Referenced by ascdate(), startup(), and xsh_netinfo().
 {
     va_list ap;
     char *s;
     s = str;
     va_start(ap, fmt);
     _fdoprnt(fmt, ap, sprntf, (int)&s);
     va_end(ap);
     *s++ = '\0';
     return ((int)str);
 }
sscanf()
int32 sscanf (char * , char * , int32)
Definition at line 20 of file sscanf.c.
References _doscan(), sgetch(), and sungetch().
 {
     char *s;
     s = str;
     return (_doscan(fmt, (int **)&args, sgetch, sungetch, 0, (int)&s));
 }