XINU: lib/fgetc.c File Reference
fgetc.c File Reference
デバイス（ファイル）から文字を読み込む。
Macros
#define EOF (-2)
End Of Fileを示す値
Functions
int fgetc (int dev)
デバイス（ファイル）から文字を読み込む。
int getc (int)
Detailed Description
デバイス（ファイル）から文字を読み込む。
Definition in file fgetc.c.
Macro Definition Documentation
EOF
#define EOF (-2)
End Of Fileを示す値
Definition at line 9 of file fgetc.c.
Referenced by fgetc().
Function Documentation
fgetc()
int fgetc (int dev)
デバイス（ファイル）から文字を読み込む。
Parameters
[in] dev デバイスディスクリプタ
Returns
成功時は読み込んだ文字、異常時はEOFを返す。
Definition at line 17 of file fgetc.c.
References EOF, and getc().
Referenced by getchar().
 {
     int result = (int)getc(dev);
     if (0 > result)
     {
         return EOF;
     }
     else
     {
         return result;
     }
 }
getc()
int getc (int)
Definition at line 9 of file getc.c.
Referenced by fgetc().
 {
     intmask     mask;       /* Saved interrupt mask     */
     struct dentry   *devptr;    /* Entry in device switch table */
     int32       retval;     /* Value to return to caller    */
     mask = disable();
     if (isbaddev(descrp)) {
         restore(mask);
         return SYSERR;
     }
     devptr = (struct dentry *) &devtab[descrp];
     retval = (*devptr->dvgetc) (devptr);
     restore(mask);
     return retval;
 }