XINU: system/receive.c File Reference
receive.c File Reference
メッセージの受信を待ち、受信後にreceive()の呼び出し者にメッセージを返す。
#include <xinu.h>
Functions
umsg32 receive (void)
メッセージの受信を待ち、受信後にreceive()の呼び出し者にメッセージを返す。
Detailed Description
メッセージの受信を待ち、受信後にreceive()の呼び出し者にメッセージを返す。
Definition in file receive.c.
Function Documentation
receive()
umsg32 receive (void)
メッセージの受信を待ち、受信後にreceive()の呼び出し者にメッセージを返す。
Step1. 割り込みを禁止する。
Step2. 現在のプロセスが有効なメッセージを受信していない場合は受信待ち状態に移行し、
再スケジューリングを行う。
Step3. プロセスが復帰後、メッセージを取得し、メッセージフラグをリセットする。
Step4. 割り込み状態を復元する。
Returns
取得したメッセージを返す。
Definition at line 17 of file receive.c.
References currpid, disable(), FALSE, PR_RECV, procent::prhasmsg, procent::prmsg, proctab, procent::prstate, resched(), and restore().
Referenced by main(), rdscontrol(), rdsread(), and shell().
 {
     intmask mask;          /* Saved interrupt mask      */
     struct procent *prptr; /* Ptr to process's table entry  */
     umsg32 msg;            /* Message to return     */
     mask = disable();
     prptr = &proctab[currpid];
     if (prptr->prhasmsg == FALSE)
     {
         prptr->prstate = PR_RECV;
         resched(); /* Block until message arrives   */
     }
     msg = prptr->prmsg;      /* Retrieve message        */
     prptr->prhasmsg = FALSE; /* Reset message flag      */
     restore(mask);
     return msg;
 }