XINU: system/close.c File Reference
close.c File Reference
#include <xinu.h>
Functions
syscall close (did32 descrp)
Function Documentation
close()
syscall close (did32 descrp)
Definition at line 9 of file close.c.
References devtab, disable(), dentry::dvclose, isbaddev, restore(), and SYSERR.
Referenced by kill(), lfscreate(), xsh_cat(), and xsh_rdstest().
 {
     intmask     mask;       /* Saved interrupt mask     */
     struct  dentry  *devptr;    /* Entry in device switch table */
     int32       retval;     /* Value to return to caller    */
     mask = disable();
     if (isbaddev(descrp)) {
         restore(mask);
         return SYSERR;
     }
     devptr = (struct dentry *) &devtab[descrp];
     retval = (*devptr->dvclose) (devptr);
     restore(mask);
     return retval;
 }