XINU: device/tty/ttykickout.c File Reference
ttykickout.c File Reference
#include <xinu.h>
Functions
void ttykickout (struct uart_csreg *csrptr)
Function Documentation
ttykickout()
void ttykickout (struct uart_csreg * csrptr)
Definition at line 10 of file ttykickout.c.
References uart_csreg::ier, UART_IER_ERBFI, and UART_IER_ETBEI.
Referenced by eputc(), ttyhandle_in(), ttyinit(), and ttyputc().
 {
     /* Force the UART hardware generate an output interrupt */
     csrptr->ier = UART_IER_ERBFI | UART_IER_ETBEI;
     return;
 }