XINU: system/init.c File Reference
init.c File Reference
デバイスとデバイスドライバを初期化する。
#include <xinu.h>
Functions
syscall init (did32 descrp)
デバイスとデバイスドライバを初期化する。
Detailed Description
デバイスとデバイスドライバを初期化する。
Definition in file init.c.
Function Documentation
init()
syscall init (did32 descrp)
デバイスとデバイスドライバを初期化する。
Step1. 割り込みを禁止する。
Step2. デバイスディスクリプタが不正値の場合は、割り込み状態を復元し、処理を終了する。
Step3. デバイス固有の初期化処理を実施する。
Step4. 割り込み許可状態に復元する。
Parameters
[in] descrp デバイスディスクリプタ
Returns
成功時はデバイスに応じた返り値、デバイスディスクリプタが不正値の場合はSYSERRを返す。
Definition at line 17 of file init.c.
References devtab, disable(), dentry::dvinit, isbaddev, restore(), and SYSERR.
Referenced by sysinit().
 {
     intmask mask;          /* Saved interrupt mask      */
     struct dentry *devptr; /* Entry in device switch table  */
     int32 retval;          /* Value to return to caller */
     mask = disable();
     if (isbaddev(descrp))
     {
         restore(mask);
         return SYSERR;
     }
     devptr = (struct dentry *)&devtab[descrp];
     retval = (*devptr->dvinit)(devptr);
     restore(mask);
     return retval;
 }