XINU: device/rfs/rfsndmsg.c File Reference
rfsndmsg.c File Reference
#include <xinu.h>
Functions
status rfsndmsg (uint16 type, char *name)
Function Documentation
rfsndmsg()
status rfsndmsg (uint16 type, char * name)
Definition at line 9 of file rfsndmsg.c.
References htons, kprintf(), ntohl, OK, rfscomm(), SYSERR, and TIMEOUT.
Referenced by rfscontrol().
 {
     struct  rf_msg_hdr  req;    /* Request message to send  */
     struct  rf_msg_hdr resp;    /* Buffer for response      */
     int32   retval;         /* Return value         */
     char    *to;            /* Used during name copy    */
     /* Form a request */
     req.rf_type = htons(type);
     req.rf_status = htons(0);
     req.rf_seq = 0;         /* Rfscomm will set sequence    */
     to = req.rf_name;
     while ( (*to++ = *name++) ) {   /* Copy name to request     */
         ;
     }
     /* Send message and receive response */
     retval = rfscomm(&req,  sizeof(struct rf_msg_hdr),
              &resp, sizeof(struct rf_msg_hdr) );
     /* Check response */
     if (retval == SYSERR) {
         return SYSERR;
     } else if (retval == TIMEOUT) {
         kprintf("Timeout during remote file server access\n");
         return SYSERR;
     } else if (ntohl(resp.rf_status) != 0) {
         return SYSERR;
     }
     return OK;
 }