XINU: device/rds/rdsbufalloc.c File Reference
rdsbufalloc.c File Reference
#include <xinu.h>
Functions
struct rdbuff * rdsbufalloc (struct rdscblk *rdptr)
Function Documentation
rdsbufalloc()
struct rdbuff* rdsbufalloc (struct rdscblk * rdptr)
Definition at line 9 of file rdsbufalloc.c.
References NULL, panic(), rdscblk::rd_availsem, rdscblk::rd_chnext, rdscblk::rd_ctprev, rdscblk::rd_free, rdbuff::rd_next, rdbuff::rd_prev, rdbuff::rd_refcnt, SYSERR, and wait().
Referenced by rdscontrol(), rdsread(), and rdswrite().
 {
     struct  rdbuff  *bptr;      /* Pointer to a buffer      */
     struct  rdbuff  *pptr;      /* Pointer to previous buffer   */
     struct  rdbuff  *nptr;      /* Pointer to next buffer   */
     /* Wait for an available buffer */
     wait(rdptr->rd_availsem);
     /* If free list contains a buffer, extract it */
     bptr = rdptr->rd_free;
     if ( bptr != (struct rdbuff *)NULL ) {
         rdptr->rd_free = bptr->rd_next;
         return bptr;
     }
     /* Extract oldest item in cache that has ref count zero (at */
     /*   least one such entry must exist because the semaphore  */
     /*   had a nonzero count)                   */
     bptr = rdptr->rd_ctprev;
     while (bptr != (struct rdbuff *) &rdptr->rd_chnext) {
         if (bptr->rd_refcnt <= 0) {
             /* Remove from cache and return to caller */
             pptr = bptr->rd_prev;
             nptr = bptr->rd_next;
             pptr->rd_next = nptr;
             nptr->rd_prev = pptr;
             return bptr;
         }
         bptr = bptr->rd_prev;
     }
     panic("Remote disk cannot find an available buffer");
     return (struct rdbuff *)SYSERR;
 }