XINU: system/kill.c File Reference
kill.c File Reference
#include <xinu.h>
Functions
syscall kill (pid32 pid)
Function Documentation
kill()
syscall kill (pid32 pid)
Definition at line 9 of file kill.c.
References close(), disable(), freestk, getitem(), isbadpid, NULLPROC, OK, PR_CURR, PR_FREE, PR_READY, PR_RECTIM, PR_SLEEP, PR_WAIT, prcount, procent::prdesc, proctab, procent::prparent, procent::prsem, procent::prstate, procent::prstkbase, procent::prstklen, resched(), restore(), sentry::scount, semtab, send(), SYSERR, unsleep(), and xdone().
Referenced by exit(), userret(), and xsh_kill().
 {
     intmask mask;           /* Saved interrupt mask     */
     struct  procent *prptr;     /* Ptr to process's table entry */
     int32   i;          /* Index into descriptors   */
     mask = disable();
     if (isbadpid(pid) || (pid == NULLPROC)
         || ((prptr = &proctab[pid])->prstate) == PR_FREE) {
         restore(mask);
         return SYSERR;
     }
     if (--prcount <= 1) {       /* Last user process completes  */
         xdone();
     }
     send(prptr->prparent, pid);
     for (i=0; i<3; i++) {
         close(prptr->prdesc[i]);
     }
     freestk(prptr->prstkbase, prptr->prstklen);
     switch (prptr->prstate) {
     case PR_CURR:
         prptr->prstate = PR_FREE;   /* Suicide */
         resched();
     case PR_SLEEP:
     case PR_RECTIM:
         unsleep(pid);
         prptr->prstate = PR_FREE;
         break;
     case PR_WAIT:
         semtab[prptr->prsem].scount++;
         /* Fall through */
     case PR_READY:
         getitem(pid);       /* Remove from queue */
         /* Fall through */
     default:
         prptr->prstate = PR_FREE;
     }
     restore(mask);
     return OK;
 }