XINU: system/recvtime.c File Reference
recvtime.c File Reference
#include <xinu.h>
Functions
umsg32 recvtime (int32 maxwait)
Function Documentation
recvtime()
umsg32 recvtime (int32 maxwait)
Definition at line 9 of file recvtime.c.
References currpid, disable(), FALSE, insertd(), PR_RECTIM, procent::prhasmsg, procent::prmsg, proctab, procent::prstate, resched(), restore(), sleepq, SYSERR, and TIMEOUT.
Referenced by arp_resolve(), icmp_recv(), udp_recv(), and udp_recvaddr().
 {
     intmask mask;           /* Saved interrupt mask     */
     struct  procent *prptr;     /* Tbl entry of current process */
     umsg32  msg;            /* Message to return        */
     if (maxwait < 0) {
         return SYSERR;
     }
     mask = disable();
     /* Schedule wakeup and place process in timed-receive state */
     prptr = &proctab[currpid];
     if (prptr->prhasmsg == FALSE) { /* Delay if no message waiting  */
         if (insertd(currpid,sleepq,maxwait) == SYSERR) {
             restore(mask);
             return SYSERR;
         }
         prptr->prstate = PR_RECTIM;
         resched();
     }
     /* Either message arrived or timer expired */
     if (prptr->prhasmsg) {
         msg = prptr->prmsg; /* Retrieve message     */
         prptr->prhasmsg = FALSE;/* Reset message indicator  */
     } else {
         msg = TIMEOUT;
     }
     restore(mask);
     return msg;
 }