XINU: system/kprintf.c File Reference
kprintf.c File Reference
Kernel用のputc()、getc()、printf()を提供し、コンソールに対して文字のRead/Writeを行う。
#include <xinu.h>
#include <stdarg.h>
Functions
void _doprnt (char *, va_list, int(*)(int), int)
syscall kgetc (void)
ポーリングI/Oを使用して、コンソールのシリアルラインから文字を読み取る。
syscall kprintf (char *fmt,...)
Kernel用のprintf()であり、コンソールにフォーマットされた文字列を表示する。
syscall kputc (byte c)
ポーリングI/Oを使用して、コンソールのシリアルラインに文字を書き込む。
Detailed Description
Kernel用のputc()、getc()、printf()を提供し、コンソールに対して文字のRead/Writeを行う。
Definition in file kprintf.c.
Function Documentation
_doprnt()
void _doprnt (char * , va_list , int(*)(int) , int)
Referenced by kgetc(), and kprintf().
kgetc()
syscall kgetc (void)
ポーリングI/Oを使用して、コンソールのシリアルラインから文字を読み取る。
Definition at line 59 of file kprintf.c.
References _doprnt(), CONSOLE, devtab, disable(), dentry::dvcsr, uart_csreg::ier, uart_csreg::lsr, restore(), and UART_LSR_DR.
 {
     int irmask;
     volatile struct uart_csreg *regptr;
     byte c;
     struct dentry *devptr;
     intmask mask;
     /* Disable interrupts */
     mask = disable();
     devptr = (struct dentry *)&devtab[CONSOLE];
     regptr = (struct uart_csreg *)devptr->dvcsr;
     irmask = regptr->ier; /* Save UART interrupt state.   */
     regptr->ier = 0;      /* Disable UART interrupts.     */
     while (0 == (regptr->lsr & UART_LSR_DR))
     {
         ; /* Do Nothing */
     }
     /* Read character from Receive Holding Register */
     c = regptr->rbr;
     regptr->ier = irmask; /* Restore UART interrupts.     */
     restore(mask);
     return c;
 }
kprintf()
syscall kprintf (char * fmt, ...)
Kernel用のprintf()であり、コンソールにフォーマットされた文字列を表示する。
ポーリングI/Oを使用して、フォーマットされた文字列をコンソールに出力する。
Polled I/Oを使用したシステムコール。
Parameters
[in] fmt 文字列を表示する際のフォーマット情報
[in] ... 可変長引数
Definition at line 98 of file kprintf.c.
References _doprnt(), CONSOLE, devtab, kputc(), OK, va_end, and va_start.
Referenced by arp_alloc(), arp_dump(), arp_in(), dhcp_bld_req(), dnslookup(), ethinit(), ethread(), getlocalip(), hexadump(), hexdump(), ip_enqueue(), ip_in(), ipout(), irq_dispatch(), lflcontrol(), lfsckfmt(), lfsopen(), main(), naminit(), nulluser(), panic(), pdump(), pdumph(), rdscomm(), rdscontrol(), rdsopen(), rflread(), rflwrite(), rfscomm(), rfscontrol(), rfsndmsg(), rfsopen(), startup(), stop(), sysinit(), tftp_send1(), tftpget_mb(), xdone(), and xsh_rdstest().
 {
     va_list ap;
     va_start(ap, fmt);
     _doprnt(fmt, ap, (int (*)(int))kputc, (int)&devtab[CONSOLE]);
     va_end(ap);
     return OK;
 }
kputc()
syscall kputc (byte c)
ポーリングI/Oを使用して、コンソールのシリアルラインに文字を書き込む。
Definition at line 13 of file kprintf.c.
References uart_csreg::buffer, CONSOLE, devtab, disable(), dentry::dvcsr, uart_csreg::lsr, OK, restore(), and UART_LSR_THRE.
Referenced by kprintf().
 {
     struct dentry *devptr;
     volatile struct uart_csreg *csrptr;
     intmask mask;
     /* Disable interrupts */
     mask = disable();
     /* Get CSR address of the console */
     devptr = (struct dentry *)&devtab[CONSOLE];
     csrptr = (struct uart_csreg *)devptr->dvcsr;
     /* wait for UART transmit queue to empty */
     while ((csrptr->lsr & UART_LSR_THRE) == 0)
     {
         ;
     }
     /* write the character */
     csrptr->buffer = c;
     /* Honor CRLF - when writing NEWLINE also send CARRIAGE RETURN  */
     if (c == '\n')
     {
         while ((csrptr->lsr & UART_LSR_THRE) == 0)
         {
             ;
         }
         csrptr->buffer = '\r';
     }
     restore(mask);
     return OK;
 }