XINU: include/stdlib.h File Reference
stdlib.h File Reference
Macros
#define RAND_MAX 2147483646
Functions
int abs (int)
整数の絶対値（int型）を返す。
int atoi (char *)
ASCII文字列をint型に変換する。
long atol (char *)
ASCII文字列をlong型に変換する。
void bzero (void *, int)
Byteブロック領域の先頭N bytesを数値ゼロで埋める。
void free (void *pmem)
long labs (long)
実数（long型）の絶対値を返す。
void * malloc (unsigned int nbytes)
void qsort (char *, unsigned int, int, int(*)(void))
int rand (void)
予め設定済みのシード値を用いて、疑似乱数を返す。
void srand (unsigned int)
疑似乱数のシード値を設定する。
Detailed Description
Id
stdlib.h 2051 2009-08-27 20:55:09Z akoehler
Definition in file stdlib.h.
Macro Definition Documentation
RAND_MAX
#define RAND_MAX 2147483646
Definition at line 8 of file stdlib.h.
Referenced by rand_r().
Function Documentation
abs()
int abs (int arg)
整数の絶対値（int型）を返す。
Parameters
[in] arg 絶対値に変換したい整数（int型）
Returns
引数argの絶対値（int型）
Definition at line 13 of file abs.c.
 {
     if (arg < 0)
         arg = -arg;
     return (arg);
 }
atoi()
int atoi (char * p)
ASCII文字列をint型に変換する。
処理の流れは、
Step1. 「不要な文字（空白、TAB）の削除」もしくは「正数／負数の判定」を行う
Step2. 0〜9の範囲の値であれば、一桁ずつ記録する。それ以外の文字は呼び飛ばす
ASCIIコードとして、0=0x30、1=0x31、2=0x32、…、9=0x39であるため、
「0x30〜0x39の範囲のASCIIコード値(0〜9の値) - '0'(=0x30)」と計算すれば、
0〜9の整数値が得られる。
Step3. Step.1で取得した符号情報（±）を反映した整数を返す。
Parameters
[in] p ASCII文字列
Returns
ASCII文字列をint型に変換した整数値
Note
ASCIIコード情報は、ターミナル上で"$ man ascii"で確認できる。
Definition at line 19 of file atoi.c.
 {
     int n = 0, f = 0;
     for (;; p++)
     {
         switch (*p)
         {
         case ' ':
         case '\t':
             continue;
         case '-':
             f++;
         case '+':
             p++;
         }
         break;
     }
     while (*p >= '0' && *p <= '9')
     {
         n = n * 10 + *p++ - '0';
     }
     return (f ? -n : n);
 }
atol()
long atol (char * p)
ASCII文字列をlong型に変換する。
処理の流れは、
Step1. 「不要な文字（空白、TAB）の削除」もしくは「正数／負数の判定」を行う
Step2. 0〜9の範囲の値であれば、一桁ずつ記録する。それ以外の文字は呼び飛ばす
ASCIIコードとして、0=0x30、1=0x31、2=0x32、…、9=0x39であるため、
「0x30〜0x39の範囲のASCIIコード値(0〜9の値) - '0'(=0x30)」と計算すれば、
0〜9の整数値が得られる。
Step3. Step.1で取得した符号情報（±）を反映した整数を返す。
Parameters
[in] p ASCII文字列
Returns
ASCII文字列をlong型に変換した実数
Note
ASCIIコード情報は、ターミナル上で"$ man ascii"で確認できる。
Definition at line 19 of file atol.c.
 {
     long n;
     int f;
     n = 0;
     f = 0;
     for (;; p++)
     {
         switch (*p)
         {
         case ' ':
         case '\t':
             continue;
         case '-':
             f++;
         case '+':
             p++;
         }
         break;
     }
     while (*p >= '0' && *p <= '9')
     {
         n = n * 10 + *p++ - '0';
     }
     return (f ? -n : n);
 }
bzero()
void bzero (void * p, int len)
Byteブロック領域の先頭N bytesを数値ゼロで埋める。
Parameters
[in,out] p Byteブロック（bzero()終了後にゼロで埋まった状態となる）
[in] len 数値ゼロ埋めするサイズ（Byte）
Note
引数lenが0以下の場合は、何もせずreturnする。
Definition at line 12 of file bzero.c.
Referenced by newdev(), and newtype().
 {
     int n;
     char *pch = (char *)p;
     if ((n = len) <= 0)
     {
         return;
     }
     do
     {
         *pch++ = 0;
     } while (--n);
 }
free()
void free (void * pmem)
Referenced by if().
labs()
long labs (long arg)
実数（long型）の絶対値を返す。
Parameters
[in] arg 絶対値に変換したい実数（long型）
Returns
引数argの絶対値（long型）
Definition at line 11 of file labs.c.
 {
     if (arg < 0)
         arg = -arg;
     return (arg);
 }
malloc()
void* malloc (unsigned int nbytes)
Referenced by if().
qsort()
void qsort (char * , unsigned int, int , int(*)(void))
rand()
int rand (void)
予め設定済みのシード値を用いて、疑似乱数を返す。
シード値を変えない限り、疑似乱数に再現性がある。
Returns
疑似乱数（int型の整数値。0〜RAND_MAXの範囲で表される値）
Definition at line 17 of file rand.c.
References rand_r(), and rand_seed.
 {
     return rand_r(&rand_seed);
 }
srand()
void srand (unsigned int seed)
疑似乱数のシード値を設定する。
Parameters
[in] seed 疑似乱数のシード（乱数を生成する際に用いる値）
Definition at line 37 of file rand.c.
References rand_seed.
 {
     rand_seed = seed;
 }