XINU: system/recvclr.c File Reference
recvclr.c File Reference
#include <xinu.h>
Functions
umsg32 recvclr (void)
Function Documentation
recvclr()
umsg32 recvclr (void)
Definition at line 9 of file recvclr.c.
References currpid, disable(), FALSE, OK, procent::prhasmsg, procent::prmsg, proctab, restore(), and TRUE.
Referenced by arp_resolve(), icmp_recv(), main(), rdscontrol(), rdsread(), shell(), udp_recv(), and udp_recvaddr().
 {
     intmask mask;           /* Saved interrupt mask     */
     struct  procent *prptr;     /* Ptr to process's table entry */
     umsg32  msg;            /* Message to return        */
     mask = disable();
     prptr = &proctab[currpid];
     if (prptr->prhasmsg == TRUE) {
         msg = prptr->prmsg; /* Retrieve message     */
         prptr->prhasmsg = FALSE;/* Reset message flag       */
     } else {
         msg = OK;
     }
     restore(mask);
     return msg;
 }