XINU: device/tty/ttyputc.c File Reference
ttyputc.c File Reference
#include <xinu.h>
Functions
devcall ttyputc (struct dentry *devptr, char ch)
Function Documentation
ttyputc()
devcall ttyputc (struct dentry * devptr, char ch)
Definition at line 9 of file ttyputc.c.
References dentry::dvcsr, dentry::dvminor, OK, ttykickout(), ttytab, TY_NEWLINE, TY_OBUFLEN, TY_RETURN, ttycblk::tyobuff, ttycblk::tyocrlf, ttycblk::tyosem, ttycblk::tyotail, and wait().
Referenced by ttywrite().
 {
     struct  ttycblk *typtr;     /* Pointer to tty control block */
     typtr = &ttytab[devptr->dvminor];
     /* Handle output CRLF by sending CR first */
         if ( ch==TY_NEWLINE && typtr->tyocrlf ) {
                 ttyputc(devptr, TY_RETURN);
     }
     wait(typtr->tyosem);        /* Wait for space in queue */
     *typtr->tyotail++ = ch;
     /* Wrap around to beginning of buffer, if needed */
     if (typtr->tyotail >= &typtr->tyobuff[TY_OBUFLEN]) {
         typtr->tyotail = typtr->tyobuff;
     }
     /* Start output in case device is idle */
     ttykickout((struct uart_csreg *)devptr->dvcsr);
     return OK;
 }