XINU: system/initialize.c File Reference
initialize.c File Reference
システムの初期化を処理し、nullプロセスとなる。
#include <xinu.h>
#include <string.h>
Macros
#define CONSOLE_RESET " \033[0m\033[2J\033[;H"
コンソール（コンソールカラー、文字、ポジション）をリセットするためのエスケープシーケンス
Functions
int32 delay (int n)
マイクロ秒単位で処理を遅らせる。
void main (void)
最初に生成されるmainプロセスのextern宣言
void meminit (void)
フリーメモリリストを初期化するmeminit()のextern宣言
void nulluser ()
システムの初期化を処理し、nullプロセスとなる。
void start (void)
XINUコードの開始であるstart()のextern宣言
local process startup (void)
スタートアップタスクを完了するプロセス
int32 stop (char *s)
処理を停止させる。無限ループによる停止のため、復帰にはリセットが必要である。
static void sysinit ()
内部システムの初期化を行うsysinit()のextern宣言
Variables
void * _end
XINUコードの終わり
pid32 currpid
現在実行中のプロセスのID
struct memblk memlist
フリーメモリブロックのリスト
int prcount
生存しているプロセスの総数
struct procent proctab [NPROC]
プロセステーブルエントリ
struct sentry semtab [NSEM]
セマフォテーブルエントリ
Detailed Description
システムの初期化を処理し、nullプロセスとなる。
Definition in file initialize.c.
Macro Definition Documentation
CONSOLE_RESET
#define CONSOLE_RESET " \033[0m\033[2J\033[;H"
コンソール（コンソールカラー、文字、ポジション）をリセットするためのエスケープシーケンス
Definition at line 34 of file initialize.c.
Referenced by sysinit().
Function Documentation
delay()
int32 delay (int n)
マイクロ秒単位で処理を遅らせる。
Parameters
[in] n 遅延時間（マイクロ秒）
Returns
OKを返す。
Definition at line 262 of file initialize.c.
References DELAY, and OK.
Referenced by xsh_sleep(), and xsh_udpecho().
 {
     DELAY(n);
     return OK;
 }
main()
void main (void)
最初に生成されるmainプロセスのextern宣言
最初に生成されるmainプロセスのextern宣言
Step1. メッセージを全て受信する（ただし、メッセージ内容は確認しない）。
Step2. XINUシェルを作成／起動する。
Step3. XINUシェルが終了した場合は、以下の処理を行う（無限に繰り返す）。
・メッセージ到着を待つ。メッセージが来なければ、待ち続ける。
・200[ms]スリープする。
・XINUシェルを再作成／起動する。
Returns
OKを返す。
Definition at line 18 of file main.c.
References CONSOLE, create(), kprintf(), OK, receive(), recvclr(), resume(), shell(), sleepms(), and TRUE.
Referenced by startup().
 {
     /* Run the Xinu shell */
     recvclr();
     resume(create(shell, 8192, 50, "shell", 1, CONSOLE));
     /* Wait for shell to exit and recreate it */
     while (TRUE)
     {
         receive();
         sleepms(200);
         kprintf("\n\nMain process recreating shell\n\n");
         resume(create(shell, 4096, 20, "shell", 1, CONSOLE));
     }
     return OK;
 }
meminit()
void meminit (void)
フリーメモリリストを初期化するmeminit()のextern宣言
フリーメモリリストを初期化するmeminit()のextern宣言
Step1. ヒープ開始アドレスとヒープ終了アドレスを設定する。
Step2. メモリリストの先頭に、ヒープ開始から終了までのメモリブロックをセットする。
Note
RAMサイズは512MB。
Definition at line 19 of file meminit.c.
References end, MAXADDR, maxheap, memlist, minheap, memblk::mlength, memblk::mnext, and NULL.
Referenced by sysinit().
 {
     struct memblk *memptr; /* Memory block pointer  */
     /* Initialize the minheap and maxheap variables */
     minheap = (void *)&end;
     maxheap = (void *)MAXADDR;
     /* Initialize the memory list as one big block */
     memlist.mnext = (struct memblk *)minheap;
     memptr = memlist.mnext;
     memptr->mnext = (struct memblk *)NULL;
     memlist.mlength = memptr->mlength =
         (uint32)maxheap - (uint32)minheap;
 }
nulluser()
void nulluser ()
システムの初期化を処理し、nullプロセスとなる。
Step1. XINUデータ構造とデバイスを初期化する。
Step2. XINUシステムのメモリレイアウトを出力する。
Step3. 割り込みを許可状態にする。
Step4. ネットワークデータ構造およびネットワーク関連プロセスを初期化する。
Step5. スタートアップ（初期化）終了プロセスを呼び出し、その中でmainプロセスを呼び出す。
Step6. 本関数はnullプロセスとなる。つまり、他のプロセスを実行する準備ができていない時、
CPUを実行するプロセス（nullプロセス）がある事を保証する。
Note
Cランタイム環境が確立された後に、プログラムの実行は本関数から開始される。
割り込みは最初は無効であり、最終的には明示的に有効にする必要がある。
本関数は、初期化完了後にnullプロセスとなる。nullプロセスは常に実行可能な状態を
維持する必要がある。そのため、中断、セマフォの待機、スリープ状態、または終了を
引き起こす可能性のあるコードを実行できない。特に、コードはkprintfなどのポーリング版を
除いて、I/Oを実行してはならない。
Definition at line 53 of file initialize.c.
References create(), data, ebss, enable(), etext, INITPRIO, INITSTK, kprintf(), memlist, memblk::mlength, memblk::mnext, net_init(), NULL, resume(), startup(), sysinit(), text, and TRUE.
 {
     struct memblk *memptr; /* Ptr to memory block       */
     uint32 free_mem;       /* Total amount of free memory   */
     /* Initialize the system */
     sysinit();
     /* Output Xinu memory layout */
     free_mem = 0;
     for (memptr = memlist.mnext; memptr != NULL;
          memptr = memptr->mnext)
     {
         free_mem += memptr->mlength;
     }
     kprintf("%10d bytes of free memory.  Free list:\n", free_mem);
     for (memptr = memlist.mnext; memptr != NULL; memptr = memptr->mnext)
     {
         kprintf("           [0x%08X to 0x%08X]\n",
                 (uint32)memptr, ((uint32)memptr) + memptr->mlength - 1);
     }
     kprintf("%10d bytes of Xinu code.\n",
             (uint32)&etext - (uint32)&text);
     kprintf("           [0x%08X to 0x%08X]\n",
             (uint32)&text, (uint32)&etext - 1);
     kprintf("%10d bytes of data.\n",
             (uint32)&ebss - (uint32)&data);
     kprintf("           [0x%08X to 0x%08X]\n\n",
             (uint32)&data, (uint32)&ebss - 1);
     /* Enable interrupts */
     enable();
     /* Initialize the network stack and start processes */
     net_init();
     /* Create a process to finish startup and start main */
     resume(create((void *)startup, INITSTK, INITPRIO,
                   "Startup process", 0, NULL));
     /* Become the Null process (i.e., guarantee that the CPU has    */
     /*  something to run when no other process is ready to execute) */
     while (TRUE)
     {
         ; /* Do nothing */
     }
 }
start()
void start (void)
XINUコードの開始であるstart()のextern宣言
startup()
local process startup (void)
スタートアップタスクを完了するプロセス
nullプロセスから実行できないスタートアップ処理（初期化処理）を行い、mainプロセスを作成／実行する。
Step1. DHCPを使用してIPアドレスを取得／表示する。
Step2. mainプロセスを作成し、実行する。
Returns
OKを返す。
Definition at line 114 of file initialize.c.
References create(), getlocalip(), INITPRIO, INITSTK, network::ipucast, kprintf(), main(), NetData, NULL, OK, resume(), sprintf(), and SYSERR.
Referenced by nulluser().
 {
     uint32 ipaddr; /* Computer's IP address */
     char str[128]; /* String used to format output  */
     /* Use DHCP to obtain an IP address and format it */
     ipaddr = getlocalip();
     if ((int32)ipaddr == SYSERR)
     {
         kprintf("Cannot obtain an IP address\n");
     }
     else
     {
         /* Print the IP in dotted decimal and hex */
         ipaddr = NetData.ipucast;
         sprintf(str, "%d.%d.%d.%d",
                 (ipaddr >> 24) & 0xff, (ipaddr >> 16) & 0xff,
                 (ipaddr >> 8) & 0xff, ipaddr & 0xff);
         kprintf("Obtained IP address  %s   (0x%08x)\n", str,
                 ipaddr);
     }
     /* Create a process to execute function main() */
     resume(create((void *)main, INITSTK, INITPRIO,
                   "Main process", 0, NULL));
     /* Startup process exits at this point */
     return OK;
 }
stop()
int32 stop (char * s)
処理を停止させる。無限ループによる停止のため、復帰にはリセットが必要である。
Parameters
[in] s 停止時に表示するメッセージ
Definition at line 249 of file initialize.c.
References kprintf().
Referenced by xsh_memdump().
 {
     kprintf("%s\n", s);
     kprintf("looping... press reset\n");
     while (1)
         /* Empty */;
 }
sysinit()
static void sysinit () static
内部システムの初期化を行うsysinit()のextern宣言
XINUデータ構造とデバイスを初期化する。
Step1. コンソールリセットを行う。
Step2. プラットフォーム固有の初期化を行う。
Step3. 割り込みベクタを初期化する。
Step4. フリーメモリリストを初期化する。
Step5. プロセス総数を記録する（nullプロセス分のみ記録するため、1となる）。
Step6. スケジューリングの延期（Defer）状態をリセットする。
Step7. プロセステーブルエントリ（nullプロセス分も含む）を初期化する。
Step8. セマフォテーブルを初期化する。
Step9. バッファプールを初期化する。
Step10. プロセスのREADYリストを作成する。
Step11. リアルタイムクロックを初期化する。
Step12. デバイスとデバイスドライバを初期化する。
Definition at line 163 of file initialize.c.
References bufinit(), clkinit(), CONSOLE_RESET, currpid, Defer, getstk(), init(), initevec(), kprintf(), meminit(), defer::ndefers, NDEVS, newqueue(), NPROC, NSEM, NULL, NULLCH, NULLPROC, NULLSTK, platinit(), PR_CURR, PR_FREE, prcount, procent::prname, proctab, procent::prprio, procent::prstate, procent::prstkbase, procent::prstklen, procent::prstkptr, readylist, S_FREE, sentry::scount, semtab, sentry::squeue, sentry::sstate, and strncpy().
Referenced by nulluser().
 {
     int32 i;
     struct procent *prptr; /* Ptr to process table entry    */
     struct sentry *semptr; /* Ptr to semaphore table entry  */
     kprintf(CONSOLE_RESET);
     kprintf("\n%s\n\n", VERSION);
     /* Platform Specific Initialization */
     platinit();
     /* Initialize the interrupt vectors */
     initevec();
     /* Initialize free memory list */
     meminit();
     /* Initialize system variables */
     /* Count the Null process as the first process in the system */
     prcount = 1;
     /* Scheduling is not currently blocked */
     Defer.ndefers = 0;
     /* Initialize process table entries free */
     for (i = 0; i < NPROC; i++)
     {
         prptr = &proctab[i];
         prptr->prstate = PR_FREE;
         prptr->prname[0] = NULLCH;
         prptr->prstkbase = NULL;
         prptr->prprio = 0;
     }
     /* Initialize the Null process entry */
     prptr = &proctab[NULLPROC];
     prptr->prstate = PR_CURR;
     prptr->prprio = 0;
     strncpy(prptr->prname, "prnull", 7);
     prptr->prstkbase = getstk(NULLSTK);
     prptr->prstklen = NULLSTK;
     prptr->prstkptr = 0;
     currpid = NULLPROC;
     /* Initialize semaphores */
     for (i = 0; i < NSEM; i++)
     {
         semptr = &semtab[i];
         semptr->sstate = S_FREE;
         semptr->scount = 0;
         semptr->squeue = newqueue();
     }
     /* Initialize buffer pools */
     bufinit();
     /* Create a ready list for processes */
     readylist = newqueue();
     /* Initialize the real time clock */
     clkinit();
     for (i = 0; i < NDEVS; i++)
     {
         init(i);
     }
     return;
 }
Variable Documentation
_end
void* _end
XINUコードの終わり
currpid
pid32 currpid
現在実行中のプロセスのID
現在実行中のプロセス。
Definition at line 32 of file initialize.c.
Referenced by arp_resolve(), dnslookup(), getpid(), icmp_recv(), irq_dispatch(), receive(), recvclr(), recvtime(), resched(), sleepms(), sysinit(), udp_recv(), udp_recvaddr(), and wait().
memlist
struct memblk memlist
フリーメモリブロックのリスト
フリーメモリリストの先頭
Definition at line 27 of file initialize.c.
Referenced by freemem(), getmem(), getstk(), meminit(), nulluser(), printFreeList(), and printMemUse().
prcount
int prcount
生存しているプロセスの総数
現在アクティブのプロセス。
Definition at line 30 of file initialize.c.
Referenced by create(), kill(), and sysinit().
proctab
struct procent proctab[NPROC]
プロセステーブルエントリ
プロセステーブル。
Definition at line 23 of file initialize.c.
Referenced by addargs(), chprio(), create(), getprio(), irq_dispatch(), kill(), newpid(), printMemUse(), ready(), receive(), recvclr(), recvtime(), resched(), resume(), send(), shell(), sleepms(), suspend(), sysinit(), unsleep(), wait(), and xsh_ps().
semtab
struct sentry semtab[NSEM]
セマフォテーブルエントリ
セマフォテーブルエントリのextern宣言
Definition at line 25 of file initialize.c.
Referenced by kill(), newsem(), semcount(), semcreate(), semdelete(), semreset(), signal(), signaln(), sysinit(), and wait().