XINU: system/semcount.c File Reference
semcount.c File Reference
セマフォのカウント値を返す。
#include <xinu.h>
Functions
syscall semcount (sid32 semid)
セマフォのカウント値を返す。
Detailed Description
セマフォのカウント値を返す。
Definition in file semcount.c.
Function Documentation
semcount()
syscall semcount (sid32 semid)
セマフォのカウント値を返す。
Step1. 割り込みを禁止する。
Step2. 「セマフォIDが不正値」か「セマフォがFREE状態」の場合、割り込み許可状態に復元して、処理を終了する。
Step3. 引数で渡されたセマフォIDを基に、セマフォテーブルからセマフォのカウント値を取得する。
Step4. 割り込み許可状態に復元する。
Parameters
[in] semid セマフォカウンタを確認したいセマフォのID
Returns
成功時はセマフォのカウント値、「不正なセマフォID」や「セマフォがFREE状態の場合はSYSERR」を返す。
Note
セマフォカウンタ値が整数値（正負問わず）のため、SYSERR（-1）と同じ値になる可能性がある。
Definition at line 18 of file semcount.c.
References disable(), isbadsem, restore(), S_FREE, sentry::scount, semtab, and SYSERR.
Referenced by ethhandler(), ip_enqueue(), ptcount(), rdswrite(), ttycontrol(), ttyhandle_in(), ttyhandle_out(), and ttyread().
 {
     intmask mask; /* Saved interrupt mask       */
     int32 count;  /* Current sempahore count    */
     mask = disable();
     if (isbadsem(semid) || semtab[semid].sstate == S_FREE)
     {
         restore(mask);
         return SYSERR;
     }
     count = semtab[semid].scount;
     restore(mask);
     return count;
 }