XINU: lib/strncpy.c File Reference
strncpy.c File Reference
文字列s1に文字列s2をN文字（Byte）分コピーする。
Functions
char * strncpy (char *s1, const char *s2, int n)
文字列s1に文字列s2をN文字（Byte）分コピーする。
Detailed Description
文字列s1に文字列s2をN文字（Byte）分コピーする。
Definition in file strncpy.c.
Function Documentation
strncpy()
char* strncpy (char * s1, const char * s2, int n)
文字列s1に文字列s2をN文字（Byte）分コピーする。
自動でNULL終端（'\0'）は付与しない。
また、N Byteコピーする前にNULL終端に達した場合、残りのByte数分をNULL終端で埋める。
Parameters
[in,out] s1 コピー先の文字列
[in] s2 コピー元の文字列
[in] n コピーする文字数（Byte）
Returns
コピー後の文字列s1を返す。
Definition at line 15 of file strncpy.c.
Referenced by newtype(), sysinit(), and tftpget_mb().
 {
     register int i;
     register char *os1;
     os1 = s1;
     for (i = 0; i < n; i++)
     {
         if (((*s1++) = (*s2++)) == '\0')
         {
             while (++i < n)
             {
                 *s1++ = '\0';
             }
             return os1;
         }
     }
     return os1;
 }