XINU: device/rds/rdsinit.c File Reference
rdsinit.c File Reference
リモートディスクシステムデバイスを初期化する。
#include <xinu.h>
Functions
devcall rdsinit (struct dentry *devptr)
Variables
struct rdscblk rdstab [Nrds]
Detailed Description
リモートディスクシステムデバイスを初期化する。
Definition in file rdsinit.c.
Function Documentation
rdsinit()
devcall rdsinit (struct dentry * devptr)
Definition at line 17 of file rdsinit.c.
References create(), dot2ip(), dentry::dvminor, FALSE, getmem(), NULL, NULLCH, OK, panic(), rdscblk::rd_availsem, RD_BUFFS, rdscblk::rd_chnext, rdscblk::rd_chprev, rdscblk::rd_comproc, rdscblk::rd_comruns, rdscblk::rd_ctnext, rdscblk::rd_ctprev, RD_FREE, rdscblk::rd_free, rdscblk::rd_id, RD_INVALID, RD_LOC_PORT, rdscblk::rd_loc_port, rdbuff::rd_next, RD_PRIO, rdscblk::rd_registered, rdscblk::rd_reqsem, rdscblk::rd_rhnext, rdscblk::rd_rhprev, rdscblk::rd_rtnext, rdscblk::rd_rtprev, rdscblk::rd_seq, rdscblk::rd_ser_ip, rdscblk::rd_ser_port, RD_SERVER_IP, RD_SERVER_PORT, RD_STACK, rdscblk::rd_state, rdbuff::rd_status, rdsprocess(), rdstab, semcreate(), and SYSERR.
 {
     struct rdscblk *rdptr; /* Ptr to device contol block    */
     struct rdbuff *bptr;   /* Ptr to buffer in memory   */
     /*   used to form linked list   */
     struct rdbuff *pptr;    /* Ptr to previous buff on list */
     struct rdbuff *buffend; /* Last address in buffer memory*/
     uint32 size;            /* Total size of memory needed  */
     /*   buffers            */
     /* Obtain address of control block */
     rdptr = &rdstab[devptr->dvminor];
     /* Set control block to unused */
     rdptr->rd_state = RD_FREE;
     /* Create the resprocess and leave it suspended.    */
     /*  Note: the process cannot be resumed because */
     /*  device initialization occurs before interrupts  */
     /*  are enabled.                    */
     rdptr->rd_comproc = create(rdsprocess, RD_STACK, RD_PRIO,
                                "rdsproc", 1, rdptr);
     if (rdptr->rd_comproc == SYSERR)
     {
         panic("Cannot create remote disk process");
     }
     rdptr->rd_comruns = FALSE;
     rdptr->rd_id[0] = NULLCH;
     /* Set initial message sequence number */
     rdptr->rd_seq = 1;
     /* Initialize request queue and cache to empty */
     rdptr->rd_rhnext = (struct rdbuff *)&rdptr->rd_rtnext;
     rdptr->rd_rhprev = (struct rdbuff *)NULL;
     rdptr->rd_rtnext = (struct rdbuff *)NULL;
     rdptr->rd_rtprev = (struct rdbuff *)&rdptr->rd_rhnext;
     rdptr->rd_chnext = (struct rdbuff *)&rdptr->rd_ctnext;
     rdptr->rd_chprev = (struct rdbuff *)NULL;
     rdptr->rd_ctnext = (struct rdbuff *)NULL;
     rdptr->rd_ctprev = (struct rdbuff *)&rdptr->rd_chnext;
     /* Allocate memory for a set of buffers (actually request   */
     /*    blocks and link them to form the initial free list    */
     size = sizeof(struct rdbuff) * RD_BUFFS;
     bptr = (struct rdbuff *)getmem(size);
     rdptr->rd_free = bptr;
     if ((int32)bptr == SYSERR)
     {
         panic("Cannot allocate memory for remote disk buffers");
     }
     pptr = (struct rdbuff *)NULL; /* To avoid a compiler warning    */
     buffend = (struct rdbuff *)((char *)bptr + size);
     while (bptr < buffend)
     { /* walk through memory */
         pptr = bptr;
         bptr = (struct rdbuff *)(sizeof(struct rdbuff) + (char *)bptr);
         pptr->rd_status = RD_INVALID; /* Buffer is empty    */
         pptr->rd_next = bptr;         /* Point to next buffer */
     }
     pptr->rd_next = (struct rdbuff *)NULL; /* Last buffer on list   */
     /* Create the request list and available buffer semaphores */
     rdptr->rd_availsem = semcreate(RD_BUFFS);
     rdptr->rd_reqsem = semcreate(0);
     /* Set the server IP address, server port, and local port */
     if (dot2ip(RD_SERVER_IP, &rdptr->rd_ser_ip) == SYSERR)
     {
         panic("invalid IP address for remote disk server");
     }
     /* Set the port numbers */
     rdptr->rd_ser_port = RD_SERVER_PORT;
     rdptr->rd_loc_port = RD_LOC_PORT + devptr->dvminor;
     /* Specify that the server port is not yet registered */
     rdptr->rd_registered = FALSE;
     return OK;
 }
Variable Documentation
rdstab
struct rdscblk rdstab[Nrds]
Definition at line 11 of file rdsinit.c.
Referenced by rdsclose(), rdscontrol(), rdsinit(), rdsopen(), rdsread(), and rdswrite().