XINU: device/nam/namopen.c File Reference
namopen.c File Reference
#include <xinu.h>
Functions
devcall namopen (struct dentry *devptr, char *name, char *mode)
Function Documentation
namopen()
devcall namopen (struct dentry * devptr, char * name, char * mode)
Definition at line 9 of file namopen.c.
References dentry::dvnum, nammap(), newdev(), NM_MAXLEN, open(), and SYSERR.
 {
     char    newname[NM_MAXLEN]; /* Name with prefix replaced    */
     did32   newdev;         /* Device ID after mapping  */
     /* Use namespace to map name to a new name and new descriptor */
     newdev = nammap(name, newname, devptr->dvnum);
     if (newdev == SYSERR) {
         return SYSERR;
     }
     /* Open underlying device and return status */
     return  open(newdev, newname, mode);
 }