XINU: device/lfs/lfdballoc.c File Reference
lfdballoc.c File Reference
ディスク上の空きリストから新しいデータブロック割当を行う。
#include <xinu.h>
Macros
#define DFILL '+' /* character used to fill a disk block */
Functions
dbid32 lfdballoc (struct lfdbfree *dbuff)
Detailed Description
ディスク上の空きリストから新しいデータブロック割当を行う。
Definition in file lfdballoc.c.
Macro Definition Documentation
DFILL
#define DFILL '+' /* character used to fill a disk block */
Definition at line 12 of file lfdballoc.c.
Referenced by lfdballoc().
Function Documentation
lfdballoc()
dbid32 lfdballoc (struct lfdbfree * dbuff)
Definition at line 19 of file lfdballoc.c.
References DFILL, FALSE, LF_AREA_DIR, LF_BLKSIZ, Lf_data, lfdata::lf_dir, lfdata::lf_dirdirty, LF_DNULL, lfdata::lf_dskdev, lfdir::lfd_dfree, memset(), panic(), read(), SYSERR, and write().
Referenced by lfsetup().
 {
     dbid32 dnum;  /* ID of next d-block on the free list    */
     int32 retval; /* Return value               */
     /* Get the ID of first data block on the free list */
     dnum = Lf_data.lf_dir.lfd_dfree;
     if (dnum == LF_DNULL)
     { /* Ran out of free data blocks */
         panic("out of data blocks");
     }
     retval = read(Lf_data.lf_dskdev, (char *)dbuff, dnum);
     if (retval == SYSERR)
     {
         panic("lfdballoc cannot read disk block\n\r");
     }
     /* Unlink d-block from in-memory directory */
     Lf_data.lf_dir.lfd_dfree = dbuff->lf_nextdb;
     write(Lf_data.lf_dskdev, (char *)&Lf_data.lf_dir, LF_AREA_DIR);
     Lf_data.lf_dirdirty = FALSE;
     /* Fill data block to erase old data */
     memset((char *)dbuff, DFILL, LF_BLKSIZ);
     return dnum;
 }