XINU: system/mark.c File Reference
mark.c File Reference
#include <xinu.h>
Functions
status mark (int32 *loc)
void markinit (void)
Variables
int32 * marks [MAXMARK]
sid32 mkmutex
int32 nmarks
Function Documentation
mark()
status mark (int32 * loc)
Definition at line 24 of file mark.c.
References marks, MAXMARK, mkmutex, nmarks, OK, signal(), SYSERR, and wait().
 {
     /* If location is already marked, do nothing */
     if ( (*loc>=0) && (*loc<nmarks) && (marks[*loc]==loc) ) {
         return OK;
     }
     /* If no more memory marks are available, indicate an error */
     if (nmarks >= MAXMARK) {
         return SYSERR;
     }
     /* Obtain exclusive access and mark the specified location */
     wait(mkmutex);
     marks[ (*loc) = nmarks++ ] = loc;
     signal(mkmutex);
     return OK;
 }
markinit()
void markinit (void)
Definition at line 13 of file mark.c.
References mkmutex, nmarks, and semcreate().
 {
     nmarks = 0;
     mkmutex = semcreate(1);
 }
Variable Documentation
marks
int32* marks[MAXMARK]
Definition at line 5 of file mark.c.
Referenced by mark().
mkmutex
sid32 mkmutex
Definition at line 7 of file mark.c.
Referenced by mark(), and markinit().
nmarks
int32 nmarks
Definition at line 6 of file mark.c.
Referenced by mark(), and markinit().