XINU: lib/fscanf.c File Reference
fscanf.c File Reference
Macros
#define EMPTY (-1)
#define EOF (-2)
Functions
int _doscan (register char *, register int **, int(*getc)(int, int), int(*ungetc)(int, int), int, int)
int fscanf (int dev, char *fmt, int args)
int getc (int)
static int getch (int, int)
static int ungetch (int, int)
Macro Definition Documentation
EMPTY
#define EMPTY (-1)
Definition at line 4 of file fscanf.c.
Referenced by fscanf(), getch(), and ungetch().
EOF
#define EOF (-2)
Definition at line 7 of file fscanf.c.
Referenced by getch().
Function Documentation
_doscan()
int _doscan (register char * , register int ** , int(*)(int, int) getc, int(*)(int, int) ungetc, int , int)
Definition at line 38 of file doscan.c.
References _getccl(), _innum(), EOF, getch(), isdigit, isupper, LONG, REGULAR, SHORT, tolower, and ungetch().
Referenced by fscanf().
 {
     register int ch;
     int nmatch, len, ch1;
     int **ptr, fileended, size;
     nmatch = 0;
     fileended = 0;
     for (;;)
     {
         switch (ch = *fmt++)
         {
         case '\0':
             return (nmatch);
         case '%':
             if ((ch = *fmt++) == '%')
             {
                 goto def;
             }
             ptr = 0;
             if (ch != '*')
             {
                 ptr = argp++;
             }
             else
             {
                 ch = *fmt++;
             }
             len = 0;
             size = REGULAR;
             while (isdigit(ch))
             {
                 len = len * 10 + ch - '0';
                 ch = *fmt++;
             }
             if (len == 0)
             {
                 len = 30000;
             }
             if (ch == 'l')
             {
                 ch = *fmt++;
                 size = LONG;
             }
             else if (ch == 'h')
             {
                 size = SHORT;
                 ch = *fmt++;
             }
             else if (ch == '[')
             {
                 fmt = _getccl(fmt);
             }
             if (isupper(ch))
             {
                 ch = tolower(ch);
                 size = LONG;
             }
             if (ch == '\0')
             {
                 return (-1);
             }
             if (_innum
                 (ptr, ch, len, size,
                  getch, ungetch, arg1, arg2, &fileended) && ptr)
             {
                 nmatch++;
             }
             if (fileended)
             {
                 return (nmatch ? nmatch : -1);
             }
             break;
         case ' ':
         case '\n':
         case '\t':
             while ((ch1 =
                     (*getch) (arg1,
                               arg2)) == ' ' || ch1 == '\t' || ch1 == '\n')
             {;
             }
             if (ch1 != EOF)
             {
                 (*ungetch) (arg1, arg2);
             }
             break;
         default:
           def:
             ch1 = (*getch) (arg1, arg2);
             if (ch1 != ch)
             {
                 if (ch1 == EOF)
                 {
                     return (-1);
                 }
                 (*ungetch) (arg1, arg2);
                 return nmatch;
             }
         }
     }
 }
fscanf()
int fscanf (int dev, char * fmt, int args)
Definition at line 23 of file fscanf.c.
References _doscan(), EMPTY, getch(), and ungetch().
 {
     int buf;
     buf = EMPTY;
     return (_doscan
             (fmt, (int **)&args, getch, ungetch, dev, (int)(int)&buf));
 }
getc()
int getc (int)
Definition at line 9 of file getc.c.
References devtab, disable(), dentry::dvgetc, isbaddev, restore(), and SYSERR.
Referenced by getch().
 {
     intmask     mask;       /* Saved interrupt mask     */
     struct dentry   *devptr;    /* Entry in device switch table */
     int32       retval;     /* Value to return to caller    */
     mask = disable();
     if (isbaddev(descrp)) {
         restore(mask);
         return SYSERR;
     }
     devptr = (struct dentry *) &devtab[descrp];
     retval = (*devptr->dvgetc) (devptr);
     restore(mask);
     return retval;
 }
getch()
static int getch (int dev, int abuf) static
Definition at line 40 of file fscanf.c.
References EMPTY, EOF, and getc().
Referenced by _doscan(), _innum(), _instr(), and fscanf().
 {
     int *buf = (int *)abuf;
     if (*buf != EOF && *buf != EMPTY)
     {
         *buf = getc(dev);
     }
 /*  if( *buf != EOF ) */
 /*  { *buf = control(dev, TTY_IOC_NEXTC, 0, 0); } */
     return (*buf);
 }
ungetch()
static int ungetch (int dev, int abuf) static
Definition at line 60 of file fscanf.c.
References EMPTY.
Referenced by _doscan(), _innum(), and fscanf().
 {
     int *buf = (int *)abuf;
     *buf = EMPTY;
     return (*buf);
 }