XINU: system/queue.c File Reference
queue.c File Reference
キュー操作API（キューの追加、キューの削除）を提供する。
#include <xinu.h>
Functions
pid32 dequeue (qid16 q)
プロセスキューテーブルからキューを削除し、リスト先頭のプロセスIDを返す。
pid32 enqueue (pid32 pid, qid16 q)
プロセスをプロセスキューテーブルの末尾に挿入する。
Variables
struct qentry queuetab [NQENT]
Detailed Description
キュー操作API（キューの追加、キューの削除）を提供する。
Note
プロセスキューテーブルは、リストとも呼ばれる。
Definition in file queue.c.
Function Documentation
dequeue()
pid32 dequeue (qid16 q)
プロセスキューテーブルからキューを削除し、リスト先頭のプロセスIDを返す。
Parameters
[in] q 使用するキューID
Returns
キューを削除した場合はリスト先頭のプロセスID、キューIDが不正の場合はSYSERR、
キューが空の場合はEMPTYを返す。
Definition at line 78 of file queue.c.
References EMPTY, getfirst(), isbadqid, isempty, qentry::qnext, qentry::qprev, queuetab, and SYSERR.
Referenced by resched(), signal(), signaln(), and wakeup().
 {
     pid32 pid; /* ID of process removed */
     if (isbadqid(q))
     {
         return SYSERR;
     }
     else if (isempty(q))
     {
         return EMPTY;
     }
     pid = getfirst(q);
     queuetab[pid].qprev = EMPTY;
     queuetab[pid].qnext = EMPTY;
     return pid;
 }
enqueue()
pid32 enqueue (pid32 pid, qid16 q)
プロセスをプロセスキューテーブルの末尾に挿入する。
Parameters
[in] pid 挿入するプロセスID
[in] q 使用するキューID
Returns
成功時はキューに挿入したプロセスID、引数不正時はSYSERRを返す。
Definition at line 53 of file queue.c.
References isbadpid, isbadqid, qentry::qnext, qentry::qprev, queuetab, queuetail, and SYSERR.
Referenced by wait().
 {
     qid16 tail, prev; /* Tail & previous node indexes   */
     if (isbadqid(q) || isbadpid(pid))
     {
         return SYSERR;
     }
     tail = queuetail(q);
     prev = queuetab[tail].qprev;
     queuetab[pid].qnext = tail; /* Insert just before tail node */
     queuetab[pid].qprev = prev;
     queuetab[prev].qnext = pid;
     queuetab[tail].qprev = pid;
     return pid;
 }
Variable Documentation
queuetab
struct qentry queuetab[NQENT]
プロセスキューテーブル（全てのプロセスがアクセス可能な変数）。
NPROC-1より小さいインデックスは、プロセスIDに対応する。
queuetab[NPROC]〜queuetab[NQENT]の範囲は、キューIDと呼ばれ、
・リスト先頭
・リスト末尾
のポインタを保持するために使用される。
あるリストの先頭／末尾ノードは、queuetab配列のインデックスNPROC以降に配置し、
必ず連続した配置となる（例：先頭ノード→末尾ノード→先頭ノード→末尾ノード…）
XINU内では、リストは先頭ノードのインデックスで識別および操作する仕様である。
Note
以下はテーブルイメージ図であるが、Doxygenドキュメント上ではコメント表記が崩れるため、
note部分のスクショ画像も併記している。 ---------------------------------------------------------------—
| KEY | PREV | NEXT |↓１行がプロセスに対応する
------------------------------------------—
0 | XXX | XXXX | XXXX |
------------------------------------------—
1 | XXX | XXXX | XXXX |
------------------------------------------—
: | : |
------------------------------------------—
NPROC-1 | XXX | XXXX | XXXX |↓ ここまでがプロセス情報 -----------------------------------------------------------—
NPROC | : |↑ここから下はリスト先頭／末尾の組み合わせ
------------------------------------------—
: | : |
------------------------------------------—
: | MAXKEY | - | XXXX |リストの先頭
------------------------------------------—リストの末尾
: | MINKEY | XXXX | - |
------------------------------------------—
: | : |
------------------------------------------—
Definition at line 45 of file queue.c.
Referenced by clkhandler(), dequeue(), enqueue(), getfirst(), getitem(), getlast(), insert(), insertd(), newqueue(), and unsleep().