XINU: system/putc.c File Reference
putc.c File Reference
#include <xinu.h>
Functions
syscall putc (did32 descrp, char ch)
文字を書き込むputc()のextern宣言
Function Documentation
putc()
syscall putc (did32 descrp, char ch)
文字を書き込むputc()のextern宣言
Definition at line 9 of file putc.c.
References devtab, disable(), dentry::dvputc, isbaddev, restore(), and SYSERR.
Referenced by fprintf(), fputc(), fputs(), printf(), and xsh_cat().
 {
     intmask     mask;       /* Saved interrupt mask     */
     struct dentry   *devptr;    /* Entry in device switch table */
     int32       retval;     /* Value to return to caller    */
     mask = disable();
     if (isbaddev(descrp)) {
         restore(mask);
         return SYSERR;
     }
     devptr = (struct dentry *) &devtab[descrp];
     retval = (*devptr->dvputc) (devptr, ch);
     restore(mask);
     return retval;
 }