XINU: lib/sscanf.c File Reference
sscanf.c File Reference
Macros
#define EOF (-2)
Functions
int _doscan (register char *, register int **, int(*getc)(int, char **), int(*ungetc)(int, char **), int, int)
static int sgetch (int, char **)
int sscanf (char *str, char *fmt, int args)
static int sungetch (int, char **)
Macro Definition Documentation
EOF
#define EOF (-2)
Definition at line 3 of file sscanf.c.
Referenced by sgetch().
Function Documentation
_doscan()
int _doscan (register char * , register int ** , int(*)(int, char **) getc, int(*)(int, char **) ungetc, int , int)
Referenced by sscanf().
sgetch()
static int sgetch (int dummy, char ** cpp) static
Definition at line 32 of file sscanf.c.
References EOF.
Referenced by sscanf().
 {
     return (*(*cpp) == '\0' ? EOF : *(*cpp)++);
 }
sscanf()
int sscanf (char * str, char * fmt, int args)
Definition at line 16 of file sscanf.c.
References _doscan(), sgetch(), and sungetch().
 {
     char *s;
     s = str;
     return (_doscan(fmt, (int **)&args, sgetch, sungetch, 0, (int)&s));
 }
sungetch()
static int sungetch (int dummy, char ** cpp) static
Definition at line 44 of file sscanf.c.
Referenced by sscanf().
 {
     return (*(*cpp)--);
 }