XINU: include/string.h File Reference
string.h File Reference
Functions
char * strchr (const char *, int32)
指定された文字を文字列から探し、最初にに見つかった位置をポインタで返す。
int strlen (char *str)
NULL終端された文字列の長さを返す。NULL終端は長さに含まない。
char * strncat (char *, const char *, int32)
文字列s1の末尾に文字列s2をN文字（Byte）分、結合する。
int32 strncmp (const char *, const char *, int32)
char * strncpy (char *, const char *, int32)
文字列s1に文字列s2をN文字（Byte）分コピーする。
int32 strnlen (const char *, uint32)
NULL終端された文字列の長さを返す。NULL終端は長さに含まない。
char * strrchr (const char *, int32)
文字列の後方から指定された文字を探し、最後に見つかった位置をポインタで返す。
char * strstr (const char *, const char *)
検索対象の文字列Aから文字列Bを探す。
Function Documentation
strchr()
char* strchr (const char * s, int c)
指定された文字を文字列から探し、最初にに見つかった位置をポインタで返す。
Parameters
[in] s 探索対象の文字列
[in] c 検索文字
Returns
文字cが見つかった場合は文字cが最初に登場した位置を示すポインタ、
文字cが見つからなかった場合はNULLを返す。
Definition at line 13 of file strchr.c.
 {
     for (; *s != '\0'; s++)
     {
         if (*s == (const char)c)
         {
             return (char *)s;
         }
     }
     if ((const char)c == *s)
     {
         return (char *)s;
     }
     return 0;
 }
strlen()
int strlen (char * str)
NULL終端された文字列の長さを返す。NULL終端は長さに含まない。
Parameters
[in] str 長さを調べる対象の文字列
Returns
文字列の長さを返す。NULL終端は長さに含まない。
Definition at line 11 of file strlen.c.
Referenced by addton(), devisid(), devonid(), dns_bldq(), dns_geta(), getattrid(), if(), newdev(), newtype(), and xsh_ping().
 {
     int len;
     len = 0;
     while (*str++ != '\0')
     {
         len++;
     }
     return len;
 }
strncat()
char* strncat (char * s1, const char * s2, int n)
文字列s1の末尾に文字列s2をN文字（Byte）分、結合する。
処理の流れは、以下の通り。
Step1. 文字列s1のNULL終端'\0'までポインタを進める。
Step2. 文字列s1のNULL終端の位置から文字列s2を一文字ずつ連結する。
Step3. N+1回目にNULL終端を付与する。
Parameters
[in,out] s1 結合先の文字列
[in] s2 結合する文字列
[in] n 結合する文字数（Byte）
Returns
結合後の文字列s1を返す（NULL終端済み）。
Definition at line 17 of file strncat.c.
 {
     char *os1;
     os1 = s1;
     while (*s1++)
         ;
     --s1;
     while ((*s1++ = *s2++))
         if (--n < 0)
         {
             *--s1 = '\0';
             break;
         }
     return (os1);
 }
strncmp()
int32 strncmp (const char * , const char * , int32)
Referenced by dns_geta(), getdev(), main(), xsh_arp(), xsh_cat(), xsh_date(), xsh_help(), xsh_kill(), xsh_ls(), xsh_memdump(), xsh_memstat(), xsh_netinfo(), xsh_ping(), xsh_ps(), xsh_sleep(), xsh_udpdump(), xsh_udpecho(), xsh_udpeserver(), and xsh_uptime().
strncpy()
char* strncpy (char * s1, const char * s2, int n)
文字列s1に文字列s2をN文字（Byte）分コピーする。
自動でNULL終端（'\0'）は付与しない。
また、N Byteコピーする前にNULL終端に達した場合、残りのByte数分をNULL終端で埋める。
Parameters
[in,out] s1 コピー先の文字列
[in] s2 コピー元の文字列
[in] n コピーする文字数（Byte）
Returns
コピー後の文字列s1を返す。
Definition at line 15 of file strncpy.c.
Referenced by newtype(), sysinit(), and tftpget_mb().
 {
     register int i;
     register char *os1;
     os1 = s1;
     for (i = 0; i < n; i++)
     {
         if (((*s1++) = (*s2++)) == '\0')
         {
             while (++i < n)
             {
                 *s1++ = '\0';
             }
             return os1;
         }
     }
     return os1;
 }
strnlen()
int32 strnlen (const char * s, unsigned int len)
NULL終端された文字列の長さを返す。NULL終端は長さに含まない。
Parameters
[in] s 長さを調べる対象の文字列
[in] len 読み取る長さの最大長（Byte）
Returns
文字列の長さを返す。NULL終端は長さに含まず、ユーザが指定したN Byteを最大長とする。
Definition at line 14 of file strnlen.c.
Referenced by tftpget_mb(), xsh_help(), and xsh_udpecho().
 {
     int n;
     n = 0;
     while (*s++ && n < len)
         n++;
     return (n);
 }
strrchr()
char* strrchr (const char * s, int c)
文字列の後方から指定された文字を探し、最後に見つかった位置をポインタで返す。
Parameters
[in] s 探索対象の文字列
[in] c 検索文字
Returns
文字cが見つかった場合は文字cが最後に登場した位置を示すポインタ、
文字cが見つからなかった場合はNULLを返す。
Definition at line 13 of file strrchr.c.
 {
     char *r = 0;
     for (; *s != '\0'; s++)
     {
         if (*s == (const char)c)
         {
             r = (char *)s;
         }
     }
     if ((const char)c == *s)
     {
         return (char *)s;
     }
     return r;
 }
strstr()
char* strstr (const char * cs, const char * ct)
検索対象の文字列Aから文字列Bを探す。
Parameters
[in] cs 検索対象の文字列
[in] ct 検索語句（検索キーワード）となる文字列
Returns
検索語句が見つかった場合はその位置をポインタで返し、見つからなかった場合はNULLを返す。
Definition at line 12 of file strstr.c.
 {
     char *cq;
     char *cr;
     for (; *cs != '\0'; cs++)
     {
         if (*cs == *ct)
         {
             cq = (char *)cs;
             cr = (char *)ct;
             while ((*cq != '\0') && (*cr != '\0'))
             {
                 if (*cq != *cr)
                 {
                     break;
                 }
                 cq++;
                 cr++;
             }
             if ('\0' == *cr)
             {
                 return (char *)cs;
             }
         }
     }
     return 0;
 }