XINU: shell/xsh_udpecho.c File Reference
xsh_udpecho.c File Reference
#include <xinu.h>
#include <stdio.h>
#include <string.h>
Functions
int atoi (char *)
ASCII文字列をint型に変換する。
shellcmd xsh_udpecho (int nargs, char *args[])
Function Documentation
atoi()
int atoi (char * p)
ASCII文字列をint型に変換する。
処理の流れは、
Step1. 「不要な文字（空白、TAB）の削除」もしくは「正数／負数の判定」を行う
Step2. 0〜9の範囲の値であれば、一桁ずつ記録する。それ以外の文字は呼び飛ばす
ASCIIコードとして、0=0x30、1=0x31、2=0x32、…、9=0x39であるため、
「0x30〜0x39の範囲のASCIIコード値(0〜9の値) - '0'(=0x30)」と計算すれば、
0〜9の整数値が得られる。
Step3. Step.1で取得した符号情報（±）を反映した整数を返す。
Parameters
[in] p ASCII文字列
Returns
ASCII文字列をint型に変換した整数値
Note
ASCIIコード情報は、ターミナル上で"$ man ascii"で確認できる。
Definition at line 19 of file atoi.c.
Referenced by xsh_udpecho().
 {
     int n = 0, f = 0;
     for (;; p++)
     {
         switch (*p)
         {
         case ' ':
         case '\t':
             continue;
         case '-':
             f++;
         case '+':
             p++;
         }
         break;
     }
     while (*p >= '0' && *p <= '9')
     {
         n = n * 10 + *p++ - '0';
     }
     return (f ? -n : n);
 }
xsh_udpecho()
shellcmd xsh_udpecho (int nargs, char * args[])
Definition at line 14 of file xsh_udpecho.c.
References atoi(), delay(), dot2ip(), fprintf(), printf(), stderr, strncmp(), strnlen(), SYSERR, TIMEOUT, udp_recv(), udp_register(), udp_release(), and udp_send().
 {
     int i;          /* index into buffer        */
     int retval;         /* return value         */
     char    msg[] = "Xinu testing UDP echo"; /* message to send */
     char    inbuf[1500];        /* buffer for incoming reply    */
     int32   slot;           /* UDP slot to use      */
     int32   msglen;         /* length of outgoing message   */
     uint32  remoteip;       /* remote IP address to use */
     uint16  remport= 7;     /* remote port number to use    */
     uint16  locport = 52743;    /* local port to use        */
     int32   retries = 3;        /* number of retries        */
     int32   delay   = 500;      /* reception delay in ms    */
     /* For argument '--help', emit help about the 'udpecho' command */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s  REMOTEIP\n\n", args[0]);
         printf("Description:\n");
         printf("\tBounce a message off a remote UDP echo server\n");
         printf("Options:\n");
         printf("\tREMOTEIP:\tIP address in dotted decimal\n");
         printf("\t--help\t display this help and exit\n");
         return 0;
     }
     /* Check for valid IP address argument */
     if (nargs != 2) {
         fprintf(stderr, "%s: invalid number of argument(s)\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     if (dot2ip(args[1], &remoteip) == SYSERR) {
         fprintf(stderr, "%s: invalid IP address argument\r\n",
             args[0]);
         return 1;
     }
     if (nargs == 3) {
         retval = atoi(args[2]);
         if ( (retval <= 0) || (retval > 64535) ) {
             fprintf(stderr, "%s: invalid port argument\r\n",
                 args[0]);
             return 1;
         }
         remport = (uint16) retval;
     }
     fprintf(stderr, "using remote port %d\n", remport);
     /* register local UDP port */
     slot = udp_register(remoteip, remport, locport);
     if (slot == SYSERR) {
         fprintf(stderr, "%s: could not reserve UDP port %d\n",
                 args[0], locport);
         return 1;
     }
     /* Retry sending outgoing datagram and getting response */
     msglen = strnlen(msg, 1200);
     for (i=0; i<retries; i++) {
         retval = udp_send(slot, msg, msglen);
         if (retval == SYSERR) {
             fprintf(stderr, "%s: error sending UDP \n",
                 args[0]);
             return 1;
         }
         retval = udp_recv(slot, inbuf, sizeof(inbuf), delay);
         if (retval == TIMEOUT) {
             fprintf(stderr, "%s: timeout...\n", args[0]);
             continue;
         } else if (retval == SYSERR) {
             fprintf(stderr, "%s: error from udp_recv \n",
                 args[0]);
             udp_release(slot);
             return 1;
         }
         break;
     }
     udp_release(slot);
     if (retval == TIMEOUT) {
         fprintf(stderr, "%s: retry limit exceeded\n",
             args[0]);
         return 1;
     }
     /* Response received - check contents */
     if (retval != msglen) {
         fprintf(stderr, "%s: sent %d bytes and received %d\n",
             args[0], msglen, retval);
         return 1;
     }
     for (i = 0; i < msglen; i++) {
         if (msg[i] != inbuf[i]) {
             fprintf(stderr, "%s: reply differs at byte %d\n",
                 args[0], i);
             return 1;
         }
     }
     printf("UDP echo test was successful\n");
     return 0;
 }