XINU: device/tty/ttycontrol.c File Reference
ttycontrol.c File Reference
#include <xinu.h>
Functions
devcall ttycontrol (struct dentry *devptr, int32 func, int32 arg1, int32 arg2)
Function Documentation
ttycontrol()
devcall ttycontrol (struct dentry * devptr, int32 func, int32 arg1, int32 arg2)
Definition at line 9 of file ttycontrol.c.
References dentry::dvminor, FALSE, OK, semcount(), signal(), SYSERR, TC_ECHO, TC_ICHARS, TC_MODEC, TC_MODEK, TC_MODER, TC_NEXTC, TC_NOECHO, TRUE, ttytab, TY_IMCBREAK, TY_IMCOOKED, TY_IMRAW, ttycblk::tyiecho, ttycblk::tyimode, ttycblk::tyisem, ttycblk::tyitail, and wait().
 {
     struct  ttycblk *typtr;     /* Pointer to tty control block */
     char    ch;         /* Character for lookahead  */
     typtr = &ttytab[devptr->dvminor];
     /* Process the request */
     switch ( func ) {
     case TC_NEXTC:
         wait(typtr->tyisem);
         ch = *typtr->tyitail;
         signal(typtr->tyisem);
         return (devcall)ch;
     case TC_MODER:
         typtr->tyimode = TY_IMRAW;
         return (devcall)OK;
     case TC_MODEC:
         typtr->tyimode = TY_IMCOOKED;
         return (devcall)OK;
     case TC_MODEK:
         typtr->tyimode = TY_IMCBREAK;
         return (devcall)OK;
     case TC_ICHARS:
         return(semcount(typtr->tyisem));
     case TC_ECHO:
         typtr->tyiecho = TRUE;
         return (devcall)OK;
     case TC_NOECHO:
         typtr->tyiecho = FALSE;
         return (devcall)OK;
     default:
         return (devcall)SYSERR;
     }
 }