XINU: system/read.c File Reference
read.c File Reference
#include <xinu.h>
Functions
syscall read (did32 descrp, char *buffer, uint32 count)
Function Documentation
read()
syscall read (did32 descrp, char * buffer, uint32 count)
Definition at line 9 of file read.c.
References devtab, disable(), dentry::dvread, isbaddev, restore(), and SYSERR.
Referenced by lfdballoc(), lfibget(), lfibput(), lfsckfmt(), lfsetup(), lfsopen(), netin(), shell(), xsh_ls(), and xsh_rdstest().
 {
     intmask     mask;       /* Saved interrupt mask     */
     struct dentry   *devptr;    /* Entry in device switch table */
     int32       retval;     /* Value to return to caller    */
     mask = disable();
     if (isbaddev(descrp)) {
         restore(mask);
         return SYSERR;
     }
     devptr = (struct dentry *) &devtab[descrp];
     retval = (*devptr->dvread) (devptr, buffer, count);
     restore(mask);
     return retval;
 }