XINU: system/main.c File Reference
main.c File Reference
XINUシェルを起動する。
#include <xinu.h>
Functions
process main (void)
XINUシェルを起動する。
Detailed Description
XINUシェルを起動する。
Definition in file main.c.
Function Documentation
main()
process main (void)
XINUシェルを起動する。
最初に生成されるmainプロセスのextern宣言
Step1. メッセージを全て受信する（ただし、メッセージ内容は確認しない）。
Step2. XINUシェルを作成／起動する。
Step3. XINUシェルが終了した場合は、以下の処理を行う（無限に繰り返す）。
・メッセージ到着を待つ。メッセージが来なければ、待ち続ける。
・200[ms]スリープする。
・XINUシェルを再作成／起動する。
Returns
OKを返す。
Definition at line 18 of file main.c.
References CONSOLE, create(), kprintf(), OK, receive(), recvclr(), resume(), shell(), sleepms(), and TRUE.
Referenced by startup().
 {
     /* Run the Xinu shell */
     recvclr();
     resume(create(shell, 8192, 50, "shell", 1, CONSOLE));
     /* Wait for shell to exit and recreate it */
     while (TRUE)
     {
         receive();
         sleepms(200);
         kprintf("\n\nMain process recreating shell\n\n");
         resume(create(shell, 4096, 20, "shell", 1, CONSOLE));
     }
     return OK;
 }