XINU: include/shprototypes.h File Reference
shprototypes.h File Reference
Functions
shellcmd xsh_argecho (int32, char *[])
shellcmd xsh_arp (int32, char *[])
shellcmd xsh_bingid (int32, char *[])
shellcmd xsh_cat (int32, char *[])
shellcmd xsh_clear (int32, char *[])
shellcmd xsh_date (int32, char *[])
shellcmd xsh_devdump (int32, char *[])
shellcmd xsh_echo (int32, char *[])
shellcmd xsh_ethstat (int32, char *[])
shellcmd xsh_exit (int32, char *[])
exitコマンドとして、シェル終了を引き起こす終了コードを返す。
shellcmd xsh_help (int32, char *[])
shellcmd xsh_kill (int32, char *[])
shellcmd xsh_led (int32, char *[])
shellcmd xsh_ls (int32, char *[])
shellcmd xsh_memdump (int32, char *[])
shellcmd xsh_memstat (int32, char *[])
shellcmd xsh_netinfo (int32, char *[])
shellcmd xsh_nvram (int32, char *[])
shellcmd xsh_ping (int32, char *[])
shellcmd xsh_ps (int32, char *[])
shellcmd xsh_sleep (int32, char *[])
shellcmd xsh_udpdump (int32, char *[])
shellcmd xsh_udpecho (int32, char *[])
shellcmd xsh_udpeserver (int32, char *[])
shellcmd xsh_uptime (int32, char *[])
Function Documentation
xsh_argecho()
shellcmd xsh_argecho (int32 , char * [])
Definition at line 10 of file xsh_argecho.c.
References printf().
 {
     int32   i;
     printf("\n\nThe %d arguments are:\n", nargs);
     for (i = 0; i < nargs; i++) {
         printf("    %2d: %s\n", i, args[i]);
     }
     printf("\n");
     return 0;
 }
xsh_arp()
shellcmd xsh_arp (int32 , char * [])
Definition at line 12 of file xsh_arp.c.
References arp_dmp(), printf(), and strncmp().
 {
     /* For argument '--help', emit help about the 'arp' command */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s\n\n", args[0]);
         printf("Description:\n");
         printf("\tDisplays information from the ARP cache\n");
         printf("Options:\n");
         printf("\t--help\t display this help and exit\n");
         return 0;
     }
     /* Dump the Entire ARP cache */
     printf("\n");
     arp_dmp();
     return 0;
 }
xsh_bingid()
shellcmd xsh_bingid (int32 , char * [])
xsh_cat()
shellcmd xsh_cat (int32 , char * [])
Definition at line 11 of file xsh_cat.c.
References close(), EOF, fprintf(), getc(), NAMESPACE, NULLCH, open(), printf(), putc(), stderr, stdin, stdout, strncmp(), and SYSERR.
 {
     int32   i;          /* index into proctabl      */
     int32   nextch;         /* character read from file */
     did32   descr;          /* descriptor for a file    */
     char    *argptr;        /* pointer to next arg string   */
     /* For argument '--help', emit help about the 'cat' command */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s [file...]\n\n", args[0]);
         printf("Description:\n");
         printf("\twrites contents of files or stdin to stdout\n");
         printf("Options:\n");
         printf("\tfile...\tzero or more file names\n");
         printf("\t--help\t display this help and exit\n");
         return 0;
     }
     if (nargs == 1) {
         nextch = getc(stdin);
         while (nextch != EOF) {
             putc(stdout, nextch);
             nextch = getc(stdin);
         }
         return 0;
     }
     for (i = 1; i < nargs; i++) {
         argptr = args[i];
         if ( (argptr[0] == '-') && (argptr[1] == NULLCH) ) {
             descr = stdin;
         } else {
             descr = open(NAMESPACE, argptr, "ro");
             if (descr == (did32)SYSERR) {
                 fprintf(stderr, "%s: cannot open file %s\n",
                     args[0], argptr);
                 return 1;
             }
         }
         nextch = getc(descr);
         while (nextch != EOF) {
             putc(stdout, nextch);
             nextch = getc(descr);
         }
         close(descr);
     }
     return 0;
 }
xsh_clear()
shellcmd xsh_clear (int32 , char * [])
Definition at line 10 of file xsh_clear.c.
References fprintf(), printf(), and stderr.
 {
     /* Insure no arguments were passed */
     if (nargs > 1) {
     fprintf(stderr,"use is: %s\n", args[0]);
     return 1;
     }
     printf("\033[0m\033[2J\033[H\n");
     return 0;
 }
xsh_date()
shellcmd xsh_date (int32 , char * [])
Definition at line 11 of file xsh_date.c.
References ascdate(), Date, DATE_DST_AUTO, DATE_DST_OFF, DATE_DST_ON, dateinfo::dt_bootvalid, dateinfo::dt_daylight, FALSE, fprintf(), gettime(), printf(), stderr, strncmp(), and SYSERR.
{
     int32   retval;         /* return value         */
     uint32  now;            /* current local time       */
     char    datestr[64];        /* printable date in ascii  */
     /* Output info for '--help' argument */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Usage: %s\n\n", args[0]);
         printf("Description:\n");
         printf("\tDisplays the current date and time\n");
         printf("Options (one per invocation):\n");
         printf("\t-f\tforce a time server request to be sent\n");
         printf("\t-d\tset daylight savings time on\n");
         printf("\t-s\tset standard time (not daylight savings)\n");
         printf("\t-a\tset daylight savings to automatic\n");
         printf("\t--help\tdisplay this help and exit\n");
         return 0;
     }
     /* Check argument count */
     if (nargs > 2) {
         fprintf(stderr, "%s: too many arguments\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
             args[0]);
         return 1;
     }
     if (nargs == 2) {
         if (strncmp(args[1], "-f", 3) == 0) {
             Date.dt_bootvalid = FALSE;
         } else if (strncmp(args[1], "-d", 3) == 0) {
             Date.dt_daylight = DATE_DST_ON;
         } else if (strncmp(args[1], "-s", 3) == 0) {
             Date.dt_daylight = DATE_DST_OFF;
         } else if (strncmp(args[1], "-a", 3) == 0) {
             Date.dt_daylight = DATE_DST_AUTO;
         } else {
             fprintf(stderr, "%s: invalid argument\n", args[0]);
             fprintf(stderr,
                 "Try '%s --help' for more information\n",
                 args[0]);
             return 1;
         }
     }
     retval = gettime(&now);
     if (retval == SYSERR) {
         fprintf(stderr,
             "%s: could not obtain the current date\n",
             args[0]);
         return 1;
     }
     ascdate(now, datestr);
     printf("%s\n", datestr);
     return 0;
 }
xsh_devdump()
shellcmd xsh_devdump (int32 , char * [])
Definition at line 10 of file xsh_devdump.c.
References devtab, dentry::dvminor, dentry::dvname, fprintf(), NDEVS, printf(), and stderr.
 {
     struct  dentry  *devptr;    /* pointer to device entry  */
     int32   i;          /* walks through device table   */
     /* No arguments are expected */
     if (nargs > 1) {
         fprintf(stderr, "No arguments allowed\n");
         return 1;
     }
     /* Walk through device table */
     printf("Device     Name     Minor\n");
     printf("------ ------------ -----\n");
     for (i = 0; i < NDEVS; i++) {
         devptr = &devtab[i];
         printf("%4d   %-12s %3d\n", i, devptr->dvname,
             devptr->dvminor);
     }
     return 0;
 }
xsh_echo()
shellcmd xsh_echo (int32 , char * [])
Definition at line 10 of file xsh_echo.c.
References printf().
 {
     int32   i;          /* walks through args array */
     if (nargs > 1) {
         printf("%s", args[1]);
         for (i = 2; i < nargs; i++) {
             printf(" %s", args[i]);
         }
     }
     printf("\n");
     return 0;
 }
xsh_ethstat()
shellcmd xsh_ethstat (int32 , char * [])
xsh_exit()
shellcmd xsh_exit (int nargs, char * args[])
exitコマンドとして、シェル終了を引き起こす終了コードを返す。
Parameters
[in] nargs 引数の数（使用しない）
[in] args 引数（使用しない）
Returns
SHELL_EXITを返す。
Definition at line 17 of file xsh_exit.c.
References SHELL_EXIT.
 {
     return SHELL_EXIT;
 }
xsh_help()
shellcmd xsh_help (int32 , char * [])
Definition at line 11 of file xsh_help.c.
References cmdent::cfunc, cmdtab, cmdent::cname, fprintf(), ncmd, NULLCH, printf(), stderr, strncmp(), and strnlen().
 {
     int32   i;
     char    *argv[2];       /* argument vector for call */
     char    *src, *cmp;     /* used for string compare  */
     int32   len;            /* length of a command name */
     int32   maxlen;         /* maximum length of all    */
                     /*   command names      */
     int32   cols;           /* number of columns in the */
                     /*   formatted command list */
     int32   spac;           /* space per column in the  */
                     /*   formatted command list */
     int32   lines;          /* total lines of output in the */
                     /*   formatted command list */
     int32   j;          /* index of commands across one */
                     /*   line of formatted output   */
     /* For argument '--help', emit help about the 'help' command    */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use:\n");
         printf("\t%s [command]\n", args[0]);
         printf("Description:\n");
         printf("\tProvides a list of shell commands or\n");
         printf("\thelp information for a specific command\n");
         printf("Options:\n");
         printf("\tcommand\tspecific command for which to\n");
         printf("\t\tdisplay help information\n");
         printf("\t--help\tdisplay this help and exit\n");
         return 0;
     }
     /* Check for valid number of arguments */
     if (nargs > 2) {
         fprintf(stderr, "%s: too many arguments\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     /* Output help for specific command given as an argument */
     if (nargs == 2) {
         for (i = 0; i < ncmd; i++) {
             src = cmdtab[i].cname;
             cmp = args[1];
             while (*src != NULLCH) {
                 if (*src != *cmp) {
                     break;
                 }
                 src++;
                 cmp++;
             }
             if ( (*src != NULLCH) || (*cmp != NULLCH) ) {
                 continue;
             }
             /* prepare args for shell command */
             argv[0] = args[1];
             argv[1] = "--help";
             (*cmdtab[i].cfunc) (2, argv);
             return 0;
         }
         printf("%s: no such command as '%s'\n", args[0], args[1]);
         return 1;
     }
     /* No arguments -- print a list of shell commands */
     printf("\nshell commands are:\n\n");
     /* Calculate the maximum length of a command name */
     maxlen = 0;
     for (i = 0; i < ncmd; i++) {
         len = strnlen(cmdtab[i].cname, 80);
         if (len > maxlen) {
             maxlen = len;
         }
     }
     /* Calculate the number of command names per line */
     cols = 80/(maxlen+1);
     if (cols > 6) {
         cols = 6;
     }
     /* Calculate the width of a column */
     spac = 80/cols;
     /* Calculate the number of lines of output */
     lines = (ncmd+(cols-1))/cols;
     /* print the lines of command names */
     for (i=0; i<lines; i++) {
         for (j=i; j<ncmd; j+=lines) {
             len = strnlen(cmdtab[j].cname,80);
             printf("%s", cmdtab[j].cname);
             while (len < spac) {
                 printf(" ");
                 len++;
             }
         }
         printf("\n");
     }
     return 0;
 }
xsh_kill()
shellcmd xsh_kill (int32 , char * [])
Definition at line 11 of file xsh_kill.c.
References fprintf(), kill(), NULLCH, OK, printf(), stderr, strncmp(), and SYSERR.
{
     int32   retval;         /* return value         */
     pid32   pid;            /* ID of process to kill    */
     char    ch;         /* next character of argument   */
     char    *chptr;         /* walks along argument string  */
     /* Output info for '--help' argument */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Usage: %s PID\n\n", args[0]);
         printf("Description:\n");
         printf("\tterminates a process\n");
         printf("Options:\n");
         printf("\tPID \tthe ID of a process to terminate\n");
         printf("\t--help\tdisplay this help and exit\n");
         return OK;
     }
     /* Check argument count */
     if (nargs != 2) {
         fprintf(stderr, "%s: incorrect argument\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
             args[0]);
         return SYSERR;
     }
     /* compute process ID from argument string */
     chptr = args[1];
     ch = *chptr++;
     pid = 0;
     while(ch != NULLCH) {
         if ( (ch < '0') || (ch > '9') ) {
             fprintf(stderr, "%s: non-digit in process ID\n",
                 args[0]);
             return 1;
         }
         pid = 10*pid + (ch - '0');
         ch = *chptr++;
     }
     if (pid == 0) {
         fprintf(stderr, "%s: cannot kill the null process\n",
             args[0]);
         return 1;
     }
     retval = kill(pid);
     if (retval == SYSERR) {
         fprintf(stderr, "%s: cannot kill process %d\n",
             args[0], pid);
         return 1;
     }
     return 0;
 }
xsh_led()
shellcmd xsh_led (int32 , char * [])
xsh_ls()
shellcmd xsh_ls (int32 , char * [])
Definition at line 10 of file xsh_ls.c.
References fprintf(), ldentry::ld_name, LF_AREA_DIR, Lf_data, lfdata::lf_dir, lfdata::lf_dirpresent, lfdata::lf_dskdev, lfdata::lf_mutex, lfdir::lfd_files, lfdir::lfd_nfiles, lfscheck(), printf(), read(), signal(), stderr, strncmp(), SYSERR, TRUE, and wait().
 {
     struct  lfdir   *dirptr;    /* Ptr to in-memory directory   */
     int32   i;
     struct  ldentry *ldptr;     /* Ptr to an entry in directory */
     /* For argument '--help', emit help about the 'ls' command  */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s\n\n", args[0]);
         printf("Description:\n");
         printf("\tlists the names of files\n");
         printf("Options:\n");
         printf("\t--help\t display this help and exit\n");
         return 0;
     }
     if (nargs != 1) {
         printf("illegal option: try --help for more information\n");
         return 1;
     }
     /* Obtain copy of directory if not already present in memory    */
     dirptr = &Lf_data.lf_dir;
     wait(Lf_data.lf_mutex);
     if (! Lf_data.lf_dirpresent) {
         if (read(Lf_data.lf_dskdev, (char *)dirptr, LF_AREA_DIR) == SYSERR ) {
         signal(Lf_data.lf_mutex);
         fprintf(stderr,"cannot read the directory\n");
         }
         if (lfscheck(dirptr) == SYSERR ) {
         fprintf(stderr, "THe disk does not contain a Xinu file system\n");
         signal(Lf_data.lf_mutex);
         return 1;
         }
         Lf_data.lf_dirpresent = TRUE;
     }
     signal(Lf_data.lf_mutex);
     /* Search directory and list the file names */
     for (i=0; i<dirptr->lfd_nfiles; i++) {
         ldptr = &dirptr->lfd_files[i];
         printf("%s\n", ldptr->ld_name);
     }
     return 0;
 }
xsh_memdump()
shellcmd xsh_memdump (int32 , char * [])
Definition at line 15 of file xsh_memdump.c.
References FALSE, fprintf(), maxheap, parseval(), printf(), start, stderr, stop(), strncmp(), and TRUE.
 {
     bool8   force = FALSE;      /* ignore address sanity checks */
     uint32  begin;          /* begining address     */
     uint32  stop;           /* last address to dump     */
     uint32  length;         /* length of region to dump */
     int32   arg;            /* index into args array    */
     uint32  l;          /* counts length during dump    */
     int32   i;          /* counts words during dump */
     uint32  *addr;          /* address to dump      */
     char    *chptr;         /* character address to dump    */
     char    ch;         /* next character to print  */
     /* For argument '--help', emit help about the 'memdump' command */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s [-f] Address Length\n\n", args[0]);
         printf("Description:\n");
         printf("\tDumps Length bytes of memory begining at the\n");
         printf("\tspecified starting address (both the address\n");
         printf("\tand length can be specified in decimal or hex)\n");
         printf("Options:\n");
         printf("\t-f         ignore sanity checks for addresses\n");
         printf("\tAddress    memory address at which to start\n");
         printf("\tLength     the number of bytes to dump\n");
         printf("\t--help     display this help and exit\n");
         return 0;
     }
     /* Check for valid number of arguments */
     if (nargs < 3 || nargs > 4) {
         fprintf(stderr, "%s: incorrect number of arguments\n",
                 args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     arg = 1;
     if (strncmp(args[arg], "-f", 2) == 0) {
         force = TRUE;
         arg++;
         nargs --;
     }
     if (nargs != 3) {
         fprintf(stderr, "%s: too few arguments\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     if ( (begin=parseval(args[arg])) == 0 ) {
         fprintf(stderr, "%s: invalid begining address\n",
                 args[0]);
         return 1;
     }
     if ( (length =parseval(args[arg+1])) == 0 ) {
         fprintf(stderr, "%s: invalid length address\n",
                 args[0]);
         return 1;
     }
     /* Round begining address down to multiple of four and round    */
     /*  length up to a multiple of four             */
     begin &= ~0x3;
     length = (length + 3) & ~0x3;
     /* Add length to begin address */
     stop = begin + length;
     /* verify that the address and length are reasonable */
     if ( force || ( (begin >= (uint32)&start) && (stop > begin) &&
                     (((void *)stop) < maxheap)) ) {
         /* values are valid; perform dump */
         chptr = (char *)begin;
         for (l=0; l<length; l+=16) {
             printf("%08x: ", begin);
             addr = (uint32 *)begin;
             for (i=0; i<4; i++) {
                 printf("%08x ",*addr++);
             }
             printf("  *");
             for (i=0; i<16; i++) {
                 ch = *chptr++;
                 if ( (ch >= 0x20) && (ch <= 0x7e) ) {
                     printf("%c",ch);
                 } else {
                     printf(".");
                 }
             }
             printf("*\n");
             begin += 16;
         }
         return 0;
     } else {
         printf("Values are out of range; use -f to force\n");
     }
     return 1;
 }
xsh_memstat()
shellcmd xsh_memstat (int32 , char * [])
Definition at line 14 of file xsh_memstat.c.
References fprintf(), printf(), printFreeList(), printMemUse(), stderr, and strncmp().
 {
     /* For argument '--help', emit help about the 'memstat' command */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("use: %s \n\n", args[0]);
         printf("Description:\n");
         printf("\tDisplays the current memory use and prints the\n");
         printf("\tfree list.\n");
         printf("Options:\n");
         printf("\t--help\t\tdisplay this help and exit\n");
         return 0;
     }
     /* Check for valid number of arguments */
     if (nargs > 1) {
         fprintf(stderr, "%s: too many arguments\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     printMemUse();
     printFreeList();
     return 0;
 }
xsh_netinfo()
shellcmd xsh_netinfo (int32 , char * [])
Definition at line 12 of file xsh_netinfo.c.
References network::dnsserver, network::ethbcast, network::ethucast, FALSE, fprintf(), getlocalip(), network::ipbcast, network::ipmask, network::ipprefix, network::iprouter, network::ipucast, network::ipvalid, NetData, network::ntpserver, OK, printf(), sprintf(), stderr, strncmp(), and SYSERR.
{
     uint32  ipaddr;         /* An IP address in binary  */
     uint32  ipbcast;        /* IP broadcast addr. in binary */
     uint32  ipprefix;       /* IP network prefix in binary  */
     uint32  router;         /* Router address in binary */
     uint32  tserver;        /* NTP server address in binary */
     uint32  dserver;        /* DNS server address in binary */
     char    str[40];        /* Temporary used for formatting*/
     uint32  ipmask;         /* Subnet mask in binary    */
     /* Output info for '--help' argument */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Usage: %s\n\n", args[0]);
         printf("Description:\n");
         printf("\tDisplays IP address information\n");
         printf("Options:\n");
         printf("\t-f\tforce a new DHCP request\n");
         printf("\t--help\tdisplay this help and exit\n");
         return OK;
     }
     /* Check argument count */
     if (nargs > 2) {
         fprintf(stderr, "%s: too many arguments\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
             args[0]);
         return SYSERR;
     }
     if (nargs == 2) {
         if (strncmp(args[1], "-f", 3) != 0) {
             fprintf(stderr, "%s: invalid argument\n", args[0]);
             fprintf(stderr,
                 "Try '%s --help' for more information\n",
                 args[0]);
             return 1;
         }
         NetData.ipvalid = FALSE;
         getlocalip();
     }
     /* IP unicast address in dotted decimal and hex */
     ipaddr = NetData.ipucast;
     sprintf(str, "%d.%d.%d.%d",
         (ipaddr>>24)&0xff, (ipaddr>>16)&0xff,
         (ipaddr>>8)&0xff,        ipaddr&0xff);
     printf("   %-16s  %-16s  0x%08x\n",
         "IP address:", str, ipaddr);
     /* IP network broadcast address in dotted decimal & hex */
     ipbcast = NetData.ipbcast;
     sprintf(str, "%d.%d.%d.%d",
         (ipbcast>>24)&0xff, (ipbcast>>16)&0xff,
         (ipbcast>>8)&0xff,        ipbcast&0xff);
     printf("   %-16s  %-16s  0x%08x\n",
         "IP broadcast:", str, ipbcast);
     /* IP network prefix in dotted decimal & hex */
     ipprefix = NetData.ipprefix;
     sprintf(str, "%d.%d.%d.%d",
         (ipprefix>>24)&0xff, (ipprefix>>16)&0xff,
         (ipprefix>>8)&0xff,        ipprefix&0xff);
     printf("   %-16s  %-16s  0x%08x\n",
         "IP prefix:", str, ipprefix);
     /* IP network mask in dotted decimal & hex */
     ipmask = NetData.ipmask;
     ipaddr = NetData.ipucast;
     sprintf(str, "%d.%d.%d.%d",
         (ipmask>>24)&0xff, (ipmask>>16)&0xff,
         (ipmask>>8)&0xff,        ipmask&0xff);
     printf("   %-16s  %-16s  0x%08x\n",
         "Address mask:", str, ipmask);
     /* Default router in dotted decimal & hex */
     router = NetData.iprouter;
     sprintf(str, "%d.%d.%d.%d",
         (router>>24)&0xff, (router>>16)&0xff,
         (router>>8)&0xff,        router&0xff);
     printf("   %-16s  %-16s  0x%08x\n",
         "IP router:", str, router);
     /* NTP time server in dotted decimal & hex */
     tserver = NetData.ntpserver;
     if (tserver != 0) {
         sprintf(str, "%d.%d.%d.%d",
             (tserver>>24)&0xff, (tserver>>16)&0xff,
             (tserver>>8)&0xff,        tserver&0xff);
         printf("   %-16s  %-16s  0x%08x\n",
             "NTP time server:", str, tserver);
     }
     /* DNS server in dotted decimal & hex */
     dserver = NetData.dnsserver;
     if (dserver != 0) {
         sprintf(str, "%d.%d.%d.%d",
             (dserver>>24)&0xff, (dserver>>16)&0xff,
             (dserver>>8)&0xff,        dserver&0xff);
         printf("   %-16s  %-16s  0x%08x\n",
             "DNS server:", str, dserver);
     }
     printf("   %-16s  %02x:%02x:%02x:%02x:%02x:%02x\n",
     "MAC unicast:",
     0xff & NetData.ethucast[0],
     0xff & NetData.ethucast[1],
     0xff & NetData.ethucast[2],
     0xff & NetData.ethucast[3],
     0xff & NetData.ethucast[4],
     0xff & NetData.ethucast[5]);
     printf("   %-16s  %02x:%02x:%02x:%02x:%02x:%02x\n",
     "MAC broadcast:",
     0xff & NetData.ethbcast[0],
     0xff & NetData.ethbcast[1],
     0xff & NetData.ethbcast[2],
     0xff & NetData.ethbcast[3],
     0xff & NetData.ethbcast[4],
     0xff & NetData.ethbcast[5]);
     return OK;
 }
xsh_nvram()
shellcmd xsh_nvram (int32 , char * [])
xsh_ping()
shellcmd xsh_ping (int32 , char * [])
Definition at line 11 of file xsh_ping.c.
References dnslookup(), dot2ip(), FALSE, fprintf(), ICMP_ECHOREQST, icmp_recv(), icmp_register(), icmp_release(), icmp_send(), printf(), stderr, strlen(), strncmp(), SYSERR, TIMEOUT, and TRUE.
 {
     uint32  ipaddr;         /* IP address in binary     */
     int32   retval;         /* return value         */
     int32   slot;           /* Slot in ICMP to use      */
     static  int32   seq = 0;    /* sequence number      */
     char    buf[56];        /* buffer of chars      */
     int32   i;          /* index into buffer        */
     int32   nextval;        /* next value to use        */
     bool8   dname;
     /* For argument '--help', emit help about the 'ping' command    */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s  address\n\n", args[0]);
         printf("Description:\n");
         printf("\tUse ICMP Echo to ping a remote host\n");
         printf("Options:\n");
         printf("\t--help\t display this help and exit\n");
         printf("\taddress\t an IP address in dotted decimal\n");
         return 0;
     }
     /* Check for valid number of arguments */
     if (nargs != 2) {
         fprintf(stderr, "%s: invalid arguments\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     dname = FALSE;
     for(i = 0; i < strlen(args[1]); i++) {
         if( ( (args[1][i] >= 65) && (args[1][i] <= 90) ) ||
             ( (args[1][i] >= 97) && (args[1][i] <= 122)) ) {
                 dname = TRUE;
             break;
         }
     }
     if(dname == TRUE) {
         ipaddr = dnslookup(args[1]);
         if((int32)ipaddr == SYSERR) {
             fprintf(stderr, "DNS cannot resolve %s\n", args[1]);
             return 1;
         }
         printf("Pinging %d.%d.%d.%d\n", (ipaddr>>24)&0xff,
                         (ipaddr>>16)&0xff,
                         (ipaddr>>8)&0xff,
                         (ipaddr)&0xff);
     }
     else {
         /* convert argument to binary */
         retval = dot2ip(args[1], &ipaddr);
         if ((int32)retval == SYSERR) {
             fprintf(stderr, "%s: invalid IP address\n", args[0]);
             return 1;
         }
     }
     /* Register to receive an ICMP Echo Reply */
     slot = icmp_register(ipaddr);
     if (slot == SYSERR) {
         fprintf(stderr,"%s: ICMP registration failed\n", args[0]);
         return 1;
     }
     /* Fill the buffer with values - start with low-order byte of   */
     /*  the sequence number and increment           */
     nextval = seq;
     for (i = 0; i<sizeof(buf); i++) {
         buf[i] = 0xff & nextval++;
     }
     /* Send an ICMP Echo Request */
     retval = icmp_send(ipaddr, ICMP_ECHOREQST, slot,
                     seq++, buf, sizeof(buf));
     if (retval == SYSERR) {
         fprintf(stderr, "%s: no response from host %s\n", args[0], args[1]);
         icmp_release(slot);
         return 1;
     }
     /* Read a reply */
     retval = icmp_recv(slot, buf, sizeof(buf), 3000);
     icmp_release(slot);
     if (retval == TIMEOUT) {
         fprintf(stderr, "%s: no response from host %s\n", args[0],
                     args[1]);
         return 1;
     }
     if (retval != sizeof(buf)) {
         fprintf(stderr,"expected %d bytes but got back %d\n",
             sizeof(buf), retval);
         }
     fprintf(stderr, "host %s is alive\n", args[1]);
     return 0;
 }
xsh_ps()
shellcmd xsh_ps (int32 , char * [])
Definition at line 11 of file xsh_ps.c.
References fprintf(), NPROC, PR_FREE, printf(), procent::prname, proctab, procent::prparent, procent::prprio, procent::prstate, procent::prstkbase, procent::prstklen, procent::prstkptr, stderr, and strncmp().
 {
     struct  procent *prptr;     /* pointer to process       */
     int32   i;          /* index into proctabl      */
     char *pstate[]  = {     /* names for process states */
         "free ", "curr ", "ready", "recv ", "sleep", "susp ",
         "wait ", "rtime"};
     /* For argument '--help', emit help about the 'ps' command  */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s\n\n", args[0]);
         printf("Description:\n");
         printf("\tDisplays information about running processes\n");
         printf("Options:\n");
         printf("\t--help\t display this help and exit\n");
         return 0;
     }
     /* Check for valid number of arguments */
     if (nargs > 1) {
         fprintf(stderr, "%s: too many arguments\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     /* Print header for items from the process table */
     printf("%3s %-16s %5s %4s %4s %10s %-10s %10s\n",
            "Pid", "Name", "State", "Prio", "Ppid", "Stack Base",
            "Stack Ptr", "Stack Size");
     printf("%3s %-16s %5s %4s %4s %10s %-10s %10s\n",
            "---", "----------------", "-----", "----", "----",
            "----------", "----------", "----------");
     /* Output information for each process */
     for (i = 0; i < NPROC; i++) {
         prptr = &proctab[i];
         if (prptr->prstate == PR_FREE) {  /* skip unused slots  */
             continue;
         }
         printf("%3d %-16s %s %4d %4d 0x%08X 0x%08X %8d\n",
             i, prptr->prname, pstate[(int)prptr->prstate],
             prptr->prprio, prptr->prparent, prptr->prstkbase,
             prptr->prstkptr, prptr->prstklen);
     }
     return 0;
 }
xsh_sleep()
shellcmd xsh_sleep (int32 , char * [])
Definition at line 11 of file xsh_sleep.c.
References delay(), fprintf(), NULLCH, printf(), sleep(), stderr, and strncmp().
 {
     int32   delay;          /* Delay in seconds     */
     char    *chptr;         /* Walks through argument   */
     char    ch;         /* Next character of argument   */
     /* For argument '--help', emit help about the 'sleep' command   */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s\n\n", args[0]);
         printf("Description:\n");
         printf("\tDelay for a specified number of seconds\n");
         printf("Options:\n");
         printf("\t--help\t display this help and exit\n");
         return 0;
     }
     /* Check for valid number of arguments */
     if (nargs > 2) {
         fprintf(stderr, "%s: too many arguments\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     if (nargs != 2) {
         fprintf(stderr, "%s: argument in error\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     chptr = args[1];
     ch = *chptr++;
     delay = 0;
     while (ch != NULLCH) {
         if ( (ch < '0') || (ch > '9') ) {
             fprintf(stderr, "%s: nondigit in argument\n",
                 args[0]);
             return 1;
         }
         delay = 10*delay + (ch - '0');
         ch = *chptr++;
     }
     sleep(delay);
     return 0;
 }
xsh_udpdump()
shellcmd xsh_udpdump (int32 , char * [])
Definition at line 11 of file xsh_udpdump.c.
References fprintf(), printf(), stderr, strncmp(), udpentry::udcount, udpentry::udlocport, UDP_FREE, UDP_SLOTS, udpentry::udpid, udptab, udpentry::udremip, udpentry::udremport, and udpentry::udstate.
 {
     int32   i;          /* index into udptab        */
     char    *udpstate[] = {     /* names for entry states   */
         "free ", "used ", "recv "};
     struct  udpentry *uptr;     /* ptr to entry in udptab   */
     uint32  remip;          /* variables to hold the info   */
     int32   r1,r2,r3,r4;        /* from an entry for printing   */
     int32   remprt, locprt;
     int32   state;
     pid32   pid;
     /* For argument '--help', emit help about the 'udpdump' command */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s\n\n", args[0]);
         printf("Description:\n");
         printf("\tDisplays registerd UDP ports\n");
         printf("Options:\n");
         printf("\t--help\t display this help and exit\n");
         return 0;
     }
     /* Check for valid number of arguments */
     if (nargs > 1) {
         fprintf(stderr, "%s: no argumentd expected\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     /* Print header for items from UDP table */
     printf("%5s %5s %5s    %9s    %8s %8s %3s %4s\n",
         "Entry", "Iface", "State", "Remote IP", "Rem Port",
         "Loc Port", "Pid", "Pkts");
     printf("%5s %5s %5s %15s %8s %8s %3s %4s\n",
         "-----", "-----", "-----", "---------------", "--------",
         "--------", "---", "----");
     /* Output information for each valid entry in udptab */
     for (i = 0; i < UDP_SLOTS; i++) {
         uptr = &udptab[i];
         if (uptr->udstate == UDP_FREE) {  /* skip unused slots  */
         printf("%3d   ---- slot is free ---\n", i);
         continue;
         }
         remip = uptr->udremip;
         r1 = (remip >> 24) & 0xff;
         r2 = (remip >> 16) & 0xff;
         r3 = (remip >>  8) & 0xff;
         r4 = (remip      ) & 0xff;
         remprt = uptr->udremport;
         locprt = uptr->udlocport;
         pid = uptr->udpid;
         state = uptr->udstate;
         printf("  %4s %3d.%3d.%3d.%3d %5d    %6d%5d%6d\n",
           udpstate[state], r1, r2, r3, r4, remprt, locprt, pid,
                             uptr->udcount);
     }
     return 0;
 }
xsh_udpecho()
shellcmd xsh_udpecho (int32 , char * [])
Definition at line 14 of file xsh_udpecho.c.
References atoi(), delay(), dot2ip(), fprintf(), printf(), stderr, strncmp(), strnlen(), SYSERR, TIMEOUT, udp_recv(), udp_register(), udp_release(), and udp_send().
 {
     int i;          /* index into buffer        */
     int retval;         /* return value         */
     char    msg[] = "Xinu testing UDP echo"; /* message to send */
     char    inbuf[1500];        /* buffer for incoming reply    */
     int32   slot;           /* UDP slot to use      */
     int32   msglen;         /* length of outgoing message   */
     uint32  remoteip;       /* remote IP address to use */
     uint16  remport= 7;     /* remote port number to use    */
     uint16  locport = 52743;    /* local port to use        */
     int32   retries = 3;        /* number of retries        */
     int32   delay   = 500;      /* reception delay in ms    */
     /* For argument '--help', emit help about the 'udpecho' command */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s  REMOTEIP\n\n", args[0]);
         printf("Description:\n");
         printf("\tBounce a message off a remote UDP echo server\n");
         printf("Options:\n");
         printf("\tREMOTEIP:\tIP address in dotted decimal\n");
         printf("\t--help\t display this help and exit\n");
         return 0;
     }
     /* Check for valid IP address argument */
     if (nargs != 2) {
         fprintf(stderr, "%s: invalid number of argument(s)\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     if (dot2ip(args[1], &remoteip) == SYSERR) {
         fprintf(stderr, "%s: invalid IP address argument\r\n",
             args[0]);
         return 1;
     }
     if (nargs == 3) {
         retval = atoi(args[2]);
         if ( (retval <= 0) || (retval > 64535) ) {
             fprintf(stderr, "%s: invalid port argument\r\n",
                 args[0]);
             return 1;
         }
         remport = (uint16) retval;
     }
     fprintf(stderr, "using remote port %d\n", remport);
     /* register local UDP port */
     slot = udp_register(remoteip, remport, locport);
     if (slot == SYSERR) {
         fprintf(stderr, "%s: could not reserve UDP port %d\n",
                 args[0], locport);
         return 1;
     }
     /* Retry sending outgoing datagram and getting response */
     msglen = strnlen(msg, 1200);
     for (i=0; i<retries; i++) {
         retval = udp_send(slot, msg, msglen);
         if (retval == SYSERR) {
             fprintf(stderr, "%s: error sending UDP \n",
                 args[0]);
             return 1;
         }
         retval = udp_recv(slot, inbuf, sizeof(inbuf), delay);
         if (retval == TIMEOUT) {
             fprintf(stderr, "%s: timeout...\n", args[0]);
             continue;
         } else if (retval == SYSERR) {
             fprintf(stderr, "%s: error from udp_recv \n",
                 args[0]);
             udp_release(slot);
             return 1;
         }
         break;
     }
     udp_release(slot);
     if (retval == TIMEOUT) {
         fprintf(stderr, "%s: retry limit exceeded\n",
             args[0]);
         return 1;
     }
     /* Response received - check contents */
     if (retval != msglen) {
         fprintf(stderr, "%s: sent %d bytes and received %d\n",
             args[0], msglen, retval);
         return 1;
     }
     for (i = 0; i < msglen; i++) {
         if (msg[i] != inbuf[i]) {
             fprintf(stderr, "%s: reply differs at byte %d\n",
                 args[0], i);
             return 1;
         }
     }
     printf("UDP echo test was successful\n");
     return 0;
 }
xsh_udpeserver()
shellcmd xsh_udpeserver (int32 , char * [])
Definition at line 12 of file xsh_udpserver.c.
References fprintf(), getlocalip(), printf(), stderr, strncmp(), SYSERR, TIMEOUT, TRUE, udp_recvaddr(), udp_register(), and udp_sendto().
 {
     int32   retval;         /* return value from sys calls  */
     uint32  localip;        /* local IP address     */
     uint32  remip;          /* remote sender's IP address   */
     uint16  remport;        /* remote sender's UDP port */
     char    buff[1500];     /* buffer for incoming reply    */
     int32   msglen;         /* length of outgoing message   */
     int32   slot;           /* slot in UDP table        */
     uint16  echoserverport= 7;  /* port number for UDP echo */
     /* For argument '--help', emit a help message   */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s\n\n", args[0]);
         printf("Description:\n");
         printf("\tBecome a UDP echo server\n");
         printf("Options:\n");
         printf("\t--help\t display this help and exit\n");
         return 0;
     }
     /* Check for valid IP address argument */
     if (nargs != 1) {
         fprintf(stderr, "%s: no arguments expected\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     localip = getlocalip();
     if (localip == SYSERR) {
         fprintf(stderr,
             "%s: could not obtain a local IP address\n",
             args[0]);
         return 1;
     }
     /* register local UDP port */
     slot = udp_register(0, 0, echoserverport);
     if (slot == SYSERR) {
         fprintf(stderr, "%s: could not reserve UDP port %d\n",
                 args[0], echoserverport);
         return 1;
     }
     /* Do forever: read an incoming datagram and send it back */
     while (TRUE) {
         retval = udp_recvaddr(slot, &remip, &remport, buff,
                         sizeof(buff), 600000);
         if (retval == TIMEOUT) {
             continue;
         } else if (retval == SYSERR) {
             fprintf(stderr, "%s: error receiving UDP\n",
                 args[0]);
             return 1;
         }
         msglen = retval;
         retval = udp_sendto(slot, remip, remport, buff, msglen);
         if (retval == SYSERR) {
             fprintf(stderr, "%s: udp_sendto failed\n",
                 args[0]);
             return 1;
         }
     }
     return 0;
 }
xsh_uptime()
shellcmd xsh_uptime (int32 , char * [])
Definition at line 11 of file xsh_uptime.c.
References clktime, fprintf(), printf(), stderr, and strncmp().
 {
     uint32  days, hrs, mins, secs;  /* days, hours, minutes,  and   */
                     /*  seconds since system boot   */
     uint32  secperday = 86400;  /* seconds in a day     */
     uint32  secperhr  =  3600;  /* seconds in an hour       */
     uint32  secpermin =    60;  /* seconds in a minute      */
     /* For argument '--help', emit help about the 'uptime' command  */
     if (nargs == 2 && strncmp(args[1], "--help", 7) == 0) {
         printf("Use: %s\n\n", args[0]);
         printf("Description:\n");
         printf("\tDisplays time since the system booted\n");
         printf("Options:\n");
         printf("\t--help\t display this help and exit\n");
         return 0;
     }
     /* Check for valid number of arguments */
     if (nargs > 1) {
         fprintf(stderr, "%s: too many arguments\n", args[0]);
         fprintf(stderr, "Try '%s --help' for more information\n",
                 args[0]);
         return 1;
     }
     secs = clktime;     /* total seconds since boot */
     /* subtract number of whole days */
     days  = secs/secperday;
     secs -= days*secperday;
     /* subtract number of hours */
     hrs   = secs/secperhr;
     secs -= hrs*secperhr;
     /* subtract number of minutes */
     mins  = secs/secpermin;
     secs -= mins*secpermin;
     printf("Xinu has been up ");
     if (days > 0) {
         printf(" %d day(s) ", days);
     }
     if (hrs > 0) {
         printf(" %d hour(s) ", hrs);
     }
     if (mins > 0) {
         printf(" %d minute(s) ", mins);
     }
     if (secs > 0) {
         printf(" %d second(s) ", secs);
     }
     printf("\n");
     return 0;
 }