XINU: lib/memset.c File Reference
memset.c File Reference
指定のByteブロックに対して、同じ値をNバイト分書き込む。
Functions
void * memset (void *s, int c, int n)
指定のByteブロックに対して、同じ値をNバイト分書き込む。
Detailed Description
指定のByteブロックに対して、同じ値をNバイト分書き込む。
Definition in file memset.c.
Function Documentation
memset()
void* memset (void * s, int c, int n)
指定のByteブロックに対して、同じ値をNバイト分書き込む。
Parameters
[in,out] s Byteブロックへのポインタ（例：文字列）
[in] c 書き込む値（1Byte）
[in] n 書き込むサイズ（Byte）
Returns
書き込み完了後のByteブロックへのポインタ
Definition at line 13 of file memset.c.
Referenced by arp_alloc(), arp_resolve(), dhcp_bld_bootp_msg(), dnslookup(), ethinit(), ethwrite(), getutime(), if(), lfdballoc(), lflinit(), lfscreate(), lfsinit(), net_init(), rdscontrol(), rdsopen(), rdsprocess(), rflread(), rflwrite(), rfscontrol(), rfsopen(), tftpget_mb(), and xsh_rdstest().
 {
     register int i;
     char *cp = (char *)s;
     for (i = 0; i < n; i++)
     {
         *cp = (unsigned char)c;
         cp++;
     }
     return s;
 }