XINU: device/lfs/lflputc.c File Reference
lflputc.c File Reference
#include <xinu.h>
Functions
devcall lflputc (struct dentry *devptr, char ch)
Function Documentation
lflputc()
devcall lflputc (struct dentry * devptr, char ch)
Definition at line 9 of file lflputc.c.
References dentry::dvminor, ldentry::ld_size, LF_BLKSIZ, Lf_data, lfdata::lf_dirdirty, LF_USED, lflcblk::lfbyte, lflcblk::lfdbdirty, lflcblk::lfdblock, lflcblk::lfdirptr, lfltab, lflcblk::lfmutex, lflcblk::lfpos, lfsetup(), lflcblk::lfstate, OK, signal(), SYSERR, TRUE, and wait().
Referenced by lflwrite().
 {
     struct  lflcblk *lfptr;     /* Ptr to open file table entry */
     struct  ldentry *ldptr;     /* Ptr to file's entry in the   */
                     /*  in-memory directory     */
     /* Obtain exclusive use of the file */
     lfptr = &lfltab[devptr->dvminor];
     wait(lfptr->lfmutex);
     /* If file is not open, return an error */
     if (lfptr->lfstate != LF_USED) {
         signal(lfptr->lfmutex);
         return SYSERR;
     }
     /* Return SYSERR for an attempt to skip bytes beyond the byte   */
     /*  that is currently the end of the file           */
     ldptr = lfptr->lfdirptr;
     if (lfptr->lfpos > ldptr->ld_size) {
         signal(lfptr->lfmutex);
         return SYSERR;
     }
     /* If pointer is outside current block, set up new block */
     if (lfptr->lfbyte >= &lfptr->lfdblock[LF_BLKSIZ]) {
         /* Set up block for current file position */
         lfsetup(lfptr);
     }
     /* If appending a byte to the file, increment the file size.    */
     /*   Note: comparison might be equal, but should not be greater.*/
     if (lfptr->lfpos >= ldptr->ld_size) {
         ldptr->ld_size++;
         Lf_data.lf_dirdirty = TRUE;
     }
     /* Place byte in buffer and mark buffer "dirty" */
     *lfptr->lfbyte++ = ch;
     lfptr->lfpos++;
     lfptr->lfdbdirty = TRUE;
     signal(lfptr->lfmutex);
     return OK;
 }