XINU: system/wakeup.c File Reference
wakeup.c File Reference
#include <xinu.h>
Functions
void wakeup (void)
Function Documentation
wakeup()
void wakeup (void)
Definition at line 9 of file wakeup.c.
References DEFER_START, DEFER_STOP, dequeue(), firstkey, nonempty, ready(), resched_cntl(), and sleepq.
Referenced by clkhandler().
 {
     /* Awaken all processes that have no more time to sleep */
     resched_cntl(DEFER_START);
     while (nonempty(sleepq) && (firstkey(sleepq) <= 0)) {
         ready(dequeue(sleepq));
     }
     resched_cntl(DEFER_STOP);
     return;
 }