XINU: system/panic.c File Reference
panic.c File Reference
Panic状態に陥った旨のメッセージを表示し、全てのプロセスを停止させる。
#include <xinu.h>
Functions
void panic (char *msg)
Panic状態に陥った旨のメッセージを表示し、全てのプロセスを停止させる。
Detailed Description
Panic状態に陥った旨のメッセージを表示し、全てのプロセスを停止させる。
Definition in file panic.c.
Function Documentation
panic()
void panic (char * msg)
Panic状態に陥った旨のメッセージを表示し、全てのプロセスを停止させる。
割り込み禁止後にPanicメッセージを表示し、無限ループを行う。
Parameters
[in] msg 表示するメッセージ
Definition at line 12 of file panic.c.
References disable(), kprintf(), and TRUE.
Referenced by icmp_mkpkt(), irq_dispatch(), lfdballoc(), lfiballoc(), lfsckfmt(), net_init(), netin(), ptinit(), ptsend(), rdsbufalloc(), rdsinit(), rdsprocess(), and rfsinit().
 {
     disable(); /* Disable interrupts        */
     kprintf("\n\n\rpanic: %s\n\n", msg);
     while (TRUE)
     {
         ;
     } /* Busy loop forever      */
 }