XINU: system/getpid.c File Reference
getpid.c File Reference
現在実行中のプロセスIDを返す。
#include <xinu.h>
Functions
pid32 getpid (void)
現在実行中のプロセスIDを返す。
Detailed Description
現在実行中のプロセスIDを返す。
Definition in file getpid.c.
Function Documentation
getpid()
pid32 getpid (void)
現在実行中のプロセスIDを返す。
Returns
現在実行中のプロセスIDを返す（グローバル変数currpidをそのまま返す）
Definition at line 11 of file getpid.c.
References currpid.
Referenced by create(), exit(), rdscontrol(), rdsread(), rdswrite(), and userret().
 {
     return (currpid);
 }