XINU: lib/printf.c File Reference
printf.c File Reference
#include <xinu.h>
#include <stdio.h>
#include <stdarg.h>
Functions
void _fdoprnt (char *, va_list, int(*)(did32, char), int)
int printf (const char *fmt,...)
Function Documentation
_fdoprnt()
void _fdoprnt (char * , va_list , int(*)(did32, char) , int)
Referenced by printf().
printf()
int printf (const char * fmt, ...)
Definition at line 13 of file printf.c.
References _fdoprnt(), putc(), stdout, va_end, and va_start.
Referenced by arp_dmp(), arp_dump(), main(), printFreeList(), printMemUse(), xsh_argecho(), xsh_arp(), xsh_cat(), xsh_clear(), xsh_date(), xsh_devdump(), xsh_echo(), xsh_help(), xsh_kill(), xsh_ls(), xsh_memdump(), xsh_memstat(), xsh_netinfo(), xsh_ping(), xsh_ps(), xsh_sleep(), xsh_udpdump(), xsh_udpecho(), xsh_udpeserver(), and xsh_uptime().
 {
     va_list ap;
     syscall putc(did32, char);
     va_start(ap, fmt);
     _fdoprnt((char *)fmt, ap, putc, stdout);
     va_end(ap);
     return 0;
 }